"use client";

import { ArrowUpRight, BriefcaseBusiness, Check, CircleOff, ExternalLink, Sparkles } from "lucide-react";
import type { ManagedWork, WorkspaceProduct } from "./contracts";
import styles from "./workspace-layout.module.css";

/**
 * A managed-work link is deliberately smaller than the tenant model. The
 * workspace API supplies only authorized, user-visible destinations here;
 * discovery must not reconstruct a portfolio from relationship labels.
 */
export type ManagedWorkSummary = ManagedWork;

interface Props {
  products: readonly WorkspaceProduct[];
  managedWork?: readonly ManagedWorkSummary[];
  managedWorkUnavailable?: boolean;
  onStartAiVisibility: () => void;
}

const CONSUMER_PRODUCT_IDS = new Set(["ai_visibility", "managed_presence", "homefinder"]);

export function discoveryProducts(products: readonly WorkspaceProduct[]) {
  return products.filter((product) => CONSUMER_PRODUCT_IDS.has(product.id));
}

export function sameAppHref(href: string): string | null {
  // Managed work links are generated by the server. Keep this UI defensive so
  // a malformed or unrelated external value never becomes an unexpected
  // navigation. Production managed links may be absolute because they point
  // at the app host rather than the marketing host.
  if (typeof href !== "string") return null;
  const value = href.trim();
  if (value.startsWith("/") && !value.startsWith("//")) return value;
  try {
    const url = new URL(value);
    const trustedHost = url.hostname === "app.strelva.com"
      || (url.protocol === "http:" && ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname));
    return trustedHost ? value : null;
  } catch {
    return null;
  }
}

function relationshipLabel(relationship: ManagedWorkSummary["relationship"]): string {
  return relationship === "enterprise" ? "Enterprise" : "Client";
}

export function WorkspaceProductDiscovery({ products, managedWork = [], managedWorkUnavailable = false, onStartAiVisibility }: Props) {
  const available = discoveryProducts(products);

  return (
    <section id="workspace-products" className={styles.productShelf} aria-labelledby="workspace-products-title">
      <div className={styles.productShelfHeader}>
        <div>
          <p className={styles.productShelfEyebrow}>Explore</p>
          <h2 id="workspace-products-title">Products</h2>
        </div>
        <Sparkles aria-hidden="true" size={16} strokeWidth={1.5} />
      </div>

      {!available.length ? (
        <p className={styles.productShelfEmpty}>No products are available in this workspace.</p>
      ) : (
        <div className={styles.productList}>
          {available.map((product) => {
            if (product.id === "ai_visibility") {
              return (
                <article key={product.id} className={styles.productItem} data-product-id={product.id}>
                  <div className={styles.productItemIcon} aria-hidden="true"><Sparkles size={15} strokeWidth={1.5} /></div>
                  <div className={styles.productItemBody}>
                    <h3>{product.name}</h3>
                    <p>{product.description}</p>
                    {product.availability === "available" ? (
                      <button type="button" className={styles.productAction} onClick={onStartAiVisibility}>
                        Check a business <ArrowUpRight size={13} strokeWidth={1.6} />
                      </button>
                    ) : (
                      <p className={styles.productUnavailable}>Not available in this workspace.</p>
                    )}
                  </div>
                </article>
              );
            }

            if (product.id === "managed_presence") {
              return (
                <article key={product.id} className={styles.productItem} data-product-id={product.id}>
                  <div className={styles.productItemIcon} aria-hidden="true"><BriefcaseBusiness size={15} strokeWidth={1.5} /></div>
                  <div className={styles.productItemBody}>
                    <h3>{product.name}</h3>
                    <p>{product.description}</p>
                    {managedWorkUnavailable ? (
                      <p className={styles.productShelfEmpty}>Managed website destinations are temporarily unavailable. Nothing has changed.</p>
                    ) : managedWork.length ? (
                      <ul className={styles.managedWorkList} aria-label="Authorized managed work">
                        {managedWork.map((work) => {
                          const href = sameAppHref(work.href);
                          return (
                            <li key={work.id}>
                              {href ? (
                                <a href={href} className={styles.managedWorkLink}>
                                  <span className={styles.managedWorkName}>{work.title}</span>
                                  <span className={styles.managedWorkMeta}>{relationshipLabel(work.relationship)} <ExternalLink aria-hidden="true" size={12} strokeWidth={1.5} /></span>
                                </a>
                              ) : (
                                <span className={styles.managedWorkLink} data-unavailable="true">
                                  <span className={styles.managedWorkName}>{work.title}</span>
                                  <span className={styles.managedWorkMeta}>Destination unavailable</span>
                                </span>
                              )}
                            </li>
                          );
                        })}
                      </ul>
                    ) : (
                      <p className={styles.productShelfEmpty}>No authorized managed websites in this workspace.</p>
                    )}
                  </div>
                </article>
              );
            }

            // Homefinder stays visible only when the server supplied a catalog
            // item, and it remains an honest disabled state until its external
            // authorization and inventory gates are met.
            return (
              <article key={product.id} className={styles.productItem} data-product-id={product.id} data-product-state="not-enabled">
                <div className={styles.productItemIcon} aria-hidden="true"><CircleOff size={15} strokeWidth={1.5} /></div>
                <div className={styles.productItemBody}>
                  <div className={styles.productTitleRow}><h3>{product.name}</h3><span className={styles.productState}>Not enabled</span></div>
                  <p>{product.description}</p>
                  <p className={styles.productUnavailable}><Check aria-hidden="true" size={13} strokeWidth={1.7} /> This product is not enabled for this workspace.</p>
                </div>
              </article>
            );
          })}
        </div>
      )}
    </section>
  );
}
