export const SCAFFOLD_PLAN_MONTHLY_PRICE_CENTS = 14900;
export const SCAFFOLD_PLAN_MONTHLY_PRICE_DOLLARS = SCAFFOLD_PLAN_MONTHLY_PRICE_CENTS / 100;
export const SCAFFOLD_PLAN_MONTHLY_PRICE_CURRENCY = "usd";
export const SCAFFOLD_PLAN_MONTHLY_PRICE_LABEL = "$149/mo";
export const SCAFFOLD_PLAN_MONTHLY_PRICE_DESCRIPTION = "exactly $149/month";
