"use client";
import { useEffect, useRef, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { SelectInput, TextInput } from "@/components/ui/TextInput";
import { homeFinderBindingSchema } from "@/products/home-finder/runtime-contracts";
const viewSchema = z.object({ bindings: z.array(homeFinderBindingSchema.extend({ changeNumber: z.number().int().positive() })), catalog: z.object({ name: z.string(), requirements: z.array(z.string()) }) });
type View = z.infer<typeof viewSchema>;
export function HomeFinder({ workspaceId, agencies }: { workspaceId: string; agencies: { id: string; name: string }[] }) { return <HomeFinderLoader key={workspaceId} workspaceId={workspaceId} agencies={agencies} />; }
function HomeFinderLoader({ workspaceId, agencies }: { workspaceId: string; agencies: { id: string; name: string }[] }) {
  const [view, setView] = useState<View | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [attempt, setAttempt] = useState(0), [busy, setBusy] = useState(false);
  const [agencyId, setAgencyId] = useState(""), [name, setName] = useState(""), [installation, setInstallation] = useState(""), [brokerage, setBrokerage] = useState(""), [origin, setOrigin] = useState(""), [license, setLicense] = useState(""), [expiry, setExpiry] = useState(""), [source, setSource] = useState("");
  const pending = useRef<Record<string, unknown> | null>(null), inflight = useRef(false);
  useEffect(() => {
    const controller = new AbortController();
    void fetch(`/api/workspace/home-finder?workspaceId=${encodeURIComponent(workspaceId)}`, { credentials: "same-origin", signal: controller.signal }).then(async response => { const raw: unknown = await response.json(); if (!response.ok) throw new Error("Home Finder could not be loaded. Current business access and the release gate are required."); const value = viewSchema.parse(raw); if (value.bindings.some(b => b.workspaceId !== workspaceId)) throw new Error("The business changed."); if (!controller.signal.aborted) { setView(value); setError(""); } }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Home Finder is unavailable."); });
    return () => controller.abort();
  }, [workspaceId, attempt]);
  async function change(input: Record<string, unknown>) {
    if (inflight.current) return; inflight.current = true; pending.current = input; setBusy(true); setError("");
    try {
      const response = await fetch("/api/workspace/home-finder", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) });
      const result: unknown = await response.json(); if (!response.ok) throw new Error(result && typeof result === "object" && "error" in result && typeof result.error === "string" ? result.error : "The operation could not be confirmed. Reload current state before changing it.");
      pending.current = null; setNotice(input.action === "install" ? "The brokerage System is prepared as a draft. It needs licensed-provider qualification before going live." : input.action === "publish" ? "The native System is live. Current grants, licensing and feed evidence are checked on every new inquiry." : "The current result is recorded. Review its evidence below."); setAttempt(v => v + 1);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The operation could not be confirmed."); }
    finally { inflight.current = false; setBusy(false); }
  }
  const locked = busy || Boolean(pending.current);
  return <main className="mx-auto max-w-4xl space-y-8 p-6 sm:p-10"><header><h1 className="font-display text-3xl">Home Finder</h1><p className="mt-3 text-gray-muted">Install brokerage-branded home search. The brokerage owns its System, inquiries and exit. Provider permission and verified delivery are required before buyers can use it.</p></header>{notice ? <p role="status">{notice}</p> : null}{error ? <div className="space-y-3"><p role="alert" className="text-critical">{error}</p>{pending.current ? <Button disabled={busy} onClick={() => pending.current && void change(pending.current)}>Retry the same request</Button> : null}<Button variant="secondary" disabled={busy} onClick={() => { pending.current = null; setAttempt(v => v + 1); }}>Reload current state</Button></div> : null}{!view && !error ? <p role="status">Reading installations…</p> : null}
    {view?.bindings.map(binding => <section key={binding.id} className="space-y-4 border-b border-gray-border pb-8" aria-label={`${binding.brokerageName} installation`}><h2 className="font-display text-xl">{binding.brokerageName}</h2><p>{binding.lifecycle} · {binding.status} · {binding.runtimeAllowed ? "Current admission confirmed" : "Qualification or current grant required"}</p><p className="break-words text-sm text-gray-muted">Licensed source: {binding.sourceName} · License expires {new Date(binding.licenseExpiresAt).toLocaleDateString()}</p><a className="inline-flex min-h-11 items-center text-accent-text underline" href={`/workspace?workspaceId=${encodeURIComponent(workspaceId)}&systemId=${encodeURIComponent(binding.systemId)}`}>Open this System</a>{binding.readiness ? <ul className="space-y-2 text-sm">{binding.readiness.map(item => <li key={item.requirement}><strong>{item.requirement}</strong> · {item.state}<span className="block text-gray-muted">{item.source} · {item.responsibleParty}</span></li>)}</ul> : <p className="text-sm text-gray-muted">No provider qualification has been observed.</p>}
      {binding.status === "active" ? <div className="flex flex-wrap gap-3"><Button variant="secondary" disabled={locked} onClick={() => void change({ action: "check", workspaceId, bindingId: binding.id })}>Check provider readiness</Button>{binding.lifecycle !== "live" ? <Button disabled={locked} onClick={() => void change({ action: "publish", workspaceId, bindingId: binding.id, expectedChange: binding.changeNumber })}>Verify and go live</Button> : <Button variant="secondary" disabled={locked} onClick={() => void change({ action: "pause", workspaceId, bindingId: binding.id, expectedChange: binding.changeNumber })}>Pause new inquiries</Button>}<Button variant="danger" disabled={locked} onClick={() => void change({ action: "revoke", workspaceId, bindingId: binding.id, expectedRevision: binding.revision })}>Revoke installation grant</Button></div> : null}{binding.lifecycle === "live" && binding.runtimeAllowed ? <a className="inline-flex min-h-11 items-center text-accent-text underline" href={binding.approvedOrigin}>Open approved brokerage website</a> : null}<p className="text-xs text-gray-muted">Pausing or revoking stops new native intake. Previously accepted inquiries keep their delivery and receipt obligations.</p></section>)}
    {view && !view.bindings.length ? <p>No brokerage installations yet.</p> : null}
    {agencies.length ? <form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!locked) void change({ action: "install", workspaceId, agencyId, name, externalInstallationId: installation, brokerageName: brokerage, approvedOrigin: origin, licenseReference: license, licenseExpiresAt: new Date(expiry).toISOString(), sourceName: source, commandId: crypto.randomUUID() }); }}><h2 className="font-display text-xl">Prepare an installation</h2><p className="text-sm text-gray-muted">Use the brokerage-signed provider installation and evidence references. Draft preparation does not establish provider approval.</p><SelectInput label="Installing agency" value={agencyId} required disabled={locked} onChange={e => setAgencyId(e.target.value)} options={[{ value: "", label: "Choose an agency" }, ...agencies.map(a => ({ value: a.id, label: a.name }))]} />{[["System name", name, setName], ["Brokerage name", brokerage, setBrokerage], ["Licensed provider installation reference", installation, setInstallation], ["Approved HTTPS brokerage origin", origin, setOrigin], ["Broker-signed license evidence reference", license, setLicense], ["Exact licensed feed name", source, setSource]].map(([label, value, setter]) => <TextInput key={String(label)} label={String(label)} value={String(value)} required maxLength={500} disabled={locked} onChange={e => (setter as (value: string) => void)(e.target.value)} />)}<TextInput label="License expiry" type="datetime-local" required value={expiry} disabled={locked} onChange={e => setExpiry(e.target.value)} /><Button type="submit" loading={busy} disabled={locked || !agencyId}>Prepare brokerage System</Button></form> : <p className="text-sm text-gray-muted">An agency owner or administrator can prepare an installation with current business access. A platform support role grants no agency authority.</p>}
  </main>;
}
