"use client";
import { useRef, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { TextArea, TextInput } from "@/components/ui/TextInput";
import { homeFinderSearchResultSchema, type HomeFinderInquiry } from "@/products/home-finder/runtime-contracts";
import type { HomeFinderDeliveryDetail } from "@/platform/customers/home-finder-port";
type Search = z.infer<typeof homeFinderSearchResultSchema>;
const resultSchema = z.object({ status: z.enum(["pending", "delivered", "unavailable"]), requestId: z.string().uuid(), message: z.string(), reference: z.string() });
export function HomeFinderBuyer({ bindingId, entryToken, brokerageName }: { bindingId: string; entryToken: string; brokerageName: string }) {
  return <BuyerSearch key={bindingId} bindingId={bindingId} entryToken={entryToken} brokerageName={brokerageName} />;
}
function BuyerSearch({ bindingId, entryToken, brokerageName }: { bindingId: string; entryToken: string; brokerageName: string }) {
  const [query, setQuery] = useState(""), [result, setResult] = useState<Search | null>(null), [selected, setSelected] = useState<Search["listings"][number] | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const token = useRef(entryToken);
  async function currentEntry() { const response = await fetch(`${endpoint}?renew=1`, { credentials: "omit", headers: { "x-home-finder-entry": token.current } }); const value = z.object({ token: z.string() }).parse(await response.json()); if (!response.ok) throw new Error("Reopen Home Finder on the brokerage website."); token.current = value.token; return value.token; }
  const endpoint = `/api/home-finder/${encodeURIComponent(bindingId)}`;
  async function search() {
    if (busy) return; setBusy(true); setError("");
    try { const response = await fetch(`${endpoint}?${new URLSearchParams({ q: query, limit: "20" })}`, { credentials: "omit", headers: { "x-home-finder-entry": await currentEntry() } }); const body: unknown = await response.json(); if (!response.ok) throw new Error("Licensed listings are currently unavailable. Your inquiry has not been started."); setResult(homeFinderSearchResultSchema.parse(body)); setSelected(null); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Search is unavailable."); } finally { setBusy(false); }
  }
  return <main className="mx-auto max-w-5xl space-y-8 p-6 sm:p-10"><header><p className="text-sm text-gray-muted">{brokerageName}</p><h1 className="font-display text-3xl">Find your home</h1><p className="mt-3 text-gray-muted">Search current brokerage listings, then ask the brokerage about a home. Your contact details go to its verified inquiry destination.</p></header><form className="flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={event => { event.preventDefault(); void search(); }}><TextInput label="City, area or address" value={query} maxLength={160} disabled={busy || Boolean(selected)} onChange={e => setQuery(e.target.value)} /><Button type="submit" disabled={busy || Boolean(selected)} loading={busy}>Search homes</Button></form>{error ? <p role="alert" className="text-critical">{error}</p> : null}
    {result ? <section aria-label="Search results"><p className="text-sm text-gray-muted">{result.source.name} · Feed checked {new Date(result.sourceCheckedAt).toLocaleString()} · {result.count} results</p>{result.listings.length ? <ul className="mt-5 divide-y divide-gray-border">{result.listings.map(listing => <li key={listing.id} className="space-y-3 py-6"><h2 className="font-display text-xl">{listing.address.line}</h2><p>{listing.address.city}, {listing.address.state} {listing.address.postalCode}</p><p className="font-medium">{new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(listing.price)} · {listing.bedrooms ?? "—"} beds · {listing.bathrooms ?? "—"} baths</p><p className="text-sm">{listing.publicRemarks}</p><p className="text-xs text-gray-muted">Listing brokerage: {listing.listOfficeName ?? "Not supplied"} · Agent: {listing.listAgentName ?? "Not supplied"} · MLS source: {listing.sourceSystemName ?? result.source.name}</p><Button variant="secondary" disabled={Boolean(selected)} onClick={() => setSelected(listing)}>Ask about {listing.address.line}</Button></li>)}</ul> : <p className="mt-5">No displayable homes match this search. Try a different city or area.</p>}</section> : !error ? <p className="text-gray-muted">Choose an area to see current, permitted listings.</p> : null}
    {selected ? <BuyerInquiry key={selected.id} bindingId={bindingId} listing={selected} currentEntry={currentEntry} onClose={() => setSelected(null)} /> : null}
  </main>;
}
function BuyerInquiry({ bindingId, listing, onClose, currentEntry }: { bindingId: string; listing: Search["listings"][number]; currentEntry: () => Promise<string>; onClose: () => void }) {
  const [name, setName] = useState(""), [email, setEmail] = useState(""), [phone, setPhone] = useState(""), [message, setMessage] = useState(""), [consent, setConsent] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [receipt, setReceipt] = useState<z.infer<typeof resultSchema> | null>(null), [delivery, setDelivery] = useState<HomeFinderDeliveryDetail | null>(null);
  const pending = useRef<HomeFinderInquiry | null>(null), inflight = useRef(false), endpoint = `/api/home-finder/${encodeURIComponent(bindingId)}`;
  async function send() {
    if (inflight.current || receipt) return; inflight.current = true; setBusy(true); setError("");
    pending.current ??= { submissionId: crypto.randomUUID(), listing: { id: listing.id, address: [listing.address.line, listing.address.city, listing.address.state, listing.address.postalCode].filter(Boolean).join(", "), inquiryToken: listing.inquiryToken }, buyer: { name, email, ...(phone ? { phone } : {}) }, ...(message ? { message } : {}), consent: true };
    try { const response = await fetch(endpoint, { method: "POST", credentials: "omit", headers: { "Content-Type": "application/json", "x-home-finder-entry": await currentEntry() }, body: JSON.stringify(pending.current) }); const body: unknown = await response.json(); if (!response.ok) throw new Error("Delivery could not be confirmed. Retry this same inquiry or contact the brokerage with the request ID."); const value = resultSchema.parse(body); if (value.requestId !== pending.current.submissionId) throw new Error("The receipt could not be confirmed."); setReceipt(value); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Delivery could not be confirmed."); } finally { inflight.current = false; setBusy(false); }
  }
  async function checkReceipt() {
    if (!receipt || busy) return; setBusy(true); setError("");
    try { const response = await fetch(`${endpoint}?${new URLSearchParams({ submissionId: receipt.requestId, receipt: receipt.reference })}`, { credentials: "omit" }); if (!response.ok) throw new Error("Delivery evidence is unavailable. Keep your request ID; do not start another inquiry."); const value: unknown = await response.json(); const parsed = z.object({ installationId: z.string(), reference: z.string(), state: z.enum(["pending", "delivered", "bounced", "failed"]), occurredAt: z.string(), expiresAt: z.string(), observedAt: z.string(), schemaVersion: z.literal("1") }).strict().parse(value); if (parsed.reference !== receipt.reference) throw new Error("The receipt scope could not be confirmed."); setDelivery(parsed); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Delivery evidence is unavailable."); } finally { setBusy(false); }
  }
  const locked = busy || Boolean(pending.current);
  return <section aria-label="Listing inquiry" className="space-y-4 border-t border-gray-border pt-8"><h2 className="font-display text-xl">Ask about {listing.address.line}</h2>{error ? <p role="alert" className="text-critical">{error}</p> : null}{pending.current ? <p className="break-words text-xs text-gray-muted">Request ID: {pending.current.submissionId}. A failed readback can still mean the provider accepted the inquiry.</p> : null}{receipt ? <><p role="status">{delivery ? `Delivery: ${delivery.state}` : receipt.message}</p><p className="text-sm text-gray-muted">Queued is awaiting delivery. Only verified provider delivery evidence confirms it reached the destination.</p><Button variant="secondary" disabled={busy} loading={busy} onClick={() => void checkReceipt()}>Check delivery receipt</Button><Button variant="ghost" disabled={busy} onClick={onClose}>Done</Button></> : <form className="space-y-4" onSubmit={event => { event.preventDefault(); if (consent) void send(); }}><TextInput label="Your name" required maxLength={120} value={name} disabled={locked} onChange={e => setName(e.target.value)} /><TextInput label="Email" type="email" required maxLength={254} value={email} disabled={locked} onChange={e => setEmail(e.target.value)} /><TextInput label="Phone (optional)" type="tel" maxLength={40} value={phone} disabled={locked} onChange={e => setPhone(e.target.value)} /><TextArea label="Your question" maxLength={2000} value={message} disabled={locked} onChange={e => setMessage(e.target.value)} /><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={consent} required disabled={locked} onChange={e => setConsent(e.target.checked)} />I agree to share this inquiry and my contact details with the brokerage about this listing.</label><div className="flex flex-wrap gap-3"><Button type="submit" disabled={busy || !consent} loading={busy}>{pending.current ? "Retry the same inquiry" : "Send inquiry"}</Button>{!pending.current ? <Button variant="ghost" type="button" disabled={busy} onClick={onClose}>Cancel</Button> : null}</div></form>}</section>;
}
