"use client";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/Button";
import { SelectInput, TextInput } from "@/components/ui/TextInput";
import { unitVersionChoicesSchema, unitsViewSchema, type Unit, type UnitCommand, type UnitsView } from "@/platform/enterprise/contracts";
type Business = { id: string; name: string; role?: string };
export function Units({ organizationId, businesses, canManage }: { organizationId: string; businesses: Business[]; canManage: boolean }) {
  return <UnitsLoader key={organizationId} organizationId={organizationId} businesses={businesses} canManage={canManage} />;
}
function UnitsLoader({ organizationId, businesses, canManage }: { organizationId: string; businesses: Business[]; canManage: boolean }) {
  const [view, setView] = useState<UnitsView | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [attempt, setAttempt] = useState(0), [pending, setPending] = useState(false);
  const [name, setName] = useState(""), [businessId, setBusinessId] = useState(""), [parentId, setParentId] = useState(""), [kind, setKind] = useState<Unit["kind"]>("location");
  const [editing, setEditing] = useState<Unit | null>(null), [bindingUnit, setBindingUnit] = useState<Unit | null>(null), [versions, setVersions] = useState<{ id: string; name: string; context: string; baselineRevision: number; assigned: boolean }[]>([]), [versionId, setVersionId] = useState("");
  const command = useRef<UnitCommand | null>(null), inflight = useRef(false);
  useEffect(() => {
    const controller = new AbortController();
    void fetch(`/api/workspace/units?organizationId=${encodeURIComponent(organizationId)}`, { credentials: "same-origin", signal: controller.signal }).then(async response => {
      const value: unknown = await response.json(); if (!response.ok) throw new Error("The Units could not be loaded. Your current organization and business memberships are required.");
      const result = unitsViewSchema.parse(value); if (result.organizationId !== organizationId) throw new Error("The organization changed.");
      if (!controller.signal.aborted) { setView(result); setError(""); }
    }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Units are unavailable."); });
    return () => controller.abort();
  }, [organizationId, attempt]);
  async function change(input: UnitCommand) {
    if (inflight.current) return; inflight.current = true; setPending(true); setError(""); command.current = input;
    try {
      const response = await fetch("/api/workspace/units", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) });
      const value: unknown = await response.json();
      if (!response.ok) throw new Error(value && typeof value === "object" && "error" in value && typeof value.error === "string" ? value.error : "The change could not be confirmed. Reload the hierarchy before trying again.");
      command.current = null; setNotice("The Unit change is recorded in audit."); setAttempt(value => value + 1); setName(""); setEditing(null); setBindingUnit(null);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The change could not be confirmed."); }
    finally { inflight.current = false; setPending(false); }
  }
  async function chooseVersions(unit: Unit) {
    setBindingUnit(unit); setVersions([]); setVersionId(""); setError("");
    try { const response = await fetch(`/api/workspace/units?${new URLSearchParams({ organizationId, unitId: unit.id })}`, { credentials: "same-origin" }); if (!response.ok) throw new Error("Business Versions could not be loaded."); const value = unitVersionChoicesSchema.parse(await response.json()); if (value.unitId !== unit.id || value.businessId !== unit.businessId) throw new Error("The Unit changed."); setVersions(value.versions); } catch (cause) { setError(cause instanceof Error ? cause.message : "Versions unavailable."); }
  }
  function depth(unit: Unit) { const seen = new Set<string>(); let current: Unit | undefined = unit; while (current?.parentId && !seen.has(current.parentId)) { seen.add(current.parentId); current = view?.units.find(item => item.id === current?.parentId); } return Math.min(seen.size, 6); }
  const managed = businesses.filter(b => b.role === "owner" || b.role === "admin");
  return <main className="mx-auto max-w-4xl space-y-8 p-6 sm:p-10"><header><h1 className="font-display text-3xl text-warm-black">Business Units</h1><p className="mt-3 text-gray-muted">Organize businesses, locations and franchises. Each keeps its own people, accounts, records and Versions.</p><a className="mt-4 inline-block text-accent-text underline" href={`/workspace/access-review?workspaceId=${encodeURIComponent(organizationId)}`}>Review people and access</a></header>
    {notice ? <p role="status">{notice}</p> : null}{error ? <div><p role="alert" className="text-critical">{error}</p>{command.current ? <Button variant="secondary" disabled={pending} onClick={() => command.current && void change(command.current)}>Retry the same change</Button> : null}<Button variant="secondary" disabled={pending} onClick={() => { command.current = null; setAttempt(value => value + 1); }}>Reload current hierarchy</Button></div> : null}
    {!view && !error ? <p role="status">Loading Units…</p> : null}
    {view ? <section aria-label="Unit hierarchy"><p className="text-sm text-gray-muted">{view.inaccessibleUnits ? `${view.inaccessibleUnits} Units are unavailable to your account. Their names and records are excluded.` : "You can see every Unit in this organization."} Structure grants no access.</p>{view.units.length ? <ul className="mt-4 divide-y divide-gray-border">{view.units.map(unit => <li key={unit.id} className="flex flex-col gap-3 py-5 sm:flex-row sm:justify-between"><div className="min-w-0"><p className="break-words font-medium">{depth(unit) ? `${"↳ ".repeat(depth(unit))}` : ""}{unit.name}</p><p className="mt-1 text-sm text-gray-muted">{unit.kind} · {unit.status} · {businesses.find(b => b.id === unit.businessId)?.name ?? "Business"}</p><p className="mt-1 text-sm text-gray-muted">{unit.versionIds.length} business-owned Versions</p></div>{canManage && managed.some(b => b.id === unit.businessId) && unit.status === "active" ? <div className="flex flex-wrap gap-3"><Button variant="secondary" disabled={pending} onClick={() => { setEditing(unit); setName(unit.name); setBusinessId(unit.businessId); setKind(unit.kind); setParentId(unit.parentId ?? ""); }}>Edit {unit.name}</Button><Button variant="secondary" disabled={pending} onClick={() => void chooseVersions(unit)}>Bind a Version</Button><Button variant="secondary" disabled={pending} onClick={() => void change({ action: "archive", organizationId, id: unit.id, expectedRevision: unit.revision })}>Archive {unit.name}</Button></div> : null}</li>)}</ul> : <p className="mt-5">No Units yet. Add a business or location below.</p>}</section> : null}
    {bindingUnit ? <section className="space-y-4" aria-label="Unit Version binding"><h2 className="font-display text-xl">Versions for {bindingUnit.name}</h2><p className="text-sm text-gray-muted">Only this business’s own Versions can be attached. A binding changes structure; it grants no source, account or customer access.</p><SelectInput label="Business Version" value={versionId} disabled={pending} onChange={e => setVersionId(e.target.value)} options={[{ value: "", label: "Choose a Version" }, ...versions.filter(v => !v.assigned).map(v => ({ value: v.id, label: `${v.name} · ${v.context} · source revision ${v.baselineRevision}` }))]} /><Button disabled={pending || !versionId} onClick={() => void change({ action: "bind_version", organizationId, id: bindingUnit.id, versionId, expectedRevision: bindingUnit.revision })}>Bind business-owned Version</Button></section> : null}
    {canManage ? <form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!pending && businessId && name.trim()) void change({ action: "put", id: editing?.id ?? crypto.randomUUID(), organizationId, businessId, parentId: parentId || null, name: name.trim(), kind, expectedRevision: editing?.revision ?? 0 }); }}><h2 className="font-display text-xl">{editing ? `Edit ${editing.name}` : "Add a Unit"}</h2><SelectInput label="Business that owns this Unit" required value={businessId} onChange={e => setBusinessId(e.target.value)} disabled={pending || Boolean(editing)} options={[{ value: "", label: "Choose a business" }, ...managed.map(b => ({ value: b.id, label: b.name }))]} /><TextInput label="Unit name" value={name} maxLength={160} required disabled={pending} onChange={e => setName(e.target.value)} /><SelectInput label="Kind" value={kind} onChange={e => setKind(e.target.value as Unit["kind"])} disabled={pending} options={["business", "location", "division", "franchise"].map(value => ({ value, label: value }))} /><SelectInput label="Parent Unit" value={parentId} onChange={e => setParentId(e.target.value)} disabled={pending} options={[{ value: "", label: "Organization root" }, ...(view?.units.filter(u => u.id !== editing?.id && u.status === "active" && managed.some(b => b.id === u.businessId)).map(u => ({ value: u.id, label: u.name })) ?? [])]} /><Button type="submit" loading={pending} disabled={pending || Boolean(command.current) || !businessId || !name.trim()}>{editing ? "Save Unit" : "Add Unit"}</Button></form> : <p className="text-sm text-gray-muted">Only an organization owner or administrator with current access to the business can change its Units.</p>}
  </main>;
}
