import { test, expect } from "@playwright/test";
test.skip(process.env.ASK456_UI_PROOF!=="1","Owned local UI fixture only");
for(const width of [1440,390])test(`Ask setup Try and request page at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000});
  const writes:string[]=[];
  page.on("request",request=>{if(request.method()!=="GET" && request.url().includes("/api/"))writes.push(request.url());});
  await page.goto("/preview/strelva/ask-service-setup");
  await expect(page.getByRole("heading",{name:"Set up consultation requests"})).toBeVisible();
  const inquiry=page.locator('form[aria-label="Consultation"]');
  await inquiry.getByLabel("Name (required)").fill("Fixture visitor");
  await inquiry.getByLabel("Email (required)").fill("fixture@example.test");
  await inquiry.getByLabel("Message (required)").fill("Only a discarded local test");
  await inquiry.getByRole("button",{name:"Send a test inquiry"}).click();
  await expect(page.getByText("Test inquiry completed. Nobody was told and no real record was kept.")).toBeVisible();
  const booking=page.locator("form").last();
  await booking.getByLabel("Name",{exact:true}).fill("Fixture visitor");
  await booking.getByLabel("Email",{exact:true}).fill("fixture@example.test");
  await booking.getByRole("button",{name:"Try this time"}).click();
  await expect(page.getByText(/test.*(discard|complete|nothing|not)/i).last()).toBeVisible();
  expect(writes).toEqual([]);
  expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:`output/ask456/try-${width}.png`,fullPage:true});
  const cap="ask-service-4e0937bfa2bdc9d1c43a94a8fdec657d";
  const start=new Date(Date.now()+10*86400000);start.setUTCHours(14,0,0,0);
  const end=new Date(start.getTime()+30*60000);
  const paths:string[]=[];
  await page.route("**/api/v1/ask-service-bookings/**",async route=>{
    paths.push(new URL(route.request().url()).pathname);
    await route.fulfill({status:200,json:{schemaVersion:1,capabilityId:cap,version:1,name:"Consultation",provider:"google",bookingAuthority:"business",timeZone:"America/New_York",slots:[{id:"fixture-slot",start:start.toISOString(),end:end.toISOString()}]}});
  });
  await page.goto(`/book/ask456-fixture/${cap}`);
  await expect(page.getByText("Request a time. The business confirms your appointment.")).toBeVisible();
  await expect(page.getByRole("heading",{name:"Consultation"})).toBeVisible();
  await expect(page.getByText("Choose a time. The business confirms your booking; a connected calendar receives a copy.")).toBeVisible();
  await expect(page.getByText(/Calendar will confirm/)).toHaveCount(0);
  expect([...new Set(paths)]).toEqual(["/api/v1/ask-service-bookings/api/v1/bookings/ask456-fixture"]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:`output/ask456/book-${width}.png`,fullPage:true});
});
