import { createHash } from "node:crypto";
import { expect,test,type BrowserContext } from "@playwright/test";
import { z } from "zod";
import { googleProviderProofSchema } from "./support/google-provider-proof-scope";
import { assertGoogleNativeIsolation,inspectGoogleNativeIsolation,googleInspectionConnection } from "./support/google-native-inspection";
import { assertProviderReporter,requireProviderProofAdmission,parseProviderProofAdmission,loadProviderOwnerState,verifyProviderWorkspaceOwner,verifyProviderOwner,claimProviderDispatch } from "./support/provider-harness-admission";
test.use({trace:"off",screenshot:"off",video:"off",headless:false});test.describe.configure({retries:0});test.setTimeout(600_000);
const activationSchema=z.object({id:z.string(),businessId:z.string(),possibilityId:z.string(),candidateRevision:z.number(),status:z.string(),checks:z.array(z.object({status:z.string()}).passthrough()),steps:z.array(z.object({id:z.string(),kind:z.string(),target:z.string(),status:z.string(),effect:z.string().optional(),receipt:z.object({providerRef:z.string().optional()}).passthrough().optional(),compensation:z.object({status:z.string()}).passthrough().optional()}).passthrough())}).passthrough();
test("native Google complete approved job, unknown recovery, undo, mandate end, disconnect and signed reconnect",async({browser},info)=>{
 assertProviderReporter(info.config);const scope=requireProviderProofAdmission("google-make-real",googleProviderProofSchema);
 for(const [key,digest] of [["NEXT_PUBLIC_SUPABASE_URL",scope.supabaseUrlDigest],["UPSTASH_REDIS_REST_URL",scope.redisUrlDigest]] as const){const raw=process.env[key]||"";const url=new URL(raw);if(!["localhost","127.0.0.1"].includes(url.hostname)||createHash("sha256").update(raw).digest("hex")!==digest)throw new Error("Google proof held: exact owned test stores required before network inspection.");}
 googleInspectionConnection(scope,process.env.STRELVA_LOCAL_DB_URL||"");
 const owner=await browser.newContext({baseURL:scope.appOrigin,storageState:loadProviderOwnerState(scope.ownerAuthStatePath)}),agency=await browser.newContext({baseURL:scope.appOrigin,storageState:loadProviderOwnerState(scope.agencyAuthStatePath)});
 const claims:Array<ReturnType<typeof claimProviderDispatch>>=[];
 const command=async(context:BrowserContext,data:unknown)=>context.request.post("/api/workspace/publishing/google",{headers:{origin:scope.appOrigin},maxRetries:0,maxRedirects:0,data});
 const identity=async()=>{await verifyProviderWorkspaceOwner(owner,scope);parseProviderProofAdmission(googleProviderProofSchema,scope);const response=await command(owner,{action:"proof_identity",workspaceId:scope.workspaceId});expect(response.status()).toBe(200);expect(await response.json()).toEqual({databaseIdentityDigest:scope.nativeDatabaseIdentityDigest,supabaseUrlDigest:scope.supabaseUrlDigest,redisUrlDigest:scope.redisUrlDigest,redisNamespaceDigest:scope.redisNamespaceDigest,nativeOnly:true});};
 const dispatch=async(action:string,data:unknown)=>{await identity();const claim=claimProviderDispatch(scope,`${scope.plan.possibilityId}:${scope.plan.candidateRevision}:${action}`);claims.push(claim);return command(owner,data);};
 const read=async()=>{const response=await command(owner,{action:"read",plan:scope.plan});expect(response.status()).toBe(200);return z.object({candidateRevision:z.number(),planFingerprint:z.string(),grant:z.unknown(),state:z.object({receipt:z.object({id:z.string().uuid(),status:z.string(),readback:z.string().nullable(),undo:z.boolean()}).nullable()}).passthrough(),activation:activationSchema.optional()}).passthrough().parse(await response.json());};
 try{
  // Both actual loaded app/Auth identity and administrator inspection agree before any provider read/write.
  await identity();assertGoogleNativeIsolation(scope);
  await verifyProviderOwner(agency,{appOrigin:scope.appOrigin,ownerUserId:scope.agencyUserId,ownerEmail:scope.agencyEmail});
  const agencyScope={action:"agency_authority",workspaceId:scope.workspaceId,locationId:scope.plan.request.locationId};
  expect((await command(agency,agencyScope)).status()).toBe(200);
  const initialGrantResponse=await command(owner,{action:"read_grant",workspaceId:scope.workspaceId,bindingId:scope.plan.grant.bindingId});expect(initialGrantResponse.status()).toBe(200);const initialGrant=z.object({subjectDigest:z.string().regex(/^[a-f0-9]{64}$/)}).passthrough().parse(await initialGrantResponse.json());
  let current=await read();expect(current.candidateRevision).toBe(scope.plan.candidateRevision);expect(current.planFingerprint).toBe(scope.plan.planFingerprint);expect(current.grant).toEqual(scope.plan.grant);
  if(!current.activation){expect((await dispatch("make_real",{action:"make_real",plan:scope.plan})).status()).toBe(200);current=await read();}
  let activation=activationSchema.parse(current.activation);expect(activation).toMatchObject({businessId:scope.workspaceId,possibilityId:scope.plan.possibilityId,candidateRevision:scope.plan.candidateRevision});
  // An actual unknown step is mandatory. Never fabricate a timeout, receipt or manual reference.
  const unknown=activation.steps.find(step=>step.kind==="effect"&&step.target===scope.plan.effectId&&step.status==="unknown"&&step.effect==="unknown");expect(unknown).toBeTruthy();
  const recovered=await dispatch("recover",{action:"recover",plan:scope.plan,activationId:activation.id});expect(recovered.status()).toBe(200);
  const recovery=z.object({activation:activationSchema,providerRef:z.string()}).parse(await recovered.json());activation=recovery.activation;
  const accepted=activation.steps.find(step=>step.id===unknown!.id)!;expect(accepted.effect).toBe("accepted");expect(accepted.receipt?.providerRef).toBe(recovery.providerRef);
  const reference=z.object({businessId:z.string().uuid(),request:z.unknown(),receiptId:z.string().uuid()}).strict().parse(JSON.parse(recovery.providerRef));expect(reference.businessId).toBe(scope.workspaceId);expect(reference.request).toEqual(scope.plan.request);
  expect((await read()).state.receipt?.id).toBe(reference.receiptId);
  const resumed=await dispatch("resume",{action:"resume",plan:scope.plan,activationId:activation.id});expect(resumed.status()).toBe(200);activation=activationSchema.parse((await resumed.json()).activation);expect(activation.status).toBe("made_real");expect(activation.checks.every(check=>check.status==="passed")).toBe(true);expect(activation.steps.every(step=>step.status==="completed")).toBe(true);
  const readback=await command(owner,{action:"readback",plan:scope.plan,activationId:activation.id});expect(readback.status()).toBe(200);expect((await readback.json()).readback.ok).toBe(true);
  const undone=await dispatch("undo",{action:"undo",plan:scope.plan,activationId:activation.id});expect(undone.status()).toBe(200);
  activation=activationSchema.parse((await undone.json()).activation);
  if(activation.steps.some(step=>step.id===accepted.id&&step.compensation?.status==="unknown")){const recoveredUndo=await dispatch("recover_compensation",{action:"recover_compensation",plan:scope.plan,activationId:activation.id});expect(recoveredUndo.status()).toBe(200);activation=activationSchema.parse((await recoveredUndo.json()).activation);const finishUndo=await dispatch("finish_undo",{action:"undo",plan:scope.plan,activationId:activation.id});expect(finishUndo.status()).toBe(200);activation=activationSchema.parse((await finishUndo.json()).activation);}
  expect(activation.steps.find(step=>step.id===accepted.id)?.compensation?.status).toBe("compensated");
  expect(activation.status).toBe("rolled_back");expect(activation.steps.filter(step=>["stage","introduce","activate","connect"].includes(step.kind)).every(step=>step.status==="restored")).toBe(true);
  const ended=await dispatch("end_mandate",{action:"end_mandate",workspaceId:scope.workspaceId,locationId:scope.plan.request.locationId,mandateId:scope.mandateId});expect(ended.status()).toBe(200);expect(await ended.json()).toEqual({mandateId:scope.mandateId,status:"ended",ownerGrantRevoked:false});expect((await command(agency,agencyScope)).status()).toBe(403);
  // Owner's independent grant remains readable after agency authority ended.
  expect((await command(owner,{action:"read_grant",workspaceId:scope.workspaceId,bindingId:scope.plan.grant.bindingId})).status()).toBe(200);
  const disconnected=await dispatch("disconnect",{action:"disconnect",plan:scope.plan,commandId:scope.disconnectCommandId,confirmGrantRevocation:true});expect(disconnected.status()).toBe(200);expect(await disconnected.json()).toMatchObject({id:scope.disconnectCommandId,credentialsPurged:true,remoteRevoked:true});
  const durable=await command(owner,{action:"read_disconnect",workspaceId:scope.workspaceId,commandId:scope.disconnectCommandId});expect(durable.status()).toBe(200);expect(await durable.json()).toMatchObject({credentialsPurged:true,remoteRevoked:true});
  const grant=await command(owner,{action:"read_grant",workspaceId:scope.workspaceId,bindingId:scope.plan.grant.bindingId});expect(grant.status()).toBe(200);expect(await grant.json()).toMatchObject({status:"revoked",credentialsPurged:true});expect((await command(owner,{action:"read",plan:scope.plan})).status()).toBe(403);
  expect(inspectGoogleNativeIsolation(scope).expiredCaches).toBeGreaterThan(0);
  const purge=await dispatch("purge",{action:"purge_expired_cache",workspaceId:scope.workspaceId});expect(purge.status()).toBe(200);const purged=z.object({workspaceId:z.string(),purged:z.number().int().positive(),expiredRemaining:z.literal(0)}).parse(await purge.json());expect(purged.workspaceId).toBe(scope.workspaceId);expect(inspectGoogleNativeIsolation(scope).expiredCaches).toBe(0);
  await identity();if(Date.parse(scope.expiresAt)<Date.now()+600_000)throw new Error("Google proof held: approval window cannot cover signed consent.");claims.push(claimProviderDispatch(scope,`${scope.plan.possibilityId}:signed-native-reconnect`));
  const begin=await owner.request.post("/api/workspace/publishing/google/oauth",{headers:{origin:scope.appOrigin},maxRetries:0,maxRedirects:0,data:{workspaceId:scope.workspaceId,accountId:scope.plan.grant.accountId,locationId:scope.plan.request.locationId,googlePrincipalEmail:scope.googlePrincipalEmail}});expect(begin.status()).toBe(200);
  const consent=z.object({url:z.string().url()}).parse(await begin.json());const page=await owner.newPage();await page.goto(consent.url);
  // The named principal completes actual consent in this visible future browser.
  await page.waitForURL(url=>url.origin===scope.appOrigin&&url.pathname==="/api/workspace/publishing/google/oauth/callback",{timeout:300_000});
  const callback=await page.locator("body").innerText();expect(z.object({status:z.literal("connected"),bindingId:z.string(),accountId:z.string(),locationId:z.string(),googlePrincipalEmail:z.string().email(),subjectDigest:z.string()}).passthrough().parse(JSON.parse(callback))).toMatchObject({bindingId:scope.plan.grant.bindingId,accountId:scope.plan.grant.accountId,locationId:scope.plan.request.locationId,googlePrincipalEmail:scope.googlePrincipalEmail.toLowerCase(),subjectDigest:initialGrant.subjectDigest});
  const renewed=await command(owner,{action:"read_grant",workspaceId:scope.workspaceId,bindingId:scope.plan.grant.bindingId});expect(renewed.status()).toBe(200);const renewedGrant=z.object({status:z.literal("connected"),credentialsPurged:z.literal(false),subjectDigest:z.string(),grantGeneration:z.string().regex(/^[a-f0-9]{64}$/),locations:z.array(z.object({accountId:z.string(),locationId:z.string()}))}).passthrough().parse(await renewed.json());expect(renewedGrant.subjectDigest).toBe(initialGrant.subjectDigest);expect(renewedGrant.grantGeneration).not.toBe(scope.plan.grant.grantGeneration);expect(renewedGrant.locations).toContainEqual({accountId:scope.plan.grant.accountId,locationId:scope.plan.request.locationId});expect([403,409]).toContain((await command(owner,{action:"read",plan:scope.plan})).status());expect((await command(agency,agencyScope)).status()).toBe(403);
 }catch{throw new Error("Google native provider proof held/failed. Inspect private native receipts and dispatch journal; sensitive details withheld.");}
 finally{for(const claim of claims)claim.close();await owner.close();await agency.close();}
});
