import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { localEnvironment, signedInContext } from "./support/local-auth";

test.skip(process.env.STRELVA_LOCAL_AUTH_PROOF !== "1", "Requires a separately created, isolated local Supabase stack.");
test.setTimeout(120_000);

test("real local auth and Postgres preserve tracker edits and enforce another user and revoked membership", async ({ browser }) => {
  test.setTimeout(120_000);
  const env = localEnvironment();
  const admin = createClient(env.url, env.service, { auth: { persistSession: false, autoRefreshToken: false } });
  const owner = await signedInContext(browser, admin, "owner");
  const stranger = await signedInContext(browser, admin, "other");
  try {
    const adminRole = await admin.from("super_admins").insert({ user_id: owner.userId, email: owner.email });
    expect(adminRole.error).toBeNull();
    const agencyResponse = await owner.context.request.post("/api/workspace", { data: { action: "create_agency", name: "Local verification team" }, headers: { origin: env.app } });
    expect(agencyResponse.status()).toBe(201);
    const { workspaceId } = await agencyResponse.json();
    const page = await owner.context.newPage();
    await page.goto(`/workspace?workspaceId=${workspaceId}&view=tracker`);
    await expect(page.getByLabel("Choose a CSV file")).toBeVisible();
    await page.getByLabel("Choose a CSV file").setInputFiles({ name: "local-auth-requests.csv", mimeType: "text/csv", buffer: Buffer.from("Request,Status\nFirst inquiry,Waiting\nSecond inquiry,Assigned") });
    await expect(page.getByRole("heading", { name: "Preview imported rows" })).toBeVisible();
    const createdResponse = page.waitForResponse((response) => response.url().endsWith("/api/tracker") && response.request().method() === "POST" && response.request().postDataJSON().action === "create");
    await page.getByRole("button", { name: "Create tracker", exact: true }).click();
    const created = await (await createdResponse).json();
    expect(created.workId).toBeTruthy();
    await expect(page.locator("#tracker-rows")).toContainText("First inquiry");
    const firstReload = page.waitForResponse((response) => response.url().includes(`/api/tracker?workId=${created.workId}`) && response.request().method() === "GET");
    await page.reload();
    expect((await firstReload).status()).toBe(200);
    await expect(page.locator("#tracker-rows")).toContainText("First inquiry");
    await page.getByRole("button", { name: "Edit Status, source row 2", exact: true }).click();
    await page.getByLabel("New cell value").fill("Handled locally");
    await page.getByRole("button", { name: "Save edit", exact: true }).click();
    await expect(page.getByRole("list", { name: "Tracker edit history" })).toContainText("Handled locally");
    const editedReload = page.waitForResponse((response) => response.url().includes(`/api/tracker?workId=${created.workId}`) && response.request().method() === "GET");
    await page.reload();
    expect((await editedReload).status()).toBe(200);
    await expect(page.locator("#tracker-rows")).toContainText("Handled locally");
    const otherRead = await stranger.context.request.get(`/api/tracker?workId=${created.workId}`);
    expect(otherRead.status()).toBe(403);
    expect(await otherRead.text()).not.toContain("First inquiry");
    const staleEdit = await owner.context.request.post("/api/tracker", { data: { action: "command", workId: created.workId, command: { kind: "update_cell", commandId: randomUUID(), baseRevision: 0, rowId: created.tracker.rows[0].id, columnId: created.tracker.columns[1].id, value: "Stale overwrite" } }, headers: { origin: env.app } });
    expect(staleEdit.status()).toBe(409);
    await page.getByText("Internal R&D: record an experiment", { exact: true }).click();
    await page.getByLabel("What are we testing?").fill("Synthetic local persistence check");
    await page.getByLabel("Workload and comparison method").fill("Two synthetic rows; these numbers test recording, not customer savings.");
    await page.getByLabel("Previous approach, minutes").fill("10");
    await page.getByLabel("Setup, minutes", { exact: true }).fill("2");
    await page.getByLabel("Review, minutes", { exact: true }).fill("3");
    await page.getByLabel("Corrections, minutes", { exact: true }).fill("1");
    await page.getByLabel("Checks, evidence and failures").fill("Local Auth and Postgres accepted the saved tracker revision; cost is unknown.");
    const experimentResponse = page.waitForResponse((response) => response.url().endsWith("/api/tracker") && response.request().method() === "POST" && response.request().postDataJSON().action === "experiment");
    await page.getByRole("button", { name: "Record experiment", exact: true }).click();
    const experiment = await (await experimentResponse).json();
    expect(experiment.experimentWorkId).toBeTruthy();
    expect(experiment.evidence.targetRevision).toBe(1);
    expect(experiment.evidence.providerCostUsd).toBeNull();
    expect(experiment.evidence.promoted).toBe(false);
    await page.goto(`/workspace?workspaceId=${workspaceId}&work=${experiment.experimentWorkId}`);
    await expect(page.getByRole("heading", { name: "Comparison method" })).toBeVisible();
    await expect(page.getByText("Not recorded", { exact: true })).toBeVisible();
    const returnToTracker = page.waitForResponse((response) => response.url().includes(`/api/tracker?workId=${created.workId}`) && response.request().method() === "GET");
    await page.getByRole("link", { name: "Open current tracker" }).click();
    expect((await returnToTracker).status()).toBe(200);
    await expect(page.locator("#tracker-rows")).toContainText("Handled locally");
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(async () => (await page.getByRole("main").boundingBox())?.width ?? 0).toBeGreaterThan(350);
    await page.screenshot({ path: "output/tracker-authenticated-local-mobile.png", fullPage: true });
    // A different shape exercises quoted text and typed columns through the real adapters.
    await page.goto(`/workspace?workspaceId=${workspaceId}&view=tracker`);
    await page.getByLabel("Choose a CSV file").setInputFiles({ name: "local-appointments.csv", mimeType: "text/csv", buffer: Buffer.from('Name,Date,Amount,Active,Notes\n"North, office",2026-09-15,125.50,true,"Bring keys\nand access code"\nSouth office,2026-09-16,90,false,Call first') });
    await expect(page.getByRole("heading", { name: "Preview imported rows" })).toBeVisible();
    const secondCreatedResponse = page.waitForResponse((response) => response.url().endsWith("/api/tracker") && response.request().method() === "POST" && response.request().postDataJSON().action === "create");
    await page.getByRole("button", { name: "Create tracker", exact: true }).click();
    const secondCreated = await (await secondCreatedResponse).json();
    expect(secondCreated.workId).not.toBe(created.workId);
    expect(secondCreated.tracker.rows).toHaveLength(2);
    await expect(page.locator("#tracker-rows")).toContainText("North, office");
    const secondReload = page.waitForResponse((response) => response.url().includes(`/api/tracker?workId=${secondCreated.workId}`) && response.request().method() === "GET");
    await page.reload();
    expect((await secondReload).status()).toBe(200);
    await expect(page.locator("#tracker-rows")).toContainText("Bring keys");
    const revoked = await admin.from("workspace_memberships").delete().eq("workspace_id", workspaceId).eq("user_id", owner.userId);
    expect(revoked.error).toBeNull();
    const revokedRead = await owner.context.request.get(`/api/tracker?workId=${created.workId}`);
    expect(revokedRead.status()).toBe(403);
    const persisted = await admin.from("saved_product_work").select("payload").eq("id", created.workId).single();
    expect(persisted.error).toBeNull();
    expect(persisted.data?.payload.tracker.revision).toBe(1);
    expect(JSON.stringify(persisted.data?.payload)).not.toContain("Stale overwrite");
  } finally {
    await owner.context.close();
    await stranger.context.close();
  }
});
