"use client";
import { useCallback, useEffect, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { SelectInput, TextArea } from "@/components/ui/TextInput";
import { packageDeclarationSchema, revisionQualificationSchema } from "@/platform/system-versions/declaration";
const schema = z.object({ workspaceId: z.string().uuid(), systemId: z.string().uuid(), source: z.object({ listingState: z.enum(["private", "clients", "listed"]) }).passthrough(), revision: z.object({ source: z.object({ revisionId: z.string().uuid(), number: z.number().int().positive() }).passthrough(), declaration: packageDeclarationSchema.optional(), qualification: revisionQualificationSchema.nullable().optional() }).passthrough().nullable(), canReview: z.boolean() }).passthrough();
function errorMessage(body: unknown) { return body && typeof body === "object" && "error" in body && typeof body.error === "string" ? body.error : "The package request could not be confirmed."; }
/** The source's visibility never grants authority over its installed Versions. */
export function SourcePackageControls({ request, workspaceId, systemId }: { request: typeof fetch; workspaceId: string; systemId: string }) {
 const [opened, setOpened] = useState(false), [view,setView]=useState<z.infer<typeof schema>|null>(null), [error,setError]=useState(""), [busy,setBusy]=useState(false), [note,setNote]=useState(""), [attempt,setAttempt]=useState(0);
 const load=useCallback(async(signal?:AbortSignal)=>{ const response=await request(`/api/workspace/packages?${new URLSearchParams({workspaceId,sourceSystemId:systemId})}`,{credentials:"same-origin",signal}); const body:unknown=await response.json().catch(()=>null); if(!response.ok)throw new Error(errorMessage(body)); const parsed=schema.parse(body);if(parsed.workspaceId!==workspaceId||parsed.systemId!==systemId)throw new Error("Package returned for another source.");if(!signal?.aborted)setView(parsed);},[request,workspaceId,systemId]);
 useEffect(()=>{if(!opened)return;const controller=new AbortController();void load(controller.signal).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:"The package could not be read.");});return()=>controller.abort();},[opened,load,attempt]);
 async function command(input:Record<string,unknown>){if(busy)return;setBusy(true);setError("");try{const response=await request("/api/workspace/packages",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId,...input})});const body:unknown=await response.json().catch(()=>null);if(!response.ok)throw new Error(errorMessage(body));await load();}catch(cause){setError(cause instanceof Error?cause.message:"The package request could not be confirmed.");}finally{setBusy(false);}}
 const revision=view?.revision, q=revision?.qualification;
 return <details className="my-4 text-sm" onToggle={event=>setOpened(event.currentTarget.open)}><summary className="cursor-pointer">Declaration, review and listing</summary><div className="mt-4 max-w-2xl space-y-4">
 {!view&&!error?<p role="status">Reading this source’s exact revision…</p>:null}{error?<><p role="alert" className="text-critical">{error}</p><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{setError("");setAttempt(v=>v+1);}}>Retry package</Button></>:null}
 {view?<><p className="text-gray-muted">Private keeps the source with your agency. Clients makes qualified revisions available to your delegated clients. Listed makes qualified revisions available to other businesses. Each business owns its accounts, records and release decisions.</p><SelectInput label="Who can find this source" value={view.source.listingState} disabled={busy} options={[{value:"private",label:"Private"},{value:"clients",label:"Clients"},{value:"listed",label:"Listed"}]} onChange={event=>void command({action:"listing",systemId,state:event.target.value})}/>
 {revision?<><p>Source revision {revision.source.number} · {q?.status==="qualified"?"Qualified":q?.humanReview.state==="rejected"?"Review rejected":"Qualification pending"}</p>{revision.declaration?<dl className="grid gap-3 sm:grid-cols-2">{Object.entries(revision.declaration).map(([key,values])=><div key={key}><dt className="text-xs text-gray-muted">{{recordsRead:"Reads records",recordsWritten:"Writes records",businessRecordFields:"Business information",outsideEffects:"Outside actions",bindingKinds:"Required accounts",dataLeavingBusiness:"Data leaving the business"}[key]}</dt><dd className="mt-1 break-words">{values.join(", ")||"None"}</dd></div>)}</dl>:<p className="text-warning">This historical revision has no declaration. Publish a supported native revision before sharing it as a qualified app.</p>}
 <Button size="sm" variant="secondary" disabled={busy} loading={busy} onClick={()=>void command({action:"qualify",revisionId:revision.source.revisionId})}>Run exact revision checks</Button>
 {q?<><ul className="space-y-2">{q.evidence.map(check=><li key={check.check}><span className={check.status==="failed"?"text-critical":"text-gray-muted"}>{check.check.replaceAll("_"," ")} · {check.status}</span><details><summary className="cursor-pointer text-xs">Evidence</summary><p className="mt-1 break-words text-xs">{check.note}</p></details></li>)}</ul><p className="text-gray-muted">Human review: {q.humanReview.state}. {q.humanReview.note}</p></>:null}
 {view.canReview&&q?.humanReview.state==="pending"?<><TextArea label="Review of this exact revision" value={note} rows={3} disabled={busy} onChange={event=>setNote(event.target.value)} /><div className="flex flex-wrap gap-3"><Button size="sm" disabled={busy||!note.trim()||q.evidence.some(check=>check.status!=="passed")} onClick={()=>void command({action:"review",revisionId:revision.source.revisionId,approve:true,note:note.trim()})}>Approve qualification</Button><Button size="sm" variant="secondary" disabled={busy||!note.trim()} onClick={()=>void command({action:"review",revisionId:revision.source.revisionId,approve:false,note:note.trim()})}>Reject qualification</Button></div></>:q?.status!=="qualified"?<p className="text-gray-muted">A configured reviewer must approve this exact revision before it can be listed or installed. A review standard and reviewer have to be designated first.</p>:null}</>:<p>No immutable revision has been published.</p>}</>:null}
 </div></details>;
}
