"use client";
import {formatMoney} from "@/platform/connect/money-format";
import {useEffect,useState,useRef} from "react";
import {Button} from "@/components/ui/Button";
import {Card} from "@/components/ui/Card";
import {paymentRequestSchema,type PaymentRequest} from "@/platform/connect/contracts";
export default function BusinessPayment({token,initialRequest}:{token:string;initialRequest?:PaymentRequest}) {
 const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const [request,setRequest]=useState<PaymentRequest|null>(initialRequest??null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(!initialRequest);
 useEffect(()=>{if(initialRequest)return;const controller=new AbortController();fetch(`/api/v1/payments?token=${encodeURIComponent(token)}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error("This payment link is unavailable. Ask the business for a current link.");setRequest(paymentRequestSchema.parse(await r.json()));}).catch(()=>{if(!controller.signal.aborted)setError("Payment details could not be loaded. Ask the business for a current link.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,initialRequest]);
 async function pay(){setBusy(true);setError(null);try{const response=await fetch("/api/v1/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});const result=await response.json().catch(()=>({}));if(!active.current)return;if(!response.ok)throw Error(result.error??"Payment could not be started.");if(result.status==="paid"){setRequest(r=>r?{...r,paid:true,status:"paid"}:r);return;}if(typeof result.url!=="string")throw Error("Payment could not be started. Try again.");const url=new URL(result.url);if(url.protocol!=="https:"||url.hostname!=="checkout.stripe.com")throw Error("The payment provider returned an invalid link.");window.location.assign(url.toString());}catch(e){setError(e instanceof Error?e.message:"Payment could not be started.");}finally{setBusy(false);}}
 return <main className="mx-auto max-w-xl px-6 py-12 text-warm-black"><h1 className="font-display text-2xl font-medium">{request?.kind==="deposit"?"Your booking deposit":"Your quote"}</h1>{loading?<p role="status" className="mt-6">Loading payment details…</p>:null}{error?<p role="alert" className="mt-6">{error}</p>:null}{request?<Card className="mt-8" padding="md"><ul className="space-y-4">{request.lines.map((line,i)=><li key={i} className="flex justify-between gap-4"><span>{line.name} × {line.quantity}</span><span className="tabular-nums">{formatMoney(line.quantity*line.unitCents,request.currency)}</span></li>)}</ul>{request.acceptedTerms?<p className="mt-6 whitespace-pre-wrap">{request.acceptedTerms}</p>:null}<p className="mt-6 text-2xl font-medium tabular-nums">{formatMoney(request.amountCents,request.currency)}</p><p className="mt-4">{request.status==="paid"?"Payment received.":request.status==="expired"?"This payment link has expired.":request.status==="cancelled"?"This request was cancelled.":`Valid until ${new Date(request.expiresAt).toLocaleString()}.`}</p>{request.status==="unpaid"?<Button size="lg" className="mt-6" disabled={busy} onClick={pay}>{busy?"Opening secure payment…":"Accept and pay"}</Button>:null}<p className="mt-6 text-sm text-gray-muted">Payment goes to the business through Stripe. The business handles refunds and cancellation terms.</p></Card>:null}</main>;
}
