import { describe, it, expect, vi, afterEach } from "vitest";
import type { SendEmailInput } from "@/platform/infra/email/send";
import { bookingCalendarHealthPorts, chaseBookingCalendarHealth, type BookingCalendarHealthPorts, type BookingCalendarHealthSnapshot } from "@/platform/bookings/calendar-health";
const flags = vi.hoisted(() => ({ release: true, write: true, busy: true, notice: true, source: "postgres" }));
vi.mock("@/platform/bookings/flags", () => ({ bookingCalendarBusyEnabled: () => flags.busy, bookingOwnerNoticeEnabled: () => flags.notice, bookingStoreWriteEnabled: () => flags.write, bookingReadSource: vi.fn(async () => flags.source) }));
vi.mock("@/platform/needs-you/release", () => ({ needsYouReleaseEnabled: () => flags.release }));
const WS = "cf000000-0000-4000-8000-000000000001";
const action = { id: "cf000000-0000-4000-8000-000000000002", revision: "safe-hash", provider: "google" as const, status: "error" as const, delivery: "not_sent" as const };
function setup() {
  const snapshot: BookingCalendarHealthSnapshot = { businessName: "Calendar Fixture", timezone: "America/New_York", actions: [action] };
  const ports = { enabled: vi.fn(async () => true), sync: vi.fn(async () => snapshot), recipient: vi.fn(async () => ({ email: "owner@example.test", name: null, from: "record" as const, source: null, verified: true, tenantId: "fixture-site" })), claim: vi.fn(async () => true), finish: vi.fn(async () => {}) } satisfies BookingCalendarHealthPorts;
  const sendEmail = vi.fn(async (_input: SendEmailInput) => ({ status: "accepted" as const, providerMessageId: "fixture-mail", acceptedAt: "2026-10-07T11:00:00Z" }));
  const input = { now: Date.parse("2026-10-07T11:00:00Z"), appOrigin: "https://app.example.test", sendEmail };
  return { snapshot, ports, sendEmail, input };
}
afterEach(() => { Object.assign(flags, { release: true, write: true, busy: true, notice: true, source: "postgres" }); });
describe("booking calendar owner health", () => {
  it.each(["release", "write", "busy", "notice"] as const)("requires %s flag", async key => { flags[key] = false; expect(await bookingCalendarHealthPorts.enabled()).toBe(false); });
  it.each(["legacy", "compare"])("requires actual store-serving, not %s", async source => { flags.source = source; expect(await bookingCalendarHealthPorts.enabled()).toBe(false); });
  it("flags off do no source read, claim, or send", async () => { const t=setup(); t.ports.enabled.mockResolvedValue(false); expect(await chaseBookingCalendarHealth(WS,t.input,t.ports)).toEqual({ digests:0,ownerNotTold:0,failed:0,complete:true }); expect(t.ports.sync).not.toHaveBeenCalled(); expect(t.sendEmail).not.toHaveBeenCalled(); });
  it("healthy connection sends no notice", async () => { const t=setup(); t.snapshot.actions=[]; await chaseBookingCalendarHealth(WS,t.input,t.ports); expect(t.ports.recipient).not.toHaveBeenCalled(); expect(t.sendEmail).not.toHaveBeenCalled(); });
  it("only morning local sends, but recovery still reads each chase", async () => { const t=setup(); t.input.now+=3600000; await chaseBookingCalendarHealth(WS,t.input,t.ports); expect(t.ports.sync).toHaveBeenCalledWith(WS); expect(t.ports.claim).not.toHaveBeenCalled(); });
  it("uses owner-recipient and existing template, with sign-in open only", async () => { const t=setup(); const result=await chaseBookingCalendarHealth(WS,t.input,t.ports); expect(result.digests).toBe(1); expect(t.ports.claim).toHaveBeenCalledWith(WS,action.id,action.revision,"2026-10-07"); const sent=t.sendEmail.mock.calls[0]![0]; expect(sent.audience).toBe("client"); expect(sent.to).toBe("owner@example.test"); expect(sent.tenantId).toBe("fixture-site"); expect(sent.options?.button?.url).toBe(`https://app.example.test/workspace/bookings?workspaceId=${WS}`); expect(sent.options?.paragraphs?.join(" ")).toContain("Sign in"); expect(sent.options?.decisions).toBeUndefined(); expect(JSON.stringify(sent)).not.toMatch(/approve|token|one-tap/); expect(t.ports.finish).toHaveBeenCalledWith(WS,action.id,"sent","fixture-mail",null); });
  it("source database failure is incomplete, never claims, sends or clears actions", async () => { const t=setup(); t.ports.sync.mockRejectedValue(new Error("db down")); expect(await chaseBookingCalendarHealth(WS,t.input,t.ports)).toMatchObject({complete:false,failed:1}); expect(t.ports.claim).not.toHaveBeenCalled(); expect(t.ports.finish).not.toHaveBeenCalled(); expect(t.sendEmail).not.toHaveBeenCalled(); });
  it("changed source or another worker's claim never sends", async () => { const t=setup(); t.ports.claim.mockResolvedValue(false); await chaseBookingCalendarHealth(WS,t.input,t.ports); expect(t.sendEmail).not.toHaveBeenCalled(); });
  it.each(["claimed", "sent"] as const)("does not replay %s", async delivery => { const t=setup(); t.snapshot.actions=[{...action,delivery}]; await chaseBookingCalendarHealth(WS,t.input,t.ports); expect(t.ports.claim).not.toHaveBeenCalled(); expect(t.sendEmail).not.toHaveBeenCalled(); });
  it("lost accepted delivery receipt remains incomplete without second provider attempt", async () => { const t=setup(); t.ports.finish.mockRejectedValue(new Error("receipt failed")); expect(await chaseBookingCalendarHealth(WS,t.input,t.ports)).toMatchObject({digests:1,complete:false,failed:1}); expect(t.sendEmail).toHaveBeenCalledTimes(1); expect(t.ports.finish).toHaveBeenCalledTimes(1); });
  it("provider rejection records failed without raw sensitive error", async () => { const t=setup(); t.sendEmail.mockRejectedValue(new Error("PRIVATE PROVIDER ERROR")); expect(await chaseBookingCalendarHealth(WS,t.input,t.ports)).toMatchObject({failed:1}); expect(t.ports.finish).toHaveBeenCalledWith(WS,action.id,"failed",null,"send_failed"); });
  it("email gates remain owner-not-told instead of fake delivery", async () => { const t=setup(); const sendEmail=vi.fn(async () => ({status:"suppressed" as const,reason:"email_gates"})); expect(await chaseBookingCalendarHealth(WS,{...t.input,sendEmail},t.ports)).toMatchObject({ownerNotTold:1,digests:0}); expect(t.ports.finish).toHaveBeenCalledWith(WS,action.id,"suppressed",null,"email_gates"); });
  it("missing owner-recipient retains suppressed action", async () => { const t=setup(); const recipient=vi.fn(async () => null); expect(await chaseBookingCalendarHealth(WS,t.input,{...t.ports,recipient})).toMatchObject({ownerNotTold:1}); expect(t.sendEmail).not.toHaveBeenCalled(); expect(t.ports.finish).toHaveBeenCalledWith(WS,action.id,"suppressed",null,"no_owner_recipient"); });
});
