import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ override: vi.fn(async () => "inherit") }));
vi.mock("@/platform/infra/email/client-override", () => ({ getClientEmailOverride: mocks.override }));
import { bookingCustomerEmailAllowed, deliverBookingUpdates, type BookingUpdatePorts } from "@/platform/bookings/updates";
import { newBookingAccess } from "@/platform/bookings/native";

const booking = { id: "b1", calendarKey: "c1", tenantStableId: "c1", tenantId: "mooney", workspaceId: "ws1", systemId: null,
 status: "confirmed", origin: "site", serviceRef: "svc", businessServiceId: null, serviceName: "Consultation", start: "2026-11-03T15:00:00Z", end: "2026-11-03T15:30:00Z", bufferMinutes: 15, timeZone: "America/New_York", localDate: "2026-11-03", localStart: "10:00", localEnd: "10:30", customer: { name: "Dana", email: "dana@example.test" }, contactId: null, intakeAnswers: {}, inquiryId: null, legacyId: "bk1", publicReservationId: null, externalSource: null, externalRef: null, recordedVia: "native", createdAt: "2026-10-07T10:00:00Z", cancelledAt: null };
function fixture(audience: "customer" | "client" = "customer", status = "confirmed") {
 const access = newBookingAccess("Fixture assistant");
 const deps: BookingUpdatePorts = { claim: vi.fn(async () => [{ messageId: "m1", audience, booking: { ...booking, status }, access: { manage_ciphertext: access.manageCiphertext, confirm_ciphertext: access.confirmCiphertext } }]),
 finish: vi.fn(async () => undefined), business: vi.fn(async () => ({ name: "Fixture Firm", address: "1 Example St", ownerEmail: "owner@example.test", tenantId: "mooney", siteUrl: null })), customerAllowed: vi.fn(async () => true), send: vi.fn(async () => ({ status: "accepted" as const, providerMessageId: "email1", acceptedAt: "now" })) };
 return deps;
}
beforeEach(() => { vi.stubEnv("SECRETS_ENC_KEY", "11".repeat(32)); vi.stubEnv("STRELVA_BOOKING_STORE_WRITE", "1"); vi.stubEnv("STRELVA_BOOKING_MESSAGES", "1"); vi.stubEnv("STRELVA_BOOKING_MANAGE_PAGE", "1"); mocks.override.mockResolvedValue("inherit"); });
afterEach(() => vi.unstubAllEnvs());
describe("booking messages", () => {
 it("does no I/O with messages off or the store killed", async () => { const deps = fixture(); vi.stubEnv("STRELVA_BOOKING_MESSAGES", "0"); expect((await deliverBookingUpdates(null,deps)).sent).toBe(0); expect(deps.claim).not.toHaveBeenCalled(); vi.stubEnv("STRELVA_BOOKING_MESSAGES","1"); vi.stubEnv("DUAL_WRITE_PG","0"); await deliverBookingUpdates(null,deps); expect(deps.claim).not.toHaveBeenCalled(); });
 it.each(["customer","client"] as const)("suppresses %s messages at the booking email gates", async audience => { const deps=fixture(audience); vi.mocked(deps.customerAllowed).mockResolvedValue(false); expect((await deliverBookingUpdates("b1",deps)).suppressed).toBe(1); expect(deps.send).not.toHaveBeenCalled(); expect(deps.finish).toHaveBeenCalledWith("m1","suppressed",null,"email_gates"); });
 it("sends confirmation with a valid calendar file, business address and manage link", async () => { const deps=fixture(); expect((await deliverBookingUpdates("b1",deps)).customerSent).toBe(1); const input=vi.mocked(deps.send).mock.calls[0]![0]; expect(input).toMatchObject({ audience:"customer", tenantId:"mooney", fromAddress:"bookings@mail.strelva.com", options:{ heading:"Booking confirmed", button:{ label:"Change or cancel" } } }); const ics=Buffer.from(input.attachments![0]!.content,"base64").toString(); expect(ics).toContain("DTSTART:20261103T150000Z\r\n"); expect(ics).toContain("LOCATION:1 Example St"); expect(deps.finish).toHaveBeenCalledWith("m1","sent","email1",null); });
 it("emails only the confirm token for an agent hold and never claims it is booked", async () => { const deps=fixture("customer","held"); await deliverBookingUpdates("b1",deps); const input=vi.mocked(deps.send).mock.calls[0]![0]; expect(input.options).toMatchObject({ heading:"Confirm your booking request", button:{ label:"Review and confirm" } }); expect(input.options?.paragraphs?.[0]).toContain("Nothing is booked until you confirm"); expect(input.attachments).toBeUndefined(); });
 it("sends the owner a workspace notice without a customer bearer link", async () => { const deps=fixture("client"); await deliverBookingUpdates("b1",deps); const input=vi.mocked(deps.send).mock.calls[0]![0]; expect(input.options).toMatchObject({ heading:"New booking", button:{ label:"Open bookings", url:expect.stringContaining("/workspace/bookings?") } }); expect(input.options?.button?.url).not.toContain("/b/"); expect(input.attachments).toBeUndefined(); });
 it("passes the owner and agent flags into the atomic send claim", async () => { const deps=fixture(); vi.stubEnv("STRELVA_BOOKING_OWNER_NOTICE","0"); vi.stubEnv("STRELVA_BOOKING_AGENTS","0"); await deliverBookingUpdates("b1",deps); expect(deps.claim).toHaveBeenCalledWith("b1",false,false); vi.stubEnv("STRELVA_BOOKING_OWNER_NOTICE","1"); vi.stubEnv("STRELVA_BOOKING_AGENTS","1"); await deliverBookingUpdates("b1",deps); expect(deps.claim).toHaveBeenLastCalledWith("b1",true,true); });
 it("records an uncertain provider attempt as failed", async () => { const deps=fixture(); vi.mocked(deps.send).mockRejectedValue(new Error("lost response")); expect((await deliverBookingUpdates("b1",deps)).failed).toBe(1); expect(deps.send).toHaveBeenCalledOnce(); expect(deps.finish).toHaveBeenCalledWith("m1","failed",null,"send_or_business_read_failed"); });
 it("requires both global switches and respects the tenant kill switch", async () => { vi.stubEnv("EMAIL_SENDING_ENABLED","false"); vi.stubEnv("CUSTOMER_EMAIL_ENABLED","true"); mocks.override.mockResolvedValue("on"); expect(await bookingCustomerEmailAllowed("mooney")).toBe(false); vi.stubEnv("EMAIL_SENDING_ENABLED","true"); vi.stubEnv("CUSTOMER_EMAIL_ENABLED","false"); expect(await bookingCustomerEmailAllowed("mooney")).toBe(false); vi.stubEnv("CUSTOMER_EMAIL_ENABLED","true"); mocks.override.mockResolvedValue("off"); expect(await bookingCustomerEmailAllowed("mooney")).toBe(false); mocks.override.mockResolvedValue("inherit"); expect(await bookingCustomerEmailAllowed("mooney")).toBe(true); expect(await bookingCustomerEmailAllowed(null)).toBe(false); });
});
