// @vitest-environment jsdom
import { act, createElement } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";
import { StrelvaBookingForm } from "../../custom-repo-starter/StrelvaBookingForm";
import { mountPublishedCapabilities } from "../../custom-repo-starter/website-generation/capability-runtime.mjs";
import { isPublicBookingSchedule, sameBookingRequest } from "../../custom-repo-starter/booking-client";
const intake=[{id:"goal",label:"What would you like help with?",required:true,type:"textarea" as const},{id:"company",label:"Company",required:false,type:"text" as const}];
const schedule={schemaVersion:1 as const,capabilityId:"consultation",version:1,name:"Consultation",provider:"google" as const,timeZone:"America/New_York",slots:[{id:"slot-12345678",start:"2026-11-01T15:00:00Z",end:"2026-11-01T15:30:00Z"}],intake};
const receipt={schemaVersion:1 as const,reservationId:"reservation-12345678",managementToken:"management-12345678",capabilityId:schedule.capabilityId,version:1,provider:"google" as const,status:"pending" as const,title:schedule.name,start:schedule.slots[0]!.start,end:schedule.slots[0]!.end,timeZone:schedule.timeZone};
function setValue(element:HTMLInputElement|HTMLTextAreaElement,value:string){Object.getOwnPropertyDescriptor(element instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype,"value")?.set?.call(element,value);element.dispatchEvent(new Event("input",{bubbles:true}));element.dispatchEvent(new Event("change",{bubbles:true}));}
afterEach(()=>{document.body.replaceChildren();vi.unstubAllGlobals();});
describe("current service intake on public booking forms",()=>{
 it("safe schedule accepts bounded questions and rejects unknown or duplicate shapes",()=>{expect(isPublicBookingSchedule(schedule)).toBe(true);expect(isPublicBookingSchedule({...schedule,intake:[...intake,intake[0]]})).toBe(false);expect(isPublicBookingSchedule({...schedule,intake:[{...intake[0],privateId:"secret"}]})).toBe(false);});
 it("changing an answer changes the browser idempotency intent",()=>{const draft={requestId:"request-12345678",capabilityId:schedule.capabilityId,capabilityVersion:1,slotId:schedule.slots[0]!.id,visitor:{name:"Dana",email:"dana@example.test",intakeAnswers:{goal:"A"}}};expect(sameBookingRequest(draft,{slotId:draft.slotId,visitor:{...draft.visitor,intakeAnswers:{goal:"B"}}})).toBe(false);});
 it("React form renders labeled required questions, submits answers and preserves them on refusal",async()=>{vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT",true);const host=document.createElement("div");document.body.append(host);const root=createRoot(host);const reserve=vi.fn(async()=>{throw new Error("Nothing booked");});await act(async()=>root.render(createElement(StrelvaBookingForm,{schedule,onReserve:reserve})));const goal=host.querySelector<HTMLTextAreaElement>('textarea[id*="intake-goal"]')!;expect(goal.required).toBe(true);expect(host.querySelector(`label[for="${goal.id}"]`)?.textContent).toBe(intake[0]!.label);await act(async()=>{setValue(host.querySelector<HTMLInputElement>('input[name="name"]')!,"Dana");setValue(host.querySelector<HTMLInputElement>('input[name="email"]')!,"dana@example.test");setValue(goal,"Need advice");});await act(async()=>host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true})));expect(reserve).toHaveBeenCalledWith(schedule.slots[0],expect.objectContaining({intakeAnswers:{goal:"Need advice"}}));expect(goal.value).toBe("Need advice");expect(host.textContent).toContain("Nothing booked");await act(async()=>root.unmount());});
 it("exported runtime submits required answers and disables them while pending",async()=>{const host=document.createElement("div");host.dataset.strelvaCapability="booking";document.body.append(host);let resolveReserve:(value:Response)=>void=()=>{};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(schedule),{headers:{"Content-Type":"application/json"}})).mockImplementationOnce(()=>new Promise<Response>(resolve=>{resolveReserve=resolve;}));host.setAttribute("data-strelva-config",JSON.stringify({baseUrl:"https://app.example",tenant:"fixture",booking:{capabilityId:schedule.capabilityId,version:1,range:{from:"2026-11-01T00:00:00Z",to:"2026-11-02T00:00:00Z"}}}));vi.stubGlobal("fetch",fetcher);mountPublishedCapabilities(document);await act(async()=>{await Promise.resolve();await Promise.resolve();});const goal=host.querySelector<HTMLTextAreaElement>("#strelva-booking-intake-goal")!;expect(goal.required).toBe(true);host.querySelector<HTMLInputElement>("#strelva-booking-name")!.value="Dana";host.querySelector<HTMLInputElement>("#strelva-booking-email")!.value="dana@example.test";goal.value="Need advice";host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));expect(goal.disabled).toBe(true);const sent=JSON.parse(String(fetcher.mock.calls[1]?.[1]?.body));expect(sent.visitor.intakeAnswers).toEqual({goal:"Need advice",company:""});resolveReserve(new Response(JSON.stringify({receipt}),{headers:{"Content-Type":"application/json"}}));await act(async()=>{await Promise.resolve();await Promise.resolve();});expect(goal.disabled).toBe(false);});
});
