import { afterEach, describe, expect, it, vi } from "vitest";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { workspaceBookingScope, resolveBookingScope, bookingScopeFor } from "@/platform/bookings/booking-scope";
import { readWorkspaceBookings, changeWorkspaceBooking, setWorkspaceBookingHours, BookingRequestDecisionError, type BookingDependencies } from "@/products/bookings/server";
import { createManualBooking, manualBookingOptions, type ManualBookingPorts } from "@/platform/bookings/manual";
import { changeBookingSettings, readBookingSettings } from "@/platform/bookings/setup";
import { DEFAULT_BOOKING_CONFIG } from "@/lib/booking";
import { parseStoreBooking, type BookingContext } from "@/platform/bookings/store";
import { setReleaseFlagsDb } from "@/platform/release-flags/store";
import { WorkspaceBookings } from "@/experience/bookings/WorkspaceBookings";
vi.mock("next/navigation",()=>({useRouter:()=>({refresh:vi.fn()})}));
const WS="cf000000-0000-4000-8000-000000000050",OTHER="cf000000-0000-4000-8000-000000000051",SYSTEM="cf000000-0000-4000-8000-000000000052";
const actor={userId:"cf000000-0000-4000-8000-000000000053",verifiedEmail:"member@example.test"};
const context={tenantStableId:null,calendarKey:WS,workspaceId:WS,systemId:SYSTEM,paused:false,hours:{timezone:"UTC",weekly:[{day:1,opens:"09:00",closes:"17:00"}]},phone:null,services:[{id:SYSTEM,name:"Consultation",durationMinutes:30,active:true,externalRef:null}],settings:null} as BookingContext;
const booking=parseStoreBooking({id:SYSTEM,calendarKey:WS,tenantStableId:null,workspaceId:WS,systemId:SYSTEM,status:"requested",origin:"owner",start:"2026-11-02T10:00:00Z",end:"2026-11-02T10:30:00Z",timeZone:"UTC",localDate:"2026-11-02",localStart:"10:00",localEnd:"10:30",customer:{name:"Dana",email:"dana@example.test"},serviceRef:SYSTEM,serviceName:"Consultation"})!;
function links(error:{message:string}|null=null){setReleaseFlagsDb({rpc:async()=>({data:[],error})});}
const evidence={calendarHealth:"not_connected" as const,truncated:false,bookings:[{booking,history:[],historyTruncated:false,calendar:null}]};
function dependencies(patch:Partial<BookingDependencies>={}):BookingDependencies{return {bookings:vi.fn(async()=>[]),config:vi.fn(async()=>{throw new Error("tenant config should not be read");}),siteName:vi.fn(async()=>{throw new Error("tenant should not exist");}),readSource:async()=>"postgres",context:vi.fn(async()=>context),evidence:vi.fn(async()=>evidence),...patch};}
const input={workspaceId:WS,serviceId:SYSTEM,start:booking.start,requestId:"request-without-website",customer:booking.customer};
function manualPorts():ManualBookingPorts{return {enabled:async()=>true,rpc:vi.fn(async name=>name==="read_workspace_manual_booking_context"?context:{status:"recorded",booking}),services:vi.fn(async()=>({timeZone:"UTC",paused:false,services:[{id:SYSTEM,name:"Consultation",mode:"request" as const,bufferMinutes:15,durationMinutes:30}]})),slots:vi.fn(async()=>({version:1,timeZone:"UTC",paused:false,slots:[{id:booking.start,start:booking.start,end:booking.end,calendarChecked:true}]})),bookings:vi.fn(async()=>[]),notify:vi.fn(async()=>{}),updates:vi.fn(async()=>({sent:0,customerSent:0,suppressed:0,failed:0}))};}
afterEach(()=>{setReleaseFlagsDb(null);vi.unstubAllEnvs();});
describe("Bookings belongs to a business without a website",()=>{
 it("uses explicit matching workspace scopes, never a made-up tenant",()=>{expect(resolveBookingScope(WS)).toBe(workspaceBookingScope(WS));expect(bookingScopeFor({tenantId:null,workspaceId:WS})).toBe(workspaceBookingScope(WS));expect(bookingScopeFor({tenantId:"legacy-site",workspaceId:WS})).toBe("legacy-site");expect(()=>resolveBookingScope(WS,workspaceBookingScope(OTHER))).toThrow("this business");});
 it("lists its real System after membership verification without site config reads",async()=>{links();const deps=dependencies();const result=await readWorkspaceBookings(actor,WS,{view:"day",date:"2026-11-02"},deps);expect(result).toMatchObject({native:true,sites:[{tenantId:workspaceBookingScope(WS),siteName:"Bookings",bookings:[{status:"requested"}]}]});expect(deps.config).not.toHaveBeenCalled();expect(deps.siteName).not.toHaveBeenCalled();expect(deps.bookings).not.toHaveBeenCalled();expect(deps.evidence).toHaveBeenCalledWith(actor,WS,workspaceBookingScope(WS),{from:"2026-11-02",to:"2026-11-02"});const html=renderToStaticMarkup(createElement(WorkspaceBookings,{workspaceId:WS,view:"week",state:{kind:"ready",bookings:result}}));expect(html).toContain("Bookings System");expect(html).not.toContain("No booking site");});
 it("kept native commitments project onto the linked site without a duplicate native card",async()=>{setReleaseFlagsDb({rpc:async()=>({data:[{tenantId:"first-site",tenantStableId:SYSTEM,linkedAt:"2026-10-01T00:00:00Z"}],error:null})});const result=await readWorkspaceBookings(actor,WS,{view:"day",date:"2026-11-02"},dependencies({config:async()=>DEFAULT_BOOKING_CONFIG,siteName:async()=>"First site"}));expect(result.sites).toHaveLength(1);expect(result.sites[0]?.bookings[0]?.id).toBe(booking.id);expect(result.sites[0]?.tenantId).toBe("first-site");const nativeUpdate=vi.fn(async()=>({...booking,status:"cancelled" as const}));await changeWorkspaceBooking(actor,{workspaceId:WS,tenantId:"first-site",bookingId:booking.id,status:"cancelled"},{linked:async()=>["first-site"],readSource:async()=>"postgres",nativeRead:async()=>[{...booking,status:"confirmed"}],nativeUpdate});expect(nativeUpdate).toHaveBeenCalledWith(actor,WS,"first-site",booking.id,"cancelled");});
 it("flags-off/no-System never creates or reads a native calendar",async()=>{links();const read=vi.fn(async()=>context);expect((await readWorkspaceBookings(actor,WS,{view:"day"},dependencies({readSource:async()=>"legacy",context:read}))).sites).toEqual([]);expect(read).not.toHaveBeenCalled();const result=await readWorkspaceBookings(actor,WS,{view:"day"},dependencies({context:async()=>({...context,systemId:null})}));expect(result.sites).toEqual([]);const html=renderToStaticMarkup(createElement(WorkspaceBookings,{workspaceId:WS,view:"day",state:{kind:"ready",bookings:result}}));expect(html).toContain("A website is optional");});
 it("foreign or unverified membership cannot read native records",async()=>{links({message:"workspace_access_denied"});const deps=dependencies();await expect(readWorkspaceBookings(actor,WS,{view:"day"},deps)).rejects.toThrow();expect(deps.context).not.toHaveBeenCalled();expect(deps.evidence).not.toHaveBeenCalled();});
 it("takes a request through the same actor-bound RPC with omitted tenant",async()=>{const p=manualPorts();expect(await manualBookingOptions(actor,{workspaceId:WS},SYSTEM,p)).toMatchObject({services:[{id:SYSTEM}]});expect(p.rpc).toHaveBeenCalledWith("read_workspace_manual_booking_context",expect.objectContaining({p_workspace_id:WS,p_tenant_id:workspaceBookingScope(WS),p_user_id:actor.userId,p_email:actor.verifiedEmail}));expect(await createManualBooking(actor,input,p)).toMatchObject({booking:{origin:"owner",status:"requested",tenantStableId:null}});expect(p.rpc).toHaveBeenLastCalledWith("create_workspace_manual_booking",expect.objectContaining({p_tenant_id:workspaceBookingScope(WS),p_booking:expect.not.objectContaining({status:"confirmed"})}));});
 it("optional and explicit native scope retries preserve the same immutable intent",async()=>{const p=manualPorts();await createManualBooking(actor,input,p);await createManualBooking(actor,{...input,tenantId:workspaceBookingScope(WS)},p);const writes=vi.mocked(p.rpc).mock.calls.filter(([name])=>name==="create_workspace_manual_booking");expect((writes[0]?.[1]?.p_booking as {requestFingerprint:string}).requestFingerprint).toBe((writes[1]?.[1]?.p_booking as {requestFingerprint:string}).requestFingerprint);});
 it("native manual requests fail closed on foreign scope, missingSystem or pause",async()=>{const p=manualPorts();await expect(createManualBooking(actor,{...input,tenantId:workspaceBookingScope(OTHER)},p)).rejects.toThrow();expect(p.rpc).not.toHaveBeenCalled();vi.mocked(p.rpc).mockResolvedValue({...context,systemId:null});await expect(createManualBooking(actor,input,p)).rejects.toMatchObject({code:"not_found"});vi.mocked(p.rpc).mockResolvedValue({...context,paused:true});await expect(createManualBooking(actor,input,p)).rejects.toMatchObject({code:"conflict"});expect(p.slots).not.toHaveBeenCalled();expect(p.notify).not.toHaveBeenCalled();});
 it("configures native booking rules through the existing owner setup revision gate",async()=>{const ports={enabled:async()=>true,rpc:vi.fn(async()=>({revision:1}))};await readBookingSettings(actor,WS,undefined,ports);await changeBookingSettings(actor,{workspaceId:WS,expectedRevision:0,mode:"request",bufferMinutes:15,minNoticeMinutes:240,maxAdvanceDays:60,maxPerDay:null,cancellationCutoffHours:24},ports);expect(ports.rpc).toHaveBeenCalledWith("configure_booking_setup",expect.objectContaining({p_tenant_id:workspaceBookingScope(WS),p_user_id:actor.userId}));});
 it("member list actions cannot confirm or decline a native request",async()=>{const nativeUpdate=vi.fn();await expect(changeWorkspaceBooking(actor,{workspaceId:WS,bookingId:booking.id,status:"confirmed"},{linked:async()=>[],readSource:async()=>"postgres",context:async()=>context,nativeRead:async()=>[booking],nativeUpdate})).rejects.toBeInstanceOf(BookingRequestDecisionError);expect(nativeUpdate).not.toHaveBeenCalled();});
 it("native cancellation stays in the scoped store and hours still require owner/admin",async()=>{const nativeUpdate=vi.fn(async()=>({...booking,status:"cancelled" as const}));expect(await changeWorkspaceBooking(actor,{workspaceId:WS,bookingId:booking.id,status:"cancelled"},{linked:async()=>[],readSource:async()=>"postgres",context:async()=>context,nativeRead:async()=>[{...booking,status:"confirmed"}],nativeUpdate})).toMatchObject({status:"cancelled"});expect(nativeUpdate).toHaveBeenCalledWith(actor,WS,workspaceBookingScope(WS),booking.id,"cancelled");const save=vi.fn();await expect(setWorkspaceBookingHours(actor,{workspaceId:WS,hours:null},{linked:async()=>[],readSource:async()=>"postgres",context:async()=>context,canManage:async()=>false,save})).rejects.toMatchObject({code:"forbidden"});expect(save).not.toHaveBeenCalled();});
});
