import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const forward=readFileSync("supabase/migrations/20261022171000_checkout_final_admission.sql","utf8"),inverse=readFileSync("supabase/migrations/rollback-20261022171000_checkout_final_admission.sql","utf8");
const body=forward.match(/as \$\$([\s\S]*?)\$\$;/)![1]!;
describe("Checkout final admission source contracts, not native proof",()=>{
 it("checks source-bound request/accepted rail and exact agency retail actor in native final transaction",()=>{for(const expression of ["channel='checkout'","r.kind<>p.purpose","r.amount_cents<>p.amount_cents","r.currency<>p.currency","payment_id=p.id and action='accepted'","p.idempotency_key<>'request:'||r.id::text","public.assert_agency_billing_mutation(p.reference_id::uuid,p_actor_id,p_verified_email,p_accepted_email,p_account,p_generation)","i->>'agency_workspace_id' is distinct from p.workspace_id::text","i->>'amount_cents'","i->>'currency'"])expect(body).toContain(expression);});
 it("puts live merchant generation/exit/payment/expiry/cancel clocks after all serialization locks",()=>{const final=body.indexOf("-- Every clock/state check");expect(final).toBeGreaterThan(body.lastIndexOf("for share"));for(const expression of ["c.generation is distinct from p_generation","public.workspace_exit_completed(p.workspace_id)","public.workspace_exit_completed((i->>'business_workspace_id')::uuid)","kind='paid'","r.expires_at<=clock_timestamp()","action='cancelled'","started<clock_timestamp()-interval '23 hours'"])expect(body.slice(final)).toContain(expression);});
 it("pins canonical body/owner/complete function ACL/properties on inverse with no history change",()=>{const hash=createHash("md5").update(body).digest("hex");for(const sql of [forward,inverse])for(const expression of [hash,"p.proowner<>migrator","p.proargnames is distinct from","p.pronargs<>6","p.proargdefaults is not null","a.is_grantable","a.grantor<>migrator"])expect(sql).toContain(expression);expect(inverse).not.toMatch(/(?:delete from|truncate|drop table|alter table) public\./i);expect(inverse.match(/drop function/g)).toHaveLength(1);});
});
