import {afterEach,beforeEach,expect,it,vi} from "vitest";
import type Stripe from "stripe";
import {ingestRevenueEvent} from "@/platform/connect/revenue";
const workspaceId="a2830000-0000-4000-8000-000000000010";
beforeEach(()=>vi.stubEnv("STRELVA_REVENUE_SPLITS","1"));afterEach(()=>vi.unstubAllEnvs());
function db(){return {rpc:vi.fn(async(name:string):Promise<{data:unknown;error:{message:string}|null}>=>({data:name==="resolve_billing_workspace"?{workspaceId}:name==="verify_invoice_split_source"?true:name==="resolve_invoice_business_line"?workspaceId:null,error:null}))};}
function event(type:string,object:unknown){return {id:"evt_Source",type,livemode:false,data:{object}} as unknown as Stripe.Event;}
const charge={id:"ch_Source",payment_intent:"pi_Source",customer:"cus_Payer",livemode:false,paid:true,captured:true,currency:"cad",amount:1000};
const invoice={id:"in_Source",status:"paid",amount_paid:1000,currency:"cad",customer:"cus_Payer",metadata:{workspaceId}};
const invoicePayment={invoice:"in_Source",amount_paid:1000,currency:"cad",status:"paid",livemode:false,payment:{charge:"ch_Source"}};
function provider(ch=charge,ip=invoicePayment){return {charges:{retrieve:vi.fn(async()=>ch)},invoicePayments:{list:()=>({async *[Symbol.asyncIterator](){yield ip;}})},invoices:{listLineItems:()=>({async *[Symbol.asyncIterator](){yield {id:"il_Source",amount:1000,discount_amounts:[],metadata:{},period:{start:100,end:200}};}})}} as unknown as Stripe;}
it("signed collection cannot settle a same-amount foreign PaymentIntent charge",async()=>{const database=db();const result=await ingestRevenueEvent(event("payment_intent.succeeded",{id:"pi_Source",latest_charge:"ch_Source",amount_received:1000,currency:"cad",customer:"cus_Payer",metadata:{platformCollectionId:workspaceId}}),{db:database,stripe:provider({...charge,payment_intent:"pi_Foreign"})});expect(result).toMatchObject({unreconciled:true,reason:"collection_charge_mismatch"});expect(database.rpc.mock.calls.some(c=>c[0]==="record_neutral_version_settlement")).toBe(false);});
it("foreign invoice payment is recorded for review before source fetch or accrual",async()=>{const database=db();const stripe=provider(charge,{...invoicePayment,invoice:"in_Foreign"});expect(await ingestRevenueEvent(event("invoice.paid",invoice),{db:database,stripe})).toMatchObject({unreconciled:true});expect(stripe.charges.retrieve).not.toHaveBeenCalled();expect(database.rpc.mock.calls.some(c=>c[0]==="accrue_invoice_splits")).toBe(false);});
it("same-amount foreign customer charge cannot create invoice splits",async()=>{const database=db();expect(await ingestRevenueEvent(event("invoice.paid",invoice),{db:database,stripe:provider({...charge,customer:"cus_Foreign"})})).toMatchObject({unreconciled:true,reason:"charge_does_not_cover_invoice"});expect(database.rpc.mock.calls.some(c=>c[0]==="accrue_invoice_splits")).toBe(false);});
it("owned source freezes exact payer before common immutable accrual",async()=>{const database=db();expect(await ingestRevenueEvent(event("invoice.paid",invoice),{db:database,stripe:provider()})).toEqual({processed:true});const names=database.rpc.mock.calls.map(c=>c[0]);expect(names.indexOf("record_invoice_split_source")).toBeLessThan(names.indexOf("accrue_invoice_splits"));expect(database.rpc).toHaveBeenCalledWith("record_invoice_split_source",expect.objectContaining({p_payer:workspaceId,p_business:workspaceId,p_customer:"cus_Payer",p_line:"il_Source",p_charge:"ch_Source",p_basis:1000,p_currency:"cad"}));});

it("agency wholesale freezes the agency payer separately from the business before SQL eligibility",async()=>{const agency="a2830000-0000-4000-8000-000000000020";const database=db();database.rpc.mockImplementation(async(name:string)=>({data:name==="resolve_billing_workspace"?{workspaceId:agency}:name==="verify_invoice_split_source"?true:name==="resolve_invoice_business_line"?workspaceId:null,error:null}));expect(await ingestRevenueEvent(event("invoice.paid",invoice),{db:database,stripe:provider()})).toEqual({processed:true});expect(database.rpc).toHaveBeenCalledWith("record_invoice_split_source",expect.objectContaining({p_payer:agency,p_business:workspaceId}));expect(database.rpc).toHaveBeenCalledWith("accrue_invoice_splits",expect.objectContaining({p_business_id:workspaceId}));});

it('persists accepted platform settlement before the additive creator observer and retries only ledger observation after failure',async()=>{
 const database=db(),seen:string[]=[];let accepted=false,fail=true;
 database.rpc.mockImplementation(async(name:string)=>{seen.push(name);if(name==='record_neutral_version_settlement')accepted=true;if(name==='observe_neutral_creator_settlement'&&fail){fail=false;return {data:null,error:{message:'Temporary observation failure'}};}return {data:null,error:null};});
 const stripe=provider(),settled=event('payment_intent.succeeded',{id:'pi_Source',latest_charge:'ch_Source',amount_received:1000,currency:'cad',customer:'cus_Payer',metadata:{platformCollectionId:workspaceId}});
 await expect(ingestRevenueEvent(settled,{db:database,stripe})).rejects.toThrow();expect(accepted).toBe(true);expect(seen).toEqual(['record_neutral_version_settlement','observe_neutral_creator_settlement']);
 expect(await ingestRevenueEvent(settled,{db:database,stripe})).toEqual({processed:true});expect(seen).toEqual(['record_neutral_version_settlement','observe_neutral_creator_settlement','record_neutral_version_settlement','observe_neutral_creator_settlement']);
 expect(stripe.charges.retrieve).toHaveBeenCalledTimes(2);
});
it('legacy accepted collection with no generic lineage still finishes through a null additive observation',async()=>{
 const database=db();expect(await ingestRevenueEvent(event('payment_intent.succeeded',{id:'pi_Source',latest_charge:'ch_Source',amount_received:1000,currency:'cad',customer:'cus_Payer',metadata:{platformCollectionId:workspaceId}}),{db:database,stripe:provider()})).toEqual({processed:true});
 expect(database.rpc.mock.calls.map(call=>call[0])).toEqual(['record_neutral_version_settlement','observe_neutral_creator_settlement']);
});
