import {beforeEach,afterEach,describe,it,expect,vi} from "vitest";
import type Stripe from "stripe";
import {createDirectCheckout,createDirectSubscription,ingestConnectEvent,onboardConnectedAccount} from "@/platform/connect";
import {planSplitPayouts,type PayoutCandidate} from "@/platform/connect/payouts";
import {requestAgentPayment} from "@/platform/connect/agent-payments";
const workspaceId="a2830000-0000-4000-8000-000000000010";const paymentId="a2830000-0000-4000-8000-000000000011";
const merchant={workspace_id:workspaceId,stripe_account_id:"acct_Merchant",configurations:["merchant"],profile_version:"approved-v1",state:"ready",generation:0,capabilities:{},requirements:{}};
function db(handler?:(name:string,args:Record<string,unknown>)=>unknown){return {rpc:vi.fn(async(name:string,args:Record<string,unknown>)=>({data:handler?handler(name,args):name==="read_connected_account"?merchant:name==="reserve_business_payment"?{id:paymentId}:null,error:null}))};}
function event(type:string,object:unknown,account="acct_Merchant"){return {id:"evt_Money",type,account,data:{object}} as unknown as Stripe.Event;}
beforeEach(()=>{vi.stubEnv("STRELVA_CONNECT","1");});afterEach(()=>vi.unstubAllEnvs());
describe("merchant direct charges",()=>{
 it("reserves and pins rail before charge; zero fee and account-specific idempotency",async()=>{const database=db();const create=vi.fn(async()=>({id:"cs_Money",url:"https://checkout.stripe.com/pay/test"}));const stripe={checkout:{sessions:{create}}} as unknown as Stripe;const result=await createDirectCheckout({workspaceId,idempotencyKey:"stable-key",purpose:"quote",amountCents:1000,currency:"usd",successUrl:"https://app.example/paid",cancelUrl:"https://app.example/cancel"},{db:database,stripe});expect(result.paymentId).toBe(paymentId);expect(create).toHaveBeenCalledWith(expect.objectContaining({payment_intent_data:{application_fee_amount:0,metadata:{businessPaymentId:paymentId}}}),{stripeAccount:"acct_Merchant",idempotencyKey:`payment:${paymentId}`});expect(database.rpc.mock.calls.map(c=>c[0])).toEqual(["read_connected_account","reserve_business_payment","claim_business_payment_channel","prepare_business_checkout","record_business_payment_event"]);});
 it("stops before provider write on unavailable ledger",async()=>{const database={rpc:vi.fn(async()=>({data:merchant,error:{message:"store_failure"}}))};const create=vi.fn();await expect(createDirectCheckout({workspaceId,idempotencyKey:"stable-key",purpose:"quote",amountCents:1000,currency:"usd",successUrl:"https://app.example/paid",cancelUrl:"https://app.example/cancel"},{db:database,stripe:{checkout:{sessions:{create}}} as unknown as Stripe})).rejects.toThrow();expect(create).not.toHaveBeenCalled();});
 it("rejects account mismatch by database instead of trusting payment metadata",async()=>{const database={rpc:vi.fn(async()=>({data:null,error:{message:"payment_account_mismatch"}}))};await expect(ingestConnectEvent(event("payment_intent.succeeded",{id:"pi_Test",amount_received:1000,metadata:{businessPaymentId:paymentId}},"acct_Other"),{db:database})).rejects.toThrow();expect(database.rpc).toHaveBeenCalledWith("read_business_payment_provider",expect.objectContaining({p_account:"acct_Other"}));});
 it("refund.created and refund.updated use the same refund identity",async()=>{const database=db();const refund={id:"re_First",amount:200,currency:"usd",payment_intent:"pi_Money",status:"succeeded",metadata:{businessPaymentId:paymentId}};await ingestConnectEvent(event("refund.created",refund),{db:database});await ingestConnectEvent(event("refund.updated",refund),{db:database});expect(database.rpc.mock.calls.every(c=>c[1].p_event_id==="refund:re_First")).toBe(true);});
 it("subscription remains connected merchant, incomplete and fee-free",async()=>{const create=vi.fn(async(_input:unknown,_options:unknown)=>({id:"sub_Test"}));await createDirectSubscription({workspaceId,idempotencyKey:"agency-key",customerId:"cus_Test",priceId:"price_Test",purpose:"agency_rebill"},{db:db(),stripe:{subscriptions:{create}} as unknown as Stripe});expect(create).toHaveBeenCalledWith(expect.objectContaining({payment_behavior:"default_incomplete"}),{stripeAccount:"acct_Merchant",idempotencyKey:"agency-key"});expect(create.mock.calls[0]![0]).not.toHaveProperty("application_fee_percent");});
 it("rejects onboarding before any DB/provider call when liability profile absent",async()=>{const database=db();await expect(onboardConnectedAccount({userId:paymentId,verifiedEmail:"owner@example.test"},{workspaceId,configurations:["merchant"],origin:"https://app.example"},{db:database,stripe:{} as Stripe})).rejects.toThrow(/liability/);expect(database.rpc).not.toHaveBeenCalled();});
});
const candidate:PayoutCandidate={split_id:"split_one",source_account_id:"platform",source_charge_id:"ch_First",currency:"cad",agreement_version:"signed-v1",recipient_account_id:"acct_Recipient",amount_cents:100,state:"ready",configurations:["recipient"],capabilities:{recipient:{capabilities:{stripe_balance:{stripe_transfers:{status:"active"}}}}}};
describe("dry-run payout bounds",()=>{
 it("cannot spend merchant direct-charge funds",async()=>{const settledCharge=vi.fn();const result=await planSplitPayouts([{...candidate,source_account_id:"acct_Business"}],{settledCharge});expect(result.mode).toBe("dry_run");expect(result.plans).toEqual([]);expect(result.skipped[0]!.reason).toMatch(/merchant/);expect(settledCharge).not.toHaveBeenCalled();});
 it("skips pending settlement/currency mismatch and bounds aggregate source use",async()=>{const reader={settledCharge:vi.fn(async()=>({settled:true,currency:"cad",availableCents:150}))};const result=await planSplitPayouts([candidate,{...candidate,split_id:"split_two"}],reader);expect(result.plans).toHaveLength(1);expect(result.skipped[0]!.reason).toBe("insufficient_source_balance");expect((await planSplitPayouts([candidate],{settledCharge:async()=>({settled:false,currency:"cad",availableCents:500})})).skipped[0]!.reason).toBe("source_not_settled");expect((await planSplitPayouts([candidate],{settledCharge:async()=>({settled:true,currency:"usd",availableCents:500})})).skipped[0]!.reason).toBe("currency_mismatch");});
 it("approved agent adapter cannot record success from another currency or merchant",async()=>{vi.stubEnv("STRELVA_AGENT_PAYMENTS","1");const database=db(name=>name==="read_connected_account"?merchant:name==="reserve_agent_payment_request"?{paymentId,amountCents:1000,currency:"usd",status:"unpaid"}:null);const provider={chargeWithSharedPaymentToken:vi.fn(async()=>({id:"pi_Agent",status:"succeeded" as const,amountReceived:1000,currency:"jpy",merchantAccountId:"acct_Merchant"}))};await expect(requestAgentPayment({workspaceId},{sharedPaymentToken:"spt_secret",paymentCapability:"f".repeat(64)},{db:database,provider,previewApproved:true})).rejects.toThrow(/does not match/);expect(database.rpc.mock.calls.some(c=>c[0]==="bind_business_payment_provider"||c[0]==="record_business_payment_event")).toBe(false);});
 it("agent preview cannot run by merely setting an environment flag",async()=>{vi.stubEnv("STRELVA_AGENT_PAYMENTS","1");const result=await requestAgentPayment({workspaceId},{sharedPaymentToken:"secret",paymentCapability:"f".repeat(64)});expect(result.status).toBe("unavailable");});
});

describe("prepared platform rail and durable readback",()=>{
 it("returns an existing checkout without creating another after provider key retention",async()=>{const retrieve=vi.fn(async()=>({id:"cs_Existing",url:"https://checkout.stripe.com/pay/existing"}));const create=vi.fn();const database=db((name)=>name==="read_connected_account"?merchant:name==="reserve_business_payment"?{id:paymentId}:name==="prepare_business_checkout"?{sessionId:"cs_Existing"}:null);const result=await createDirectCheckout({workspaceId,idempotencyKey:"stable-key",purpose:"quote",amountCents:1000,currency:"usd",successUrl:"https://app.example/paid",cancelUrl:"https://app.example/cancel"},{db:database,stripe:{checkout:{sessions:{retrieve,create}}} as unknown as Stripe});expect(result.sessionId).toBe("cs_Existing");expect(create).not.toHaveBeenCalled();expect(retrieve).toHaveBeenCalledWith("cs_Existing",{stripeAccount:"acct_Merchant"});});
 it("a payout execution flag alone never grants first-payment permission",async()=>{const {executeApprovedPayout}=await import("@/platform/connect/transfers");vi.stubEnv("STRELVA_SPLIT_PAYOUT_EXECUTION","1");const create=vi.fn();const database={rpc:vi.fn(async()=>({data:null,error:{message:"payout_operator_authorization_required"}}))};await expect(executeApprovedPayout(paymentId,{db:database,stripe:{transfers:{create}} as unknown as Stripe})).rejects.toThrow();expect(create).not.toHaveBeenCalled();});
 it("approved fake transfer spends only the platform source and maps exact reversal",async()=>{const {executeApprovedPayout,reverseApprovedPayout}=await import("@/platform/connect/transfers");vi.stubEnv("STRELVA_SPLIT_PAYOUT_EXECUTION","1");const create=vi.fn(async()=>({id:"tr_Payout",amount:100,currency:"cad",destination:"acct_Recipient",source_transaction:"ch_Source"}));const createReversal=vi.fn(async()=>({id:"trr_Reversal",amount:25,transfer:"tr_Payout"}));const database=db(name=>name==="prepare_approved_split_transfer"?{id:paymentId,recipient_account_id:"acct_Recipient",source_account_id:"platform",source_transaction:"ch_Source",amount_cents:100,currency:"cad"}:name==="read_source_transfer_ids"?[]:name==="prepare_split_transfer_reversal"?{id:"reversal-one",transfer_id:"tr_Payout",amount_cents:25}:null);const stripe={charges:{retrieve:async()=>({id:"ch_Source",paid:true,captured:true,livemode:false,amount:1000,amount_refunded:0,currency:"cad",disputed:false,balance_transaction:{id:"txn_Source",source:"ch_Source",amount:1000,fee:100,net:900,currency:"cad",status:"available"}})},disputes:{list:()=>({async *[Symbol.asyncIterator](){}})},refunds:{list:()=>({async *[Symbol.asyncIterator](){}})},transfers:{create,createReversal,list:()=>({async *[Symbol.asyncIterator](){}})}} as unknown as Stripe;await executeApprovedPayout(paymentId,{db:database,stripe});expect(create).toHaveBeenCalledWith({amount:100,currency:"cad",destination:"acct_Recipient",source_transaction:"ch_Source",metadata:{splitPayoutId:paymentId}},{idempotencyKey:`split-payout:${paymentId}`});await reverseApprovedPayout(paymentId,"loss-receipt",{db:database,stripe});expect(createReversal).toHaveBeenCalledWith("tr_Payout",{amount:25,metadata:{splitReversalId:"reversal-one"}},{idempotencyKey:"split-reversal:reversal-one"});});
 it("platform collection verifies frozen line before SDK and uses platform scope",async()=>{const {createPlatformCollection}=await import("@/platform/connect/platform-collection");vi.stubEnv("STRELVA_PLATFORM_COLLECTION","1");vi.stubEnv("STRELVA_CONNECT_PROFILE_VERSION","approved-v1");vi.stubEnv("STRELVA_CONNECT_FEES_COLLECTOR","stripe");vi.stubEnv("STRELVA_CONNECT_LOSSES_COLLECTOR","stripe");const create=vi.fn(async()=>({id:"pi_Platform"}));const database=db(()=>({id:paymentId}));await createPlatformCollection({workspaceId,invoiceLineId:"il_Approved",amountCents:1000,currency:"cad",customerId:"cus_Payer",idempotencyKey:"priced-line-key",agreementVersion:"approved-v1"},{db:database,stripe:{paymentIntents:{create}} as unknown as Stripe});expect(database.rpc.mock.calls[0]![0]).toBe("reserve_platform_collection");expect(create).toHaveBeenCalledWith(expect.objectContaining({amount:1000,currency:"cad",customer:"cus_Payer"}),{idempotencyKey:`platform-collection:${paymentId}`});});
});
describe("source settlement economics",()=>{it("subtracts actual Stripe fees, refunds and external transfers without double counting known ledger transfers",async()=>{const {readPlatformSettlement}=await import("@/platform/connect/settlement");const database=db(()=>["tr_Known"]);const stripe={charges:{retrieve:async()=>({id:"ch_Source",paid:true,captured:true,livemode:false,amount:1000,currency:"cad",amount_refunded:200,disputed:false,balance_transaction:{id:"txn_Source",source:"ch_Source",amount:1000,fee:50,net:950,currency:"cad",status:"available"}})},disputes:{list:()=>({async *[Symbol.asyncIterator](){}})},refunds:{list:()=>({async *[Symbol.asyncIterator](){yield {id:"re_Source",charge:"ch_Source",amount:200,currency:"cad",status:"succeeded",balance_transaction:{id:"txn_Refund",source:"re_Source",amount:-200,fee:0,net:-200,currency:"cad",status:"available"}};}})},transfers:{list:()=>({async *[Symbol.asyncIterator](){yield {id:"tr_Known",livemode:false,source_transaction:"ch_Source",currency:"cad",amount:300,amount_reversed:0};yield {id:"tr_Outside",livemode:false,source_transaction:"ch_Source",currency:"cad",amount:100,amount_reversed:25};}})}} as unknown as Stripe;expect(await readPlatformSettlement(stripe,database,"ch_Source")).toEqual({settled:true,currency:"cad",availableCents:675});});});
