import { describe, expect, it } from "vitest";
import { automatedRevisionQualification, effectivePackageBehavior, assertPackageDeclaration, isRevisionQualified } from "@/platform/system-versions/declaration";
import { rehearseApplicationPackage } from "@/products/applications/package-rehearsal";
import type { SourceRevision } from "@/platform/system-versions";
const definition = { kind: "internal_app", title: "Requests", fields: [{ id: "request", label: "Request", type: "text", required: true }], components: [{ kind: "form", fields: ["request"] }, { kind: "list", fields: ["request"] }] };
const revision: SourceRevision = { source: { businessId: "creator", systemId: "source", revisionId: "revision-one", number: 1 }, definition, declaration: effectivePackageBehavior(definition), requires: { bindingKinds: [] }, summary: "Requests", publishedBy: "creator", publishedAt: "2026-10-07T00:00:00.000Z" };
describe("Creator package exact-revision qualification", () => {
 it("executes native rehearsal with synthetic record submission and invalid-record rejection", () => { const receipt = rehearseApplicationPackage(revision.source.revisionId, definition); expect(receipt.checks.every(check => check.passed)).toBe(true); expect(receipt.checks.some(check => check.name.includes("submission"))).toBe(true); const q = automatedRevisionQualification(revision, undefined, receipt); expect(q.evidence.every(check => check.status === "passed")).toBe(true); expect(isRevisionQualified({ ...revision, qualification: q })).toBe(false); });
 it("refuses missing or another revision's native rehearsal and stale human approval", () => { expect(automatedRevisionQualification(revision).evidence.find(check => check.check === "rehearsal")?.status).toBe("failed"); const receipt = rehearseApplicationPackage("other-revision", definition); expect(automatedRevisionQualification(revision, undefined, receipt).evidence.find(check => check.check === "rehearsal")?.status).toBe("failed"); const q = automatedRevisionQualification(revision, undefined, rehearseApplicationPackage(revision.source.revisionId, definition)); const approved = { ...q, status: "qualified", humanReview: { state: "approved", reviewerId: "reviewer", reviewedAt: "2026-10-07", note: "Exact revision" } }; expect(isRevisionQualified({ ...revision, qualification: approved })).toBe(true); expect(isRevisionQualified({ ...revision, source: { ...revision.source, revisionId: "revision-two" }, qualification: approved })).toBe(false); });
 it("rejects unknown executable runtime and declarations that omit newly reachable business records", () => { expect(() => effectivePackageBehavior({ kind: "arbitrary", source: "sendEmail()" })).toThrow(); expect(() => assertPackageDeclaration({ ...definition, fields: [...definition.fields, { id: "contact", label: "Contact", type: "contact", required: false }] }, revision.declaration!)).toThrow("recordsRead"); });
 it("declares native notice emails without linked fields and refuses omissions", () => { const actual = effectivePackageBehavior(definition); expect(actual.outsideEffects).toEqual(["email"]); expect(actual.recordsWritten).toContain("internal_tool.notices"); expect(actual.businessRecordFields).toContain("owner_recipient.email"); expect(actual.dataLeavingBusiness).toHaveLength(1); expect(() => assertPackageDeclaration(definition, { ...actual, outsideEffects: [] })).toThrow("outsideEffects"); expect(() => assertPackageDeclaration(definition, { ...actual, dataLeavingBusiness: [] })).toThrow("dataLeavingBusiness"); const linked = effectivePackageBehavior({ ...definition, fields: [...definition.fields, { id: "contact", label: "Contact", type: "contact", required: false }] }); expect(linked.recordsWritten).toContain("business.contacts"); expect(linked.recordsWritten).toContain("business.record.history"); expect(linked.businessRecordFields).toContain("contacts.email"); });
 it("keeps source input and records isolated across rehearsals", () => { const before = JSON.stringify(definition); const one = rehearseApplicationPackage("one", definition), two = rehearseApplicationPackage("two", definition); expect(JSON.stringify(definition)).toBe(before); expect(one.revisionId).toBe("one"); expect(two.revisionId).toBe("two"); });
});
