import { describe, expect, it, vi } from "vitest";
import { readCreatorMaintenance, recordCreatorMaintenance } from "@/platform/connect/creator-maintenance";
import { WorkspaceAccessError, WorkspaceConflictError, WorkspaceStoreError } from "@/platform/workspaces/types";
const workspaceId="11111111-1111-4111-8111-111111111111", listingId="22222222-2222-4222-8222-222222222222", sourceRevisionId="33333333-3333-4333-8333-333333333333", userId="44444444-4444-4444-8444-444444444444", other="55555555-5555-4555-8555-555555555555";
const actor={userId,verifiedEmail:"creator@example.test"};
const input={workspaceId,listingId,sourceRevisionId,state:"takeover" as const,effectiveFrom:"2099-01-01T10:00:00Z"};
const receipt={id:other,listing_id:listingId,maintainer_state:"takeover",agreement_version:null,rate_reference:null,effective_from:"2099-01-01T10:00:00+00:00",recorded_by:userId,recorded_at:"2026-10-09T12:00:00.123456+00:00"};
const db=(data:unknown,error:null|{message:string}=null)=>({rpc:vi.fn().mockResolvedValue({data,error})});
describe("creator maintenance operations",()=>{
 it("records exact actor/workspace/source, retaining offset receipt bytes and using no provider",async()=>{const database=db(receipt);await expect(recordCreatorMaintenance(actor,input,database)).resolves.toEqual(receipt);expect(database.rpc).toHaveBeenCalledWith("record_creator_maintenance_from_workspace",{p_workspace_id:workspaceId,p_listing_id:listingId,p_source_revision_id:sourceRevisionId,p_user_id:userId,p_verified_email:actor.verifiedEmail,p_state:"takeover",p_agreement:null,p_rate:null,p_effective:input.effectiveFrom});});
 it("taper requires explicit agreement and reference, never a caller-selected rate",async()=>{const database=db({...receipt,maintainer_state:"tapered",agreement_version:"recorded-version",rate_reference:"recorded-rate"});await expect(recordCreatorMaintenance(actor,{...input,state:"tapered",agreementVersion:"recorded-version",rateReference:"recorded-rate"},database)).resolves.toMatchObject({maintainer_state:"tapered"});for(const forged of [{...input,rateBps:1000},{...input,userId:other},{...input,agreementVersion:"invented"},{...input,state:"tapered"}]){const unused=db(null);await expect(recordCreatorMaintenance(actor,forged,unused)).rejects.toThrow();expect(unused.rpc).not.toHaveBeenCalled();}});
 it.each(["listing_id","recorded_by"])("rejects foreign receipt %s",async field=>{await expect(recordCreatorMaintenance(actor,input,db({...receipt,[field]:other}))).rejects.toBeInstanceOf(WorkspaceStoreError);});
 it("requires exact state/agreement/date in returned receipt",async()=>{for(const change of [{maintainer_state:"creator"},{agreement_version:"invented"},{effective_from:"2099-01-01T11:00:00Z"}])await expect(recordCreatorMaintenance(actor,input,db({...receipt,...change}))).rejects.toBeInstanceOf(WorkspaceStoreError);});
 it("reads empty not-configured graph without synthesizing qualification or rates",async()=>{const graph={workspaceId,canMaintain:true,listings:[],agreements:[]};const database=db(graph);await expect(readCreatorMaintenance(actor,workspaceId,database)).resolves.toEqual(graph);expect(database.rpc).toHaveBeenCalledWith("read_creator_maintenance_operations",{p_workspace_id:workspaceId,p_user_id:userId,p_verified_email:actor.verifiedEmail});await expect(readCreatorMaintenance(actor,workspaceId,db({...graph,workspaceId:other}))).rejects.toBeInstanceOf(WorkspaceStoreError);});
 it("refuses history for a different listing and malformed responses",async()=>{const graph={workspaceId,canMaintain:false,agreements:[],listings:[{id:listingId,definitionId:"fictional-definition",sourceRevisionId,agreementVersion:null,rateReference:null,maintainerState:"creator",history:[{...receipt,listing_id:other}]}]};await expect(readCreatorMaintenance(actor,workspaceId,db(graph))).rejects.toBeInstanceOf(WorkspaceStoreError);await expect(readCreatorMaintenance(actor,workspaceId,db({}))).rejects.toBeInstanceOf(WorkspaceStoreError);});
 it("retains authority/conflict/storage refusal and sends no fallback",async()=>{await expect(recordCreatorMaintenance(actor,input,db(null,{message:"creator_maintenance_scope_denied"}))).rejects.toBeInstanceOf(WorkspaceAccessError);await expect(recordCreatorMaintenance(actor,input,db(null,{message:"approved_creator_maintenance_agreement_required"}))).rejects.toBeInstanceOf(WorkspaceConflictError);await expect(recordCreatorMaintenance(actor,input,null)).rejects.toBeInstanceOf(WorkspaceStoreError);});
});
