// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,expect,it,vi} from 'vitest';
import {WebsiteExperience} from '@/experience/websites/WebsiteExperience';
import {createWebsiteService} from '@/products/websites/server';
import {memoryBoundedStore,owner} from './fixtures/bounded-store';
import {brief,providerFixture} from './legacy-website-recovery-harness';
vi.mock('@/platform/infra/redis',()=>({getRedis:()=>null}));
let root:Root,node:HTMLDivElement;
afterEach(async()=>{await act(async()=>root?.unmount());node?.remove();vi.unstubAllGlobals();});
const button=(name:string)=>[...node.querySelectorAll('button')].find(item=>item.textContent?.trim()===name)!;
async function mount(workId?:string){vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);node=document.createElement('div');document.body.append(node);root=createRoot(node);await act(async()=>root.render(createElement(WebsiteExperience,{workspaceId:'workspace-a',workId})));}
async function change(input:HTMLInputElement|HTMLTextAreaElement,text:string){await act(async()=>{Object.getOwnPropertyDescriptor(input instanceof HTMLInputElement?HTMLInputElement.prototype:HTMLTextAreaElement.prototype,'value')!.set!.call(input,text);input.dispatchEvent(new Event('input',{bubbles:true}));});}
it('gives one plain-language creation recovery instruction while retaining actual captured creation and one generation',async()=>{
 const provider=providerFixture(),service=createWebsiteService(memoryBoundedStore(),{provider});const bodies:string[]=[];vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(String(input).includes('/connections'))return Response.json({tenants:[]});const body=String(init?.body);bodies.push(body);const {action:_action,workspaceId,...payload}=JSON.parse(body);const saved=await service.create(owner,workspaceId,payload);if(bodies.length===1)throw new TypeError('Failed to fetch');return Response.json(saved);}));
 await mount();await change(node.querySelector('input')!,brief.businessName);await change(node.querySelector('textarea')!,brief.description);await act(async()=>button('Generate a private preview').click());const alert=node.querySelector('[role="alert"]')!;expect(alert.textContent).not.toMatch(/Failed to fetch|TypeError/);expect(alert.textContent?.match(/could not be confirmed/g)).toHaveLength(1);expect(node.textContent?.match(/before (?:continuing|starting|making|reviewing)/g)).toHaveLength(1);expect(alert.textContent?.match(/entered details/gi)).toHaveLength(1);expect(node.querySelector('textarea')!.readOnly).toBe(true);expect(button('Generate a private preview').disabled).toBe(true);await act(async()=>button('Check this website request').click());expect(bodies).toHaveLength(2);expect(bodies[1]).toBe(bodies[0]);expect(provider.generate).toHaveBeenCalledTimes(1);expect(node.textContent).toContain('Private preview ready');
});
it('gives one saved-change instruction and keeps the draft through actual committed correction, failed read and exact current read',async()=>{
 const service=createWebsiteService(memoryBoundedStore(),{provider:providerFixture()});const saved=await service.create(owner,'workspace-a',{requestId:'copy-saved-recovery',brief});let writes=0,failedRead=false;vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{if(String(input).includes('/connections'))return Response.json({tenants:[]});if(init?.method==='POST'){writes++;const {action:_action,...payload}=JSON.parse(String(init.body));await service.revise(owner,saved.workId,payload);throw new TypeError('Failed to fetch');}if(failedRead)throw new TypeError('Failed to fetch');return Response.json(await service.read(owner,saved.workId));}));
 await mount(saved.workId);const field=node.querySelector('textarea')!;await change(field,'Keep the corrected description.');await act(async()=>button('Generate a new preview').click());const alert=node.querySelector('[role="alert"]')!;expect(alert.textContent).not.toContain('Failed to fetch');expect(alert.textContent?.match(/could not be confirmed/g)).toHaveLength(1);expect(node.textContent?.match(/before (?:continuing|starting|making|reviewing)/g)).toHaveLength(1);expect(alert.textContent?.match(/entered details/gi)).toHaveLength(1);expect(field.readOnly).toBe(true);failedRead=true;await act(async()=>button('Reload current state').click());expect(alert.textContent).not.toContain('Failed to fetch');expect(alert.textContent?.match(/(?:inputs are retained|entered details)/gi)).toHaveLength(1);expect(field.value).toBe('Keep the corrected description.');expect(button('Generate a new preview').disabled).toBe(true);failedRead=false;await act(async()=>button('Reload current state').click());expect(writes).toBe(1);expect(field.value).toBe('Keep the corrected description.');expect(node.querySelector('[role="alert"]')).toBeNull();
});
it('preserves the definitive initial sign-in refusal instead of replacing it with unknown recovery copy',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({error:'Sign in to create website work.'},{status:401})));await mount();await change(node.querySelector('input')!,brief.businessName);await change(node.querySelector('textarea')!,brief.description);await act(async()=>button('Generate a private preview').click());expect(node.querySelector('[role="alert"]')?.textContent).toContain('Sign in to create website work.');expect(node.textContent).not.toContain('could not be confirmed');expect(node.querySelector('textarea')!.readOnly).toBe(false);expect(button('Generate a private preview').disabled).toBe(false);
});
