// @vitest-environment jsdom
import {act,createElement} from "react";
import {createRoot,type Root} from "react-dom/client";
import {afterEach,expect,it,vi} from "vitest";
import {PackageCatalog} from "@/experience/systems/PackageCatalog";
import {bundlePreviewRequest} from "@/experience/systems/BundlePackagePreview";
const workspaceId="bb000000-0000-4000-8000-000000000011";
let root:Root|undefined;let host:HTMLDivElement;
async function mount(state:string,canInstall=true,fetcher?:typeof fetch){vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT",true);host=document.createElement("div");document.body.append(host);root=createRoot(host);await act(async()=>root!.render(createElement(PackageCatalog,{workspaceId,canInstall,requestOverride:fetcher??bundlePreviewRequest(state)})));}
afterEach(async()=>{if(root)await act(async()=>root!.unmount());host?.remove();root=undefined;vi.unstubAllGlobals();});
async function select(index:number,value:string){await act(async()=>{const element=host.querySelectorAll("select")[index]!;element.value=value;element.dispatchEvent(new Event("change",{bubbles:true}));});}
async function click(text:string){await act(async()=>{const button=[...host.querySelectorAll("button")].find(b=>b.textContent===text)!;button.click();});}
it("installs all three drafts with this business's selected resources and separate native reviews",async()=>{const request=vi.fn(bundlePreviewRequest("ready"));await mount("ready",true,request);expect(host.querySelector("button")?.disabled).toBe(true);await select(0,"elmwood");await select(1,"bb000000-0000-4000-8000-000000000100");await select(2,"/services");await click("Install all private drafts");expect(host.textContent).toContain("All 3 private drafts are ready");expect(host.querySelectorAll("a")).toHaveLength(3);const post=request.mock.calls.find(([,init])=>init?.method==="POST")!;expect(JSON.parse(String(post[1]!.body)).targets.websitePagePath).toBe("/services");});
it("holds the same immutable command and target selection after an uncertain failure",async()=>{const request=vi.fn(bundlePreviewRequest("stale"));await mount("stale",true,request);await select(0,"elmwood");await select(1,"bb000000-0000-4000-8000-000000000100");await select(2,"/services");await click("Install all private drafts");await click("Retry this bundle installation");const posts=request.mock.calls.filter(([,init])=>init?.method==="POST");expect(posts).toHaveLength(2);expect(posts[0]![1]!.body).toBe(posts[1]![1]!.body);expect(host.textContent).toContain("No bundle drafts were committed");expect(host.querySelectorAll("select")[0]!.disabled).toBe(true);});
it("delegated actor uses the exact owner's nonfirst page and cannot change target choices",async()=>{const request=vi.fn(bundlePreviewRequest("delegated"));await mount("delegated",false,request);expect(host.querySelectorAll("select")[2]!.value).toBe("/services");expect([...host.querySelectorAll("select")].every(s=>s.disabled)).toBe(true);await click("Install all private drafts");const post=request.mock.calls.find(([,init])=>init?.method==="POST")!;expect(JSON.parse(String(post[1]!.body))).toMatchObject({commandId:"bb000000-0000-4000-8000-000000000031",targets:{websitePagePath:"/services"}});});
it("missing Connections and member authority never enable installation",async()=>{await mount("missing");expect(host.textContent).toContain("Add the missing inquiry Connection");expect(host.querySelector("button")?.disabled).toBe(true);});
it("switching businesses immediately removes the previous declaration and receipt",async()=>{const request=bundlePreviewRequest("ready");await mount("ready",true,request);await act(async()=>root!.render(createElement(PackageCatalog,{workspaceId:"bb000000-0000-4000-8000-000000000012",canInstall:true,requestOverride:request})));expect(host.textContent).not.toContain("Keep service requests moving");expect(host.textContent).toContain("Apps returned for another business");});
