import {describe,it,expect} from "vitest";
import {prepareBundleInquiry,prepareBundleInquiryUpdate} from "@/products/inquiries";
import {prepareBundleWebsiteUpdate,prepareBundleWebsiteSection} from "@/products/websites";
import {InquiryEngine} from "@/products/inquiries/inquiry-engine";
const sourceBusinessId="bb000000-0000-4000-8000-000000000010",businessId="bb000000-0000-4000-8000-000000000011",actorId="bb000000-0000-4000-8000-000000000002",now="2026-10-07T10:00:00.000Z";
const inquiry={kind:"inquiry_pattern",name:"Intake",title:"How can we help?",intro:"Tell your team what you need.",fields:[{id:"name",label:"Name",kind:"text",required:true}],routingWithinMinutes:60};
const faq={kind:"website_section",title:"Questions",items:[{question:"How?",answer:"Contact our team."}]};
const document={version:2,siteName:"Business",theme:{palette:"warm",typeScale:"standard"},pages:[{path:"/",title:"Business",description:"",root:"root"}],nodes:{root:{id:"root",type:"Section",variant:"container",props:{},children:[],factIds:[]}},facts:{},assets:{},redirects:[],provenance:{composer:"rules"}};
const base={version:2,revision:1,title:"Business website",input:{requestId:"native-target",description:"Target owned website",businessName:"Business"},status:"review_ready",stages:[],checkpoint:null,candidate:{revision:1,contentHash:"a".repeat(64),document,previewHref:"/api/websites/own/preview"},approvedCandidateRevision:null,tenantId:"own-tenant",launch:{receipt:null,readBack:null},lastError:null,createdBy:actorId,createdAt:now,history:[{revision:1,kind:"candidate",actorId,at:now}]};
describe("bundle native updates",()=>{
 it("starts destination-owned local work after publication and preserves received records and own bindings",async()=>{
 const first=prepareBundleInquiry(inquiry,{sourceBusinessId,sourceId:"source:inquiry",businessId,actorId,state:null,now});const engine=new InquiryEngine({businessId,state:first.state,now:()=>now,livePublisher:{async publish(){return {status:"accepted",acceptanceId:"fictional-native-live",acceptedAt:now,providerReceipt:{fictional:true}};}}});engine.updateInquiryRules(first.work.id,{actorId,routing:{destination:"local@example.test"}});engine.setEmailConnection(first.work.id,{actorId,status:"connected",consent:"explicit",lastCheckedAt:now});engine.runRehearsal(first.work.id);const version=engine.getWork(first.work.id).draft!.version;engine.approvePublish(first.work.id,{actorId,version});await engine.publish(first.work.id,{actorId,explicit:true,version});engine.recordPublishVerification(first.work.id,{actorId,version,verified:true,evidence:["Fictional exact native readback"]});engine.receiveInquiry({capabilityId:first.work.capabilityId,expectedCapabilityVersion:version,fields:{name:"Existing business visitor"},inquiryId:"existing-native-record"});const state=engine.snapshot();const result=prepareBundleInquiryUpdate({...inquiry,title:"Business's next local title"},{state,businessId,capabilityId:first.work.capabilityId,sourceBusinessId,sourceVersion:1,actorId,now});expect(result.work?.draft?.form.title).toBe("Business's next local title");expect(result.work?.id).not.toBe(first.work.id);expect(result.state.inquiries).toEqual(state.inquiries);expect(result.work?.draft?.connections).toEqual(state.capabilities[0]?.live?.connections);expect(result.work?.draft?.routing?.destination).toBe("local@example.test");expect(result.work?.publishApproval).toBeNull();expect(result.state.capabilities[0]?.live).toEqual(state.capabilities[0]?.live);
 });
 it("stages local Version changes on the same immutable source pin through real native edits",()=>{
 const first=prepareBundleInquiry(inquiry,{sourceBusinessId,sourceId:"source:inquiry",businessId,actorId,state:null,now});const result=prepareBundleInquiryUpdate({...inquiry,title:"Business-owned title",fields:[...inquiry.fields,{id:"email",label:"Email",kind:"email",required:true}]},{state:first.state,businessId,capabilityId:first.work.capabilityId,sourceBusinessId,sourceVersion:1,actorId,now});expect(result.work?.draft?.form.title).toBe("Business-owned title");expect(result.work?.draft?.form.fields).toHaveLength(2);expect(result.work?.draft?.record.fields).toEqual(result.work?.draft?.form.fields);expect(result.work?.publishApproval).toBeNull();expect(result.state.capabilities[0]?.live).toBeNull();
 const engine=new InquiryEngine({businessId,state:first.state,now:()=>now});engine.applyDraftEdit(first.work.id,{actorId,source:"manual",path:"form.title",after:"Native owner's title"});const input={state:engine.snapshot(),businessId,capabilityId:first.work.capabilityId,sourceBusinessId,sourceVersion:1,actorId,now};expect(prepareBundleInquiryUpdate(inquiry,input).conflicts[0]?.path).toBe("form.title");expect(prepareBundleInquiryUpdate(inquiry,{...input,resolutions:[{path:"form.title",choice:"source"}]}).work?.draft?.form.title).toBe(inquiry.title);expect(prepareBundleInquiryUpdate({...inquiry,title:"Version owner's title"},input).conflicts[0]?.path).toBe("form.title");expect(prepareBundleInquiryUpdate({...inquiry,title:"Version owner's title"},{...input,resolutions:[{path:"form.title",choice:"source"}]}).work?.draft?.form.title).toBe("Version owner's title");
 });
 it("stages qualified shape in the actual inquiry pattern workflow and preserves own routing and records",()=>{
 const first=prepareBundleInquiry(inquiry,{sourceBusinessId,sourceId:"source:inquiry",businessId,actorId,state:null,now});
 const engine=new InquiryEngine({businessId,state:first.state,now:()=>now});
 engine.updateInquiryRules(first.work.id,{actorId,routing:{destination:"local@example.test"}});
 const current=engine.snapshot();
 const result=prepareBundleInquiryUpdate({...inquiry,intro:"New source explanation"},{state:current,businessId,capabilityId:first.work.capabilityId,sourceBusinessId,sourceVersion:2,actorId,now});
 expect(result.work?.draft?.form.intro).toBe("New source explanation");expect(result.work?.draft?.routing?.destination).toBe("local@example.test");expect(result.work?.publishApproval).toBeNull();expect(result.state.inquiries).toEqual(current.inquiries);expect(result.state.capabilities[0]?.live).toBeNull();
 });
 it("overlapping native edits require a named local/source choice; probing never mutates input",()=>{
 const first=prepareBundleInquiry(inquiry,{sourceBusinessId,sourceId:"source:inquiry",businessId,actorId,state:null,now});const engine=new InquiryEngine({businessId,state:first.state,now:()=>now});engine.applyDraftEdit(first.work.id,{actorId,source:"manual",path:"form.title",after:"Local title"});const state=engine.snapshot(),before=JSON.stringify(state),input={state,businessId,capabilityId:first.work.capabilityId,sourceBusinessId,sourceVersion:2,actorId,now};
 const result=prepareBundleInquiryUpdate({...inquiry,title:"Source title"},input);expect(result.work).toBeNull();expect(result.conflicts[0]?.path).toBe("form.title");expect(JSON.stringify(state)).toBe(before);
 const resolved=prepareBundleInquiryUpdate({...inquiry,title:"Source title"},{...input,resolutions:[{path:"form.title",choice:"local"}]});expect(resolved.work?.draft?.form.title).toBe("Local title");expect(resolved.work?.publishApproval).toBeNull();
 });
 it("replaces exactly one installed FAQ preserving native facts/assets and owner approval",()=>{
 const initial=prepareBundleWebsiteSection(faq,base,{actorId,name:"FAQ",pagePath:"/",now,workId:"bb000000-0000-4000-8000-000000000102"});const payload={...initial.payload,revision:1};
 const result=prepareBundleWebsiteUpdate({...faq,title:"New questions"},payload,{sectionId:initial.sectionId,pagePath:"/",workId:"bb000000-0000-4000-8000-000000000100",actorId,now,expectedDefinition:faq});
 expect(result.document?.nodes.root?.children.filter(id=>id===initial.sectionId)).toHaveLength(1);expect(result.document?.nodes[initial.sectionId]?.props).toMatchObject({title:"New questions"});expect(result.document?.assets).toEqual(initial.document.assets);expect(result.payload?.tenantId).toBe("own-tenant");expect(result.payload?.approvedCandidateRevision).toBeNull();expect(result.payload?.history.at(-1)?.actorId).toBe(actorId);
 const edited=structuredClone(payload);const editedNode=edited.candidate!.document.nodes[initial.sectionId]!;if(editedNode.type!=="Faq")throw new Error("Expected FAQ");editedNode.props.title="Local wording";
 expect(prepareBundleWebsiteUpdate({...faq,title:"New questions"},edited,{sectionId:initial.sectionId,pagePath:"/",workId:"bb000000-0000-4000-8000-000000000100",actorId,now,expectedDefinition:faq}).conflict).toBeTruthy();
 });
});
