import {describe,it,expect,vi} from "vitest";
vi.mock("@/platform/workspaces/repository",()=>({}));
import {signWebsiteShare,verifyWebsiteShare} from "@/products/websites/site-sharing";
import {checkWebsiteHealth,scanWebsiteHealth} from "@/products/websites/site-health";
const secret="test-only-signing-secret-with-more-than-32-characters";
const value={version:1 as const,workspaceId:"workspace",workId:"work",revision:1,contentHash:"a".repeat(64),createdBy:"actor",creatorEmail:"agency@example.com",recipientEmail:"owner@example.com",expiresAt:10000000};
const target={workspaceId:"workspace",workId:"work",tenantId:"tenant",revision:1,contentHash:"a".repeat(64),url:"https://tenant.strelva.com/"};
describe("private shares",()=>{it("binds recipient, revision and expiry with an authenticated signature",()=>{const token=signWebsiteShare(value,secret);expect(verifyWebsiteShare(token,secret,1)).toEqual(value);expect(()=>verifyWebsiteShare(token,secret,10000000)).toThrow();expect(()=>verifyWebsiteShare(token.slice(0,-4)+"AAAA",secret,1)).toThrow();expect(()=>signWebsiteShare(value,"short")).toThrow();});});
describe("health",()=>{it("distinguishes healthy, drift, absent hash and network failure",async()=>{expect((await checkWebsiteHealth(target,{fetch:async()=>`<meta name="strelva-site-hash" content="${target.contentHash}">`})).status).toBe("healthy");expect((await checkWebsiteHealth(target,{fetch:async()=>`<meta name="strelva-site-hash" content="${"b".repeat(64)}">`})).status).toBe("hash_mismatch");expect((await checkWebsiteHealth(target,{fetch:async()=>"<html>legacy</html>"})).status).toBe("hash_missing");expect((await checkWebsiteHealth(target,{fetch:async()=>{throw Error("timeout");}})).status).toBe("unreachable");});it("persists every check and fails closed on unavailable storage",async()=>{const saved=vi.fn();const alert=vi.fn();const result=await scanWebsiteHealth({list:async()=>[target],save:saved,fetch:async()=>null,alert});expect(result.failed).toBe(1);expect(saved).toHaveBeenCalledOnce();expect(alert).toHaveBeenCalledOnce();await expect(scanWebsiteHealth({list:async()=>[target],save:async()=>{throw Error("storage");},fetch:async()=>null})).rejects.toThrow("storage");});});
