// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,expect,it,vi} from 'vitest';
import {RebuildExperience} from '@/experience/websites/RebuildExperience';
import {harness,actor} from './rebuild-recovery-independent-harness';
let root:Root,node:HTMLDivElement;
afterEach(async()=>{await act(async()=>root?.unmount());node?.remove();vi.unstubAllGlobals();});
const button=(name:string)=>[...node.querySelectorAll('button')].find(item=>item.textContent?.trim()===name)!;
it.each([false,true])('retains visible exact GET recovery after operator loss and generic read with published URL removed=%s',async(removePublication)=>{
 const h=harness();const published=await h.launch(await h.create());let finish!:(value:Response)=>void;let saved:Record<string,unknown>|undefined;let canRead=false;const posts:string[]=[];const checks:string[]=[];
 const request=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const path=String(input);if(init?.method==='POST'){posts.push(path);const body=JSON.parse(String(init.body));saved={id:body.requestId,workspaceId:published.workspaceId,workId:published.workId,tenantId:published.rebuild.tenantId,publishedRevision:published.rebuild.candidate!.revision,publishedHash:published.rebuild.candidate!.contentHash,hostname:body.domain,records:[{type:'A',name:body.domain,value:'203.0.113.10'}],revisionHash:'b'.repeat(64),createdAt:'2026-10-09T00:00:00Z',expiresAt:'2027-10-09T00:00:00Z',current:!removePublication,decisionId:null,result:null,receiptEmail:null};return new Promise<Response>(resolve=>{finish=resolve;});}
 if(path.includes('/domain/request?')){checks.push(path);return canRead?Response.json({request:saved}):Response.json({error:'Current manage access denied'},{status:403});}
 if(path.includes('/rebuild?'))return Response.json(await h.service.read(actor,published.workId));if(path.includes('/history?'))return Response.json({revisions:[]});if(path.includes('/domain?'))return Response.json({domain:{hostname:'fictional.example.test',status:'verified',checkedAt:'2026-10-09T00:00:00Z',records:[]}});return Response.json({error:'Unneeded fictional read'},{status:503});});
 vi.stubGlobal('fetch',request);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);node=document.createElement('div');document.body.append(node);root=createRoot(node);const render=(operator:boolean)=>root.render(createElement(RebuildExperience,{workspaceId:published.workspaceId,workId:published.workId,operator,canPublish:true}));await act(async()=>render(true));const field=node.querySelector('section[aria-label="Owner domain request"] input') as HTMLInputElement;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(field,'fictional.example.test');field.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>button('Ask owner to approve domain').click());await act(async()=>render(false));await act(async()=>finish(Response.json({error:'Lost preparation acknowledgement'},{status:503})));const check=button('Check saved domain request');expect(check.closest('[hidden]')).toBeNull();expect(button('Edit fact').disabled).toBe(true);expect(field.value).toBe('fictional.example.test');expect(posts).toHaveLength(1);
 if(removePublication){const work=h.works.get(published.workId)!;h.works.set(work.id,{...work,payload:{...published.rebuild,status:'approved',launch:{receipt:null,readBack:null}}});}
 await act(async()=>button('Reload saved preview and history').click());expect(button('Edit fact').disabled).toBe(true);expect(button('Check saved domain request')).toBe(check);expect(field.isConnected).toBe(true);expect(field.value).toBe('fictional.example.test');expect(node.textContent).toContain('still needs its exact saved request');
 check.focus();await act(async()=>check.click());expect(button('Edit fact').disabled).toBe(true);expect(field.value).toBe('fictional.example.test');expect(button('Check saved domain request')).toBe(check);canRead=true;await act(async()=>check.click());expect(checks).toHaveLength(2);for(const path of checks){const url=new URL(path,'http://localhost');expect(url.searchParams.get('requestId')).toBe(saved!.id);expect(url.searchParams.get('workspaceId')).toBe(published.workspaceId);}expect(posts).toHaveLength(1);expect(button('Edit fact').disabled).toBe(false);expect(button('Ask owner to approve domain').disabled).toBe(true);expect(button('Prepare another domain request').disabled).toBe(true);const receipt=field.closest('section')!.querySelector('[role="status"]');expect(receipt?.textContent).toContain(removePublication?'no longer current':'Domain request saved');expect(document.activeElement).toBe(receipt);expect(receipt?.closest('[hidden]')).toBeNull();
});
