import { describe,it,expect,vi,beforeEach,afterEach } from "vitest";
import { load } from "cheerio";
import { WorkspaceAccessError,WorkspaceConflictError } from "@/platform/workspaces/types";
import { rebuildSelectionSchema } from "@/products/websites/rebuild-contracts";
import { siteDocumentSchema,siteDocumentHash } from "@/products/websites/site-document";
const deps=vi.hoisted(()=>({release:vi.fn(),user:vi.fn(),read:vi.fn(),approve:vi.fn(),launch:vi.fn(),create:vi.fn(),retry:vi.fn(),list:vi.fn(),member:vi.fn(),work:vi.fn(),workspaces:vi.fn(),handoff:vi.fn(),document:vi.fn(),after:vi.fn(),connect:vi.fn(),legacyConnect:vi.fn(),legacyOptions:vi.fn(),nativeOptions:vi.fn(),documentList:vi.fn(),documentReceipts:vi.fn()}));
vi.mock("@/products/websites/rebuild-release",()=>({websiteRebuildReleaseEnabled:deps.release,websiteRebuildReleaseMayBeOn:(...args:unknown[])=>deps.release(...args),websiteRebuildReleaseEnabledForWorkspace:async(...args:unknown[])=>deps.release(...args),websiteRebuildReleaseEnabledForTenant:async(...args:unknown[])=>deps.release(...args),websiteRebuildReleasedFor:async(...args:unknown[])=>deps.release(...args)}));
vi.mock("@/lib/db/server-client",()=>({getSessionUser:deps.user}));
vi.mock("@/products/websites/rebuild-service",()=>({readWebsiteRebuild:deps.read,approveWebsiteRebuild:deps.approve,launchWebsiteRebuild:deps.launch,createWebsiteRebuild:deps.create,retryWebsiteRebuild:deps.retry,listWebsiteRebuilds:deps.list,connectWebsiteRebuildCapabilities:deps.connect}));
vi.mock("@/platform/workspaces/repository",()=>({assertWorkspaceMember:deps.member,getWork:deps.work,listWorkspaces:deps.workspaces,createHandoff:deps.handoff}));
vi.mock("@/products/websites/document-store",()=>({websiteDocumentStore:{read:deps.document,list:deps.documentList,receipts:deps.documentReceipts}}));
vi.mock("@/platform/workspace-release",()=>({workspaceReleaseEnabled:()=>true}));
vi.mock("@/products/websites/server",()=>({connectWebsiteCapabilities:deps.legacyConnect,listWebsiteCapabilityOptions:deps.legacyOptions,WebsiteConflictError:class extends Error{},WebsiteUnavailableError:class extends Error{}}));
vi.mock("@/products/websites/published-capabilities",()=>({listPublishedWebsiteCapabilityOptions:deps.nativeOptions}));
vi.mock("next/server",async()=>({...await vi.importActual<typeof import("next/server")>("next/server"),after:deps.after}));
import { POST as approve } from "@/app/api/websites/[workId]/approve/route";
import { POST as start } from "@/app/api/websites/rebuild/route";
import { POST as share } from "@/app/api/websites/[workId]/share/route";
import { POST as handoff } from "@/app/api/websites/[workId]/handoff/route";
import { GET as shared } from "@/app/api/websites/shared/[token]/route";
import { GET as connectionsGet,POST as connectionsPost } from "@/app/api/websites/[workId]/connections/route";
import { GET as historyGet } from "@/app/api/websites/[workId]/history/route";
import { signWebsiteShare } from "@/products/websites/site-sharing";
const workId="11111111-1111-4111-8111-111111111111";const workspaceId="22222222-2222-4222-8222-222222222222";const userId="33333333-3333-4333-8333-333333333333";
const document=siteDocumentSchema.parse({version:2,siteName:"The Mooney Firm",theme:{palette:"light",typeScale:"standard"},pages:[{path:"/",title:"Firm",description:"",root:"hero"},{path:"/about",title:"About",description:"",root:"hero"}],nodes:{hero:{id:"hero",type:"Hero",variant:"statement",props:{title:"Firm",cta:{label:"About",href:"/about"}},children:[],factIds:[]}},facts:{},assets:{},redirects:[],provenance:{composer:"rules"}});
const contentHash=siteDocumentHash(document);const selection={expectedRevision:4,candidateRevision:2,candidateContentHash:contentHash};const context={params:Promise.resolve({workId})};
const secret="test-only-private-preview-secret-at-least-32-chars";
function request(body:unknown,options:{origin?:string;contentType?:string;query?:string}={}){return new Request(`https://app.strelva.com/api/websites/${workId}/approve${options.query??""}`,{method:"POST",headers:{origin:options.origin??"https://app.strelva.com","Content-Type":options.contentType??"application/json"},body:JSON.stringify(body)});}
function record(){return{workId,workspaceId,rebuild:{revision:4,status:"review_ready",tenantId:null,candidate:{revision:2,contentHash,document,previewHref:"/api/websites/preview"}}};}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv("CRON_SECRET",secret);deps.release.mockReturnValue(true);deps.user.mockResolvedValue({id:userId,email:"agency@example.com",email_confirmed_at:"2026-09-01T00:00:00Z"});deps.read.mockResolvedValue(record());deps.member.mockResolvedValue(undefined);deps.work.mockResolvedValue({id:workId,workspaceId,productId:"websites",resourceKind:"website",payload:{version:2}});deps.workspaces.mockResolvedValue([{id:workspaceId,kind:"agency",role:"owner",access:"member"}]);deps.approve.mockImplementation(async(_actor,_id,input)=>{rebuildSelectionSchema.parse(input);return record();});deps.create.mockResolvedValue({...record(),rebuild:{...record().rebuild,status:"building",revision:0}});deps.documentList.mockResolvedValue([]);deps.documentReceipts.mockResolvedValue([]);deps.document.mockResolvedValue({workspaceId,workId,revision:2,contentHash,document});deps.handoff.mockResolvedValue({handoff:{id:"handoff",status:"pending"},token:"acceptance-token"});});
afterEach(()=>vi.unstubAllEnvs());
describe("rebuild route boundaries",()=>{
 it("keeps the rollout gate ahead of identity or work reads",async()=>{deps.release.mockReturnValue(false);expect((await approve(request(selection),context)).status).toBe(503);expect(deps.user).not.toHaveBeenCalled();expect(deps.read).not.toHaveBeenCalled();expect(deps.approve).not.toHaveBeenCalled();});
 it("rejects anonymous and unverified identities",async()=>{deps.user.mockResolvedValue(null);expect((await approve(request(selection),context)).status).toBe(401);deps.user.mockResolvedValue({id:userId,email:"agency@example.com",email_confirmed_at:null});expect((await approve(request(selection),context)).status).toBe(401);expect(deps.read).not.toHaveBeenCalled();});
 it("requires same-origin JSON before processing a write",async()=>{expect((await approve(request(selection,{origin:"https://attacker.example"}),context)).status).toBe(403);expect((await approve(request(selection,{contentType:"text/plain"}),context)).status).toBe(415);expect(deps.user).not.toHaveBeenCalled();});
 it("rejects cross-workspace envelopes and malformed identifiers before approval",async()=>{expect((await approve(request({...selection,workspaceId:"44444444-4444-4444-8444-444444444444"}),context)).status).toBe(403);expect((await approve(request(selection),{params:Promise.resolve({workId:"bad-id"})})).status).toBe(400);expect(deps.approve).not.toHaveBeenCalled();});
 it("maps invalid/stale selections and revoked access without approval side effects",async()=>{expect((await approve(request({...selection,candidateContentHash:"wrong"}),context)).status).toBe(400);deps.approve.mockRejectedValue(new WorkspaceConflictError("Reload this candidate"));expect((await approve(request(selection),context)).status).toBe(409);deps.read.mockRejectedValue(new WorkspaceAccessError());expect((await approve(request(selection),context)).status).toBe(403);});
 it("creates one saved work first and schedules only the first pending build",async()=>{const response=await start(request({workspaceId,requestId:"rebuild-request-1",url:"https://attymooney.com"}));expect(response.status).toBe(202);expect(deps.create).toHaveBeenCalledWith({userId,verifiedEmail:"agency@example.com"},workspaceId,{requestId:"rebuild-request-1",url:"https://attymooney.com"},true);expect(deps.after).toHaveBeenCalledOnce();deps.create.mockResolvedValue(record());expect((await start(request({workspaceId,requestId:"rebuild-request-1",url:"https://attymooney.com"}))).status).toBe(200);expect(deps.after).toHaveBeenCalledOnce();});
});
describe("private agency routes",()=>{
 it("requires agency membership to create shares and never sends a message",async()=>{const response=await share(request({recipientEmail:"owner@example.com",expiresInHours:72}),context);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({recipientEmail:"owner@example.com",previewHref:expect.stringContaining("/api/websites/shared/")});deps.member.mockRejectedValue(new WorkspaceAccessError());expect((await share(request({recipientEmail:"owner@example.com"}),context)).status).toBe(403);deps.member.mockResolvedValue(undefined);deps.workspaces.mockResolvedValue([{id:workspaceId,kind:"customer",role:"owner",access:"member"}]);expect((await share(request({recipientEmail:"owner@example.com"}),context)).status).toBe(403);});
 it("checks recipient and current creator membership before disclosing a shared document",async()=>{const token=signWebsiteShare({version:1,workspaceId,workId,revision:2,contentHash,createdBy:userId,creatorEmail:"agency@example.com",recipientEmail:"owner@example.com",expiresAt:Date.now()+3600000},secret);const ctx={params:Promise.resolve({token})};expect((await shared(new Request("https://app.strelva.com/preview"),ctx)).status).toBe(403);expect(deps.document).not.toHaveBeenCalled();deps.user.mockResolvedValue({id:"owner",email:"owner@example.com",email_confirmed_at:"2026-09-01"});deps.member.mockRejectedValue(new WorkspaceAccessError());expect((await shared(new Request("https://app.strelva.com/preview"),ctx)).status).toBe(403);expect(deps.document).not.toHaveBeenCalled();deps.member.mockResolvedValue(undefined);const response=await shared(new Request("https://app.strelva.com/preview"),ctx);expect(response.status).toBe(200);expect(response.headers.get("X-Robots-Tag")).toContain("noindex");expect(response.headers.get("Content-Security-Policy")).toContain("form-action 'none'");expect(response.headers.get("Cache-Control")).toBe("private, no-store");const html=await response.text();expect(html).toContain(contentHash);expect(html).toContain(`/api/websites/shared/${token}?page=%2Fabout`);const about=await shared(new Request("https://app.strelva.com/preview?page=%2Fabout"),ctx);expect(about.status).toBe(200);expect(await about.text()).toContain("<title>About</title>");});
 it("keeps query-bearing navigation on the signed revision and forces only known document pages",async()=>{
  const linkedDocument=structuredClone(document);
  linkedDocument.nodes.hero!.props={title:"Firm",cta:{label:"About",href:"/about?campaign=source&page=%2Fnot-a-page&token=other#story"},secondaryCta:{label:"External",href:"https://outside.example/about?campaign=source#story"}};
  const linkedHash=siteDocumentHash(linkedDocument);
  deps.documentList.mockResolvedValue([]);deps.documentReceipts.mockResolvedValue([]);deps.document.mockResolvedValue({workspaceId,workId,revision:2,contentHash:linkedHash,document:linkedDocument});
  deps.user.mockResolvedValue({id:"owner",email:"owner@example.com",email_confirmed_at:"2026-09-01"});
  const token=signWebsiteShare({version:1,workspaceId,workId,revision:2,contentHash:linkedHash,createdBy:userId,creatorEmail:"agency@example.com",recipientEmail:"owner@example.com",expiresAt:Date.now()+3600000},secret);
  const ctx={params:Promise.resolve({token})};
  const response=await shared(new Request("https://app.strelva.com/preview"),ctx);expect(response.status).toBe(200);
  const html=load(await response.text());const href=html("a").filter((_i,anchor)=>html(anchor).text()==="About").attr("href")!;
  const link=new URL(href,"https://app.strelva.com");
  expect(link.pathname).toBe(`/api/websites/shared/${token}`);expect(link.searchParams.get("page")).toBe("/about");expect(link.searchParams.get("campaign")).toBe("source");expect(link.hash).toBe("#story");
  expect(html("a").filter((_i,anchor)=>html(anchor).text()==="External").attr("href")).toBe("https://outside.example/about?campaign=source#story");
  const about=await shared(new Request(link.href),ctx);expect(about.status).toBe(200);expect(await about.text()).toContain("<title>About</title>");
  expect((await shared(new Request("https://app.strelva.com/preview?page=%2Fnot-a-page"),ctx)).status).toBe(403);
 });
 it("proposes handoff only and refuses live customer ownership transfers",async()=>{const response=await handoff(request({recipientEmail:"owner@example.com"}),context);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({acceptanceRequired:true,handoff:{status:"pending"}});expect(deps.handoff).toHaveBeenCalledOnce();deps.read.mockResolvedValue({...record(),rebuild:{...record().rebuild,status:"published",tenantId:"mooney"}});expect((await handoff(request({recipientEmail:"owner@example.com"}),context)).status).toBe(409);expect(deps.handoff).toHaveBeenCalledOnce();});
});

describe("native connection dispatch",()=>{
 it("preserves legacy connection behavior without querying v2 storage when rollout is off",async()=>{deps.release.mockReturnValue(false);deps.legacyOptions.mockResolvedValue({tenants:[]});expect((await connectionsGet(new Request("https://app.strelva.com/connections"),context)).status).toBe(200);expect(deps.work).not.toHaveBeenCalled();expect(deps.legacyOptions).toHaveBeenCalledWith({userId,verifiedEmail:"agency@example.com"},workId);});
 it("reads options through the authorized v2 workspace and sends selection to the scoped service",async()=>{deps.nativeOptions.mockResolvedValue({tenants:[]});expect((await connectionsGet(new Request("https://app.strelva.com/connections"),context)).status).toBe(200);expect(deps.nativeOptions).toHaveBeenCalledWith({userId,verifiedEmail:"agency@example.com"},workspaceId,workId);const input={expectedRevision:4,selection:null};deps.connect.mockResolvedValue(record());expect((await connectionsPost(request(input),context)).status).toBe(200);expect(deps.connect).toHaveBeenCalledWith({userId,verifiedEmail:"agency@example.com"},workId,input);expect(deps.legacyConnect).not.toHaveBeenCalled();});
});

describe("publication history",()=>{
 it("reports all committed revision/hash pairs while later drafts remain unpublished",async()=>{deps.documentList.mockResolvedValue([1,2,3].map(revision=>({revision,contentHash:String(revision).repeat(64),createdAt:"2026-09-20T00:00:00.000Z"})));deps.documentReceipts.mockResolvedValue([{status:"published",candidateRevision:1,artifactHash:"1".repeat(64)},{status:"published",candidateRevision:2,artifactHash:"2".repeat(64)}]);const response=await historyGet(new Request("https://app.strelva.com/history"),context);expect(response.status).toBe(200);const body=await response.json();expect(body.revisions.map((row:{published:boolean})=>row.published)).toEqual([true,true,false]);expect(deps.documentReceipts).toHaveBeenCalledWith({userId,verifiedEmail:"agency@example.com"},{workspaceId,workId});});
});
