// @vitest-environment jsdom
import { act, createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
import { WebsiteDomainRequest } from '@/experience/websites/WebsiteRecoveryControls';
const workspaceId='71000000-0000-4000-8000-000000000002',workId='71000000-0000-4000-8000-000000000003';
let root:Root,container:HTMLDivElement;
afterEach(async()=>{await act(async()=>root?.unmount());container?.remove();vi.unstubAllGlobals();});
const button=(name:string)=>[...container.querySelectorAll('button')].find(b=>b.textContent?.trim()===name)!;
async function change(value:string){const input=container.querySelector('input')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});}
async function mount(request:typeof fetch,readOnly=false){vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>root.render(createElement(WebsiteDomainRequest,{workspaceId,workId,request,readOnly})));}
const receipt=(id:string)=>({id,workspaceId,workId,tenantId:'fictional',publishedRevision:2,publishedHash:'a'.repeat(64),hostname:'fictional.example.test',records:[{type:'A',name:'fictional.example.test',value:'203.0.113.10'}],revisionHash:'b'.repeat(64),createdAt:'2026-10-09T00:00:00Z',expiresAt:'2027-10-09T00:00:00Z',current:true,decisionId:null,result:null,receiptEmail:null});
it.each([false,true])('reads the exact unknown command without another POST and preserves focus choice outside=%s',async(moved)=>{
 let command!:ReturnType<typeof receipt>;let finish!:(r:Response)=>void;const calls:Array<{url:string;init?:RequestInit}>=[];
 const request=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{calls.push({url:String(input),init});if(init?.method==='POST'){command=receipt(JSON.parse(String(init.body)).requestId);return new Promise<Response>(resolve=>{finish=resolve;});}return Response.json({request:command});});
 await mount(request);await change('fictional.example.test');button('Ask owner to approve domain').focus();await act(async()=>{container.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));container.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});expect(calls).toHaveLength(1);
 const outside=document.createElement('button');outside.textContent='Other System';document.body.append(outside);if(moved)outside.focus();await act(async()=>finish(Response.json(null)));expect(document.activeElement).toBe(moved?outside:button('Check saved domain request'));expect(container.querySelector('input')!.readOnly).toBe(true);await change('other.example.test');expect(container.querySelector('input')!.value).toBe('fictional.example.test');
 await act(async()=>button('Check saved domain request').click());expect(calls.map(call=>call.init?.method)).toEqual(['POST','GET']);expect(new URL(calls[1]!.url,'http://localhost').searchParams.get('requestId')).toBe(command.id);expect(new URL(calls[1]!.url,'http://localhost').searchParams.get('workspaceId')).toBe(workspaceId);expect(container.textContent).toContain('Domain request saved for the owner');expect(document.activeElement).toBe(moved?outside:container.querySelector('[role="status"]'));outside.remove();
});
it.each(['missing','foreign','malformed','denied'] as const)('keeps unknown input and command frozen after %s current read',async(kind)=>{
 let saved!:ReturnType<typeof receipt>;let posts=0;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{if(init?.method==='POST'){posts++;saved=receipt(JSON.parse(String(init.body)).requestId);throw new Error('lost');}return kind==='denied'?Response.json({error:'Access changed'},{status:403}):Response.json({request:kind==='missing'?null:kind==='foreign'?{...saved,workId:'71000000-0000-4000-8000-000000000004'}:{...saved,publishedRevision:'invalid'}});});
 await mount(request);await change('fictional.example.test');await act(async()=>button('Ask owner to approve domain').click());await act(async()=>button('Check saved domain request').click());expect(posts).toBe(1);expect(button('Ask owner to approve domain').disabled).toBe(true);expect(container.querySelector('input')!.value).toBe('fictional.example.test');expect(container.querySelector('input')!.readOnly).toBe(true);expect(button('Check saved domain request')).toBeDefined();
});
it('accepts an old decided exact receipt without pretending it still awaits approval',async()=>{
 let saved!:ReturnType<typeof receipt>;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{if(init?.method==='POST'){saved=receipt(JSON.parse(String(init.body)).requestId);throw new Error('lost');}return Response.json({request:{...saved,current:false,decisionId:'71000000-0000-4000-8000-000000000004',expiresAt:'2020-01-01T00:00:00Z'}});});await mount(request);await change('fictional.example.test');await act(async()=>button('Ask owner to approve domain').click());await act(async()=>button('Check saved domain request').click());expect(container.textContent).toContain('already decided');expect(container.textContent).not.toContain('waits for their approval');button('Prepare another domain request').focus();await act(async()=>button('Prepare another domain request').click());expect(document.activeElement).toBe(container.querySelector('input'));expect(button('Ask owner to approve domain').disabled).toBe(false);
});
it('preserves the exact attempt across permission loss and does not perform another mutation',async()=>{
 let finish!:(r:Response)=>void;let saved!:ReturnType<typeof receipt>;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{if(init?.method==='POST'){saved=receipt(JSON.parse(String(init.body)).requestId);return new Promise<Response>(resolve=>{finish=resolve;});}return Response.json({request:saved});});await mount(request);await change('fictional.example.test');await act(async()=>button('Ask owner to approve domain').click());await act(async()=>root.render(createElement(WebsiteDomainRequest,{workspaceId,workId,request,readOnly:true})));await act(async()=>finish(Response.json(saved)));expect(button('Check saved domain request')).toBeDefined();expect(button('Ask owner to approve domain').disabled).toBe(true);await act(async()=>button('Check saved domain request').click());expect(request.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);expect(container.textContent).toContain('Domain request saved');expect(button('Prepare another domain request').disabled).toBe(true);
});

it('permits correction only after the exact pre-preparation invalid-domain refusal, then captures a fresh command',async()=>{
 const ids:string[]=[];const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));ids.push(body.requestId);return ids.length===1?Response.json({error:'Enter a valid domain you control.'},{status:409}):Response.json(receipt(body.requestId));});
 await mount(request);await change('not a domain');await act(async()=>button('Ask owner to approve domain').click());expect(container.querySelector('input')!.readOnly).toBe(false);expect(button('Check saved domain request')).toBeUndefined();await change('fictional.example.test');await act(async()=>button('Ask owner to approve domain').click());expect(ids).toHaveLength(2);expect(ids[0]).not.toBe(ids[1]);expect(container.textContent).toContain('Domain request saved for the owner');
});
it('keeps a generic post-persistence parse failure unknown instead of clearing its request identity',async()=>{
 const request=vi.fn(async()=>Response.json({error:'Check the request, website revision, and content hash.'},{status:400}));await mount(request);await change('fictional.example.test');await act(async()=>button('Ask owner to approve domain').click());expect(container.querySelector('input')!.readOnly).toBe(true);expect(button('Check saved domain request')).toBeDefined();expect(button('Ask owner to approve domain').disabled).toBe(true);expect(request).toHaveBeenCalledTimes(1);
});
