import { describe,it,expect,vi,beforeEach } from "vitest";
const dependencies=vi.hoisted(()=>({generate:vi.fn(),primary:vi.fn(),fallback:vi.fn()}));
vi.mock("ai",()=>({generateObject:dependencies.generate}));
vi.mock("@/lib/ai-models",()=>({getPrimaryModel:dependencies.primary,getFallbackModel:dependencies.fallback}));
import {makeJevComposer,makeJevVerifier,makeJevRisk,makeModelComposer,type RebuildProviderAdmission,type RebuildProviderRequest} from "@/products/websites/rebuild-providers";
import {siteDocumentSchema} from "@/products/websites/site-document";
const key="test-only-noncredential-placeholder";
const admit:RebuildProviderAdmission=async(_request,call)=>call();
const questions=[{id:"palette",candidates:["light","warm"]}];
const context={businessName:"The Mooney Firm",category:"LegalService"};
const answer=(answers:unknown)=>Response.json({model:"typesafe-ai/jev",answers,usage:{inputTokens:100,outputTokens:5},providerMetadata:{gateway:{cost:"0.000001"}}});
const document=siteDocumentSchema.parse({version:2,siteName:"The Mooney Firm",theme:{palette:"light",typeScale:"standard"},pages:[{path:"/",title:"Firm",description:"",root:"hero"}],nodes:{hero:{id:"hero",type:"Hero",variant:"statement",props:{title:"Firm"},children:[],factIds:[]}},facts:{},assets:{},redirects:[],provenance:{composer:"rules"}});
beforeEach(()=>{vi.resetAllMocks();dependencies.primary.mockReturnValue({label:"primary",model:{}});dependencies.fallback.mockReturnValue(null);});
describe("explicitly admitted Jev providers",()=>{
 it("uses the documented fixed endpoint and real per-choice probability",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(answer({palette:{type:"choice",choice:"warm",probabilities:{light:.2,warm:.8}}}));const admissionCalls=vi.fn<(request:RebuildProviderRequest,call:()=>Promise<unknown>)=>void>();const admitted:RebuildProviderAdmission=async(request,call)=>{admissionCalls(request,call);return call();};const composer=makeJevComposer({apiKey:key,admit:admitted,fetcher});expect(fetcher).not.toHaveBeenCalled();expect(await composer.compose(questions,context)).toEqual({choices:{palette:"warm"},confidence:.8,confidenceSource:"provider_probability"});expect(admissionCalls).toHaveBeenCalledWith(expect.objectContaining({model:"typesafe-ai/jev",purpose:"composition",inputBytes:expect.any(Number)}),expect.any(Function));expect(fetcher).toHaveBeenCalledWith("https://ai-gateway.vercel.sh/v1/evaluate",expect.objectContaining({method:"POST",redirect:"error",headers:expect.objectContaining({Authorization:`Bearer ${key}`})}));const request=JSON.parse(String(fetcher.mock.calls[0]![1]?.body));expect(request).toMatchObject({model:"typesafe-ai/jev",questions:{palette:{type:"choice",criteria:{light:"light",warm:"warm"}}}});});
 it("makes no provider request when budget or explicit configuration is absent",async()=>{const fetcher=vi.fn<typeof fetch>();const denied:RebuildProviderAdmission=async()=>{throw Error("budget denied");};await expect(makeJevComposer({apiKey:key,admit:denied,fetcher}).compose(questions,context)).rejects.toThrow("budget denied");await expect(makeJevComposer({apiKey:"",admit,fetcher}).compose(questions,context)).rejects.toThrow("explicitly configured");expect(fetcher).not.toHaveBeenCalled();});
 it("rejects out-of-catalog, missing and invalid confidence instead of guessing",async()=>{for(const value of [{palette:{type:"choice",choice:"invented",probabilities:{light:.2,warm:.8}}},{palette:{type:"choice",choice:"warm",probabilities:{warm:1}}},{palette:{type:"choice",choice:"warm",probabilities:{light:1,warm:1}}},{palette:{type:"choice",choice:"warm",probabilities:{light:.2,warm:2}}},{}]){const fetcher=vi.fn<typeof fetch>().mockResolvedValue(answer(value));await expect(makeJevComposer({apiKey:key,admit,fetcher}).compose(questions,context)).rejects.toThrow();}});
 it("aborts slow transport and prevents a late admission from initiating a request",async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation((_url,init)=>new Promise((_resolve,reject)=>init!.signal!.addEventListener("abort",()=>reject(Error("aborted")))));await expect(makeJevComposer({apiKey:key,admit,fetcher,timeoutMs:10}).compose(questions,context)).rejects.toThrow();expect(fetcher.mock.calls[0]![1]!.signal!.aborted).toBe(true);const unused=vi.fn<typeof fetch>();const delayed:RebuildProviderAdmission=async(_request,call)=>{await new Promise(resolve=>setTimeout(resolve,20));return call();};await expect(makeJevComposer({apiKey:key,admit:delayed,fetcher:unused,timeoutMs:5}).compose(questions,context)).rejects.toThrow("timed out");await new Promise(resolve=>setTimeout(resolve,30));expect(unused).not.toHaveBeenCalled();});
 it("keeps support uncertainty and high-risk uncertainty visible",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(answer({supported:{type:"boolean",probability:.8},highRisk:{type:"boolean",probability:.2}}));const result=await makeJevVerifier({apiKey:key,admit,fetcher})({sentence:"We have served clients for 20 years.",facts:[]});expect(result).toEqual({supported:false,confidence:.8,highRisk:true});});
 it("returns measured risk confidence and rejects missing probabilities",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(answer({risk:{type:"choice",choice:"low",probabilities:{low:.93,medium:.05,high:.02}}}));expect(await makeJevRisk({apiKey:key,admit,fetcher})({before:document,after:document,ops:[]})).toEqual({level:"low",confidence:.93});fetcher.mockResolvedValue(answer({risk:{type:"choice",choice:"low"}}));await expect(makeJevRisk({apiKey:key,admit,fetcher})({before:document,after:document})).rejects.toThrow();});
});
describe("admitted model composition",()=>{
 it("calls generateObject with catalog enum choices and explicitly self-reported confidence",async()=>{dependencies.generate.mockResolvedValue({object:{choices:{palette:"warm"},confidence:.7}});const composer=makeModelComposer({admit});expect(dependencies.generate).not.toHaveBeenCalled();expect(await composer.compose(questions,context)).toEqual({choices:{palette:"warm"},confidence:.7,confidenceSource:"model_self_reported"});expect(dependencies.generate).toHaveBeenCalledWith(expect.objectContaining({maxRetries:0,abortSignal:expect.any(AbortSignal),temperature:0}));});
 it("admits the primary and fallback independently and never uses hidden SDK retries",async()=>{dependencies.fallback.mockReturnValue({label:"fallback",model:{}});dependencies.generate.mockRejectedValueOnce(Error("provider unavailable")).mockResolvedValueOnce({object:{choices:{palette:"light"},confidence:.6}});const admissionCalls=vi.fn<(request:RebuildProviderRequest,call:()=>Promise<unknown>)=>void>();const admitted:RebuildProviderAdmission=async(request,call)=>{admissionCalls(request,call);return call();};expect((await makeModelComposer({admit:admitted}).compose(questions,context)).choices.palette).toBe("light");expect(admissionCalls.mock.calls.map(([request])=>request.model)).toEqual(["primary","fallback"]);expect(dependencies.generate).toHaveBeenCalledTimes(2);});
 it("fails closed on admission denial, fabricated options, or absent confidence",async()=>{const denied:RebuildProviderAdmission=async()=>{throw Error("denied");};await expect(makeModelComposer({admit:denied}).compose(questions,context)).rejects.toThrow("denied");expect(dependencies.generate).not.toHaveBeenCalled();for(const object of [{choices:{palette:"fake"},confidence:.9},{choices:{palette:"warm"}},{choices:{palette:"warm"},confidence:2}]){dependencies.generate.mockResolvedValue({object});await expect(makeModelComposer({admit}).compose(questions,context)).rejects.toThrow();}});
});
