// @vitest-environment jsdom
import { act, createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
import { WebsiteCutoverUndo } from '@/experience/websites/WebsiteRecoveryControls';
import { fixtureRebuild } from '@/experience/websites/rebuild-fixture';
import { createWebsiteDocumentStore } from '@/products/websites/document-store';
import { rebuildHttpFailure } from '@/app/api/websites/rebuild-http';
vi.mock('@/products/websites/system-releases',()=>({observeWebsiteWorkRelease:vi.fn()}));
vi.mock('@/platform/infra/redis',()=>({getRedis:()=>null}));
const actor={userId:'71000000-0000-4000-8000-000000000001',verifiedEmail:'owner@example.test'};
let root:Root,node:HTMLDivElement;
afterEach(async()=>{await act(async()=>root?.unmount());node?.remove();vi.unstubAllGlobals();});
const record=()=>({...fixtureRebuild('published'),tenantId:'fictional',publishedUrl:'https://fictional.example.test'});
const button=(name:string)=>[...node.querySelectorAll('button')].find(item=>item.textContent?.trim()===name)!;
const receipt=(body:Record<string,unknown>,workId:string)=>({receiptId:body.commandId,kind:'rebuild_cutover_undone',tenantId:body.tenantId,tenantStableId:'71000000-0000-4000-8000-000000000002',workId,revision:body.candidateRevision,contentHash:body.candidateContentHash,restoredBy:actor.userId,restoredAt:'2026-10-09T00:00:00Z',deliveryModel:'custom_repo',domainRestored:true,fallbackVerified:true});
async function mount(request:typeof fetch,readOnly=false){vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);node=document.createElement('div');document.body.append(node);root=createRoot(node);await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request,readOnly})));}
async function attest(){await act(async()=>node.querySelectorAll('input').forEach(input=>input.click()));}

it.each([false,true])('checks only the same committed command after loss through the actual store, respecting outside focus=%s',async(moved)=>{
 let writes=0;const saved=new Map<string,Record<string,unknown>>();const rpc=vi.fn(async(name:string,args:Record<string,unknown>)=>{expect(name).toBe('undo_website_linked_cutover');expect(args).toMatchObject({p_user_id:actor.userId,p_verified_email:actor.verifiedEmail,p_workspace_id:record().workspaceId,p_work_id:record().workId,p_domain_restored:true,p_fallback_verified:true});const id=String(args.p_command_id);if(saved.has(id))return{data:saved.get(id),error:null};writes++;const value=receipt({commandId:id,tenantId:args.p_tenant_id,candidateRevision:args.p_revision,candidateContentHash:args.p_content_hash},String(args.p_work_id));saved.set(id,value);return{data:value,error:null};});
 const store=createWebsiteDocumentStore({rpc});const bodies:string[]=[];let finish!:()=>void;
 const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const raw=String(init?.body);bodies.push(raw);const body=JSON.parse(raw);const value=await store.undoLinkedCutover!(actor,{workspaceId:body.workspaceId,workId:record().workId,tenantId:body.tenantId,revision:body.candidateRevision,contentHash:body.candidateContentHash,commandId:body.commandId,domainRestored:body.domainRestored,fallbackVerified:body.fallbackVerified});if(bodies.length===1){await new Promise<void>(resolve=>{finish=resolve;});throw new Error('Acknowledgement lost after retained RPC receipt');}return Response.json({receipt:value});});
 await mount(request);await attest();button('Restore previous website').focus();await act(async()=>{node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});expect(bodies).toHaveLength(1);expect(writes).toBe(1);
 const outside=document.createElement('button');outside.textContent='Other System';document.body.append(outside);if(moved)outside.focus();await act(async()=>finish());expect(document.activeElement).toBe(moved?outside:button('Check this undo command'));expect(button('Restore previous website').disabled).toBe(true);expect([...node.querySelectorAll('input')].every(input=>input.checked&&input.disabled)).toBe(true);
 await act(async()=>{node.querySelectorAll('input').forEach(input=>input.click());});await act(async()=>button('Check this undo command').click());expect(bodies).toHaveLength(2);expect(bodies[1]).toBe(bodies[0]);expect(writes).toBe(1);expect(rpc).toHaveBeenCalledTimes(2);expect(node.textContent).toContain('undo receipt for website version');expect(document.activeElement).toBe(moved?outside:node.querySelector('[role="status"]'));outside.remove();
});

it.each(['receiptId','workId','tenantId','revision','contentHash','tenantStableId','restoredBy','restoredAt','kind','deliveryModel','domainRestored','fallbackVerified'] as const)('rejects a malformed or foreign %s receipt and retains the exact command',async(field)=>{
 const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));const correct=receipt(body,record().workId);const changed=field==='revision'?999:field==='domainRestored'||field==='fallbackVerified'?false:field==='tenantId'?'other-tenant':field==='receiptId'||field==='workId'?'71000000-0000-4000-8000-000000000099':field==='contentHash'?'b'.repeat(64):'invalid';return Response.json({receipt:{...correct,[field]:changed}});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());expect(node.textContent).not.toContain('The previous website was restored.');expect(button('Check this undo command')).toBeDefined();expect(button('Restore previous website').disabled).toBe(true);expect(request).toHaveBeenCalledTimes(1);
});

it('preserves immutable command and authority through permission loss, then checks under regained current permission',async()=>{
 let finish!:(value:Response)=>void;let captured!:Record<string,unknown>;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));captured??=body;return request.mock.calls.length===1?new Promise<Response>(resolve=>{finish=resolve;}):Response.json({receipt:receipt(body,record().workId)});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request,readOnly:true})));await act(async()=>finish(Response.json({receipt:receipt(captured,record().workId)})));expect(button('Check this undo command').disabled).toBe(true);expect(node.textContent).not.toContain('The previous website was restored.');await act(async()=>button('Check this undo command').click());expect(request).toHaveBeenCalledTimes(1);await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request})));await act(async()=>button('Check this undo command').click());expect(request.mock.calls[1]![1]!.body).toBe(request.mock.calls[0]![1]!.body);expect(node.textContent).toContain('The previous website was restored.');
});

it('keeps later authority refusal unknown rather than minting another command',async()=>{
 let count=0;const request=vi.fn(async()=>{count++;return count===1?Response.json({receipt:null}):Response.json({error:'Sign in to open this website rebuild.'},{status:401});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());await act(async()=>button('Check this undo command').click());expect(button('Check this undo command')).toBeDefined();expect(button('Restore previous website').disabled).toBe(true);expect(request.mock.calls[1]![1]!.body).toBe(request.mock.calls[0]![1]!.body);
});

it('keeps target immutable when current candidate changes during an unknown command',async()=>{
 let captured!:Record<string,unknown>;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));if(!captured){captured=body;throw new Error('lost');}return Response.json({receipt:receipt(body,record().workId)});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());const changed=record();changed.candidate={...changed.candidate!,revision:changed.candidate!.revision+1,contentHash:'c'.repeat(64)};await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:changed,request})));await act(async()=>button('Check this undo command').click());expect(request.mock.calls[1]![1]!.body).toBe(request.mock.calls[0]![1]!.body);expect(node.textContent).toContain(`website version ${captured.candidateRevision}`);
});

it('treats post-RPC release observation failure as unknown while preserving actual committed receipt',async()=>{
 const {observeWebsiteWorkRelease}=await import('@/products/websites/system-releases');vi.mocked(observeWebsiteWorkRelease).mockRejectedValueOnce(new Error('Release observation unavailable'));
 let writes=0;let saved:Record<string,unknown>|undefined;const rpc=vi.fn(async(_name:string,args:Record<string,unknown>)=>{if(!saved){writes++;saved=receipt({commandId:args.p_command_id,tenantId:args.p_tenant_id,candidateRevision:args.p_revision,candidateContentHash:args.p_content_hash},String(args.p_work_id));}return{data:saved,error:null};});const store=createWebsiteDocumentStore({rpc});const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));try{return Response.json({receipt:await store.undoLinkedCutover!(actor,{workspaceId:body.workspaceId,workId:record().workId,tenantId:body.tenantId,revision:body.candidateRevision,contentHash:body.candidateContentHash,commandId:body.commandId,domainRestored:true,fallbackVerified:true})});}catch(cause){return rebuildHttpFailure(cause);}});await mount(request);await attest();await act(async()=>button('Restore previous website').click());expect(writes).toBe(1);expect(button('Check this undo command')).toBeDefined();await act(async()=>button('Check this undo command').click());expect(writes).toBe(1);expect(node.textContent).toContain('The previous website was restored.');
});

it('does not admit an initial command under read-only access or without both explicit attestations',async()=>{
 const request=vi.fn(async()=>Response.json({receipt:null}));await mount(request,true);await attest();await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(request).not.toHaveBeenCalled();await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request})));await act(async()=>node.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(request).not.toHaveBeenCalled();
});
it('does not adopt a delayed acknowledgement into a different workspace/work session',async()=>{
 let finish!:(value:Response)=>void;let body!:Record<string,unknown>;const old=record();const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Promise<Response>(resolve=>{finish=resolve;});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());const next={...old,workspaceId:'71000000-0000-4000-8000-000000000098',workId:'71000000-0000-4000-8000-000000000099'};await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:next,request})));await act(async()=>finish(Response.json({receipt:receipt(body,old.workId)})));expect(node.textContent).not.toContain('The previous website was restored.');expect(button('Check this undo command')).toBeUndefined();expect([...node.querySelectorAll('input')].every(input=>!input.checked)).toBe(true);
});

it('invalidates an acknowledgement when eligibility disappears and regains during the same request',async()=>{
 let finish!:(value:Response)=>void;let captured!:Record<string,unknown>;const request=vi.fn(async(_input:string|URL|Request,init?:RequestInit)=>{captured=JSON.parse(String(init?.body));return new Promise<Response>(resolve=>{finish=resolve;});});await mount(request);await attest();await act(async()=>button('Restore previous website').click());await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request,available:false})));await act(async()=>root.render(createElement(WebsiteCutoverUndo,{record:record(),request,available:true})));await act(async()=>finish(Response.json({receipt:receipt(captured,record().workId)})));expect(button('Check this undo command')).toBeDefined();expect(node.textContent).not.toContain('The previous website was restored.');expect(request).toHaveBeenCalledTimes(1);
});
