import {describe,it,expect,vi,beforeEach} from "vitest";
const deps=vi.hoisted(()=>({member:vi.fn(),list:vi.fn(),read:vi.fn(),documents:vi.fn(),inquiries:vi.fn(),grants:vi.fn(),send:vi.fn(),tenant:vi.fn(),workspaces:vi.fn(),receipts:vi.fn(),published:vi.fn(),native:vi.fn()}));
vi.mock("@/platform/workspaces/repository",()=>({assertWorkspaceMember:deps.member,listWork:deps.list,listWorkspaces:deps.workspaces}));
vi.mock("@/products/websites/rebuild-service",()=>({readWebsiteRebuild:deps.read}));
vi.mock("@/products/websites/document-store",()=>({websiteDocumentStore:{list:deps.documents,receipts:deps.receipts,published:deps.published,managePublishedTenant:deps.native}}));
vi.mock("@/products/inquiries/server",()=>({readInquiryWorkspace:deps.inquiries}));
vi.mock("@/products/scheduling/server",()=>({listPublicWebsiteBookingGrants:deps.grants}));
vi.mock("@/lib/email/send",()=>({sendEmailWithReceipt:deps.send}));
vi.mock("@/lib/tenants",()=>({getTenantConfig:deps.tenant}));
import {readWebsiteMonthlyReport,sendWebsiteMonthlyReport,sendOwnerWebsiteMonthlyReport} from "@/products/websites/site-report";
const actor={userId:"owner",verifiedEmail:"owner@example.com"};
beforeEach(()=>{vi.resetAllMocks();deps.member.mockResolvedValue(undefined);deps.native.mockResolvedValue(undefined);deps.list.mockResolvedValue([]);deps.documents.mockResolvedValue([]);deps.receipts.mockResolvedValue([]);deps.published.mockResolvedValue({workspaceId:"workspace",workId:"website",tenantId:"mooney",document:{siteName:"The Mooney Firm",provenance:{sourceUrl:"https://attymooney.com"}}});deps.read.mockResolvedValue({workId:"website",workspaceId:"workspace",rebuild:{title:"The Mooney Firm",tenantId:"mooney",candidate:{document:{provenance:{sourceUrl:"https://attymooney.com"}}}}});deps.inquiries.mockResolvedValue({recordsAvailable:false,records:null});});
describe("website reports",()=>{
 it("labels absent native stores and visibility unavailable, never zero or fabricated",async()=>{const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.inquiries.count).toBeNull();expect(report.bookings.scheduledInPeriod).toBeNull();expect(report.visibility.status).toBe("unavailable");expect(report.changes).toEqual([]);});
 it("counts only retained native submissions in the selected month",async()=>{deps.inquiries.mockResolvedValue({recordsAvailable:true,records:[{id:"in",createdAt:"2026-09-12T12:00:00Z"},{id:"out",createdAt:"2026-10-01T00:00:00Z"}]});const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.inquiries.count).toBe(1);expect(report.inquiries.limitedToRecentRecords).toBe(true);});
 it("links the report email to the implemented workspace query route (audit finding 9)",async()=>{const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});deps.send.mockResolvedValue({status:"suppressed"});await sendWebsiteMonthlyReport(report,"owner@example.com",actor);const url=new URL(deps.send.mock.calls[0]![0].options.button.url);expect(url.pathname).toBe("/workspace");expect(Object.fromEntries(url.searchParams)).toEqual({workspaceId:report.workspaceId,view:"websites",work:report.workId});});
 it("rechecks workspace membership before reading any private records",async()=>{deps.member.mockRejectedValue(Error("access"));await expect(readWebsiteMonthlyReport(actor,"website",{month:"2026-09"})).rejects.toThrow("access");expect(deps.inquiries).not.toHaveBeenCalled();});
 it("refuses report delivery from nonowners and never accepts an arbitrary recipient",async()=>{deps.workspaces.mockResolvedValue([{id:"workspace",role:"member",access:"member"}]);await expect(sendOwnerWebsiteMonthlyReport(actor,"website",{month:"2026-09"})).rejects.toThrow("owner");expect(deps.send).not.toHaveBeenCalled();deps.workspaces.mockResolvedValue([{id:"workspace",role:"owner",access:"member"}]);deps.send.mockResolvedValue({status:"suppressed"});await sendOwnerWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(deps.send).toHaveBeenCalledWith(expect.objectContaining({to:actor.verifiedEmail}));});
 it("sends only through shared tenant-aware transport with updates domain and idempotency",async()=>{const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});deps.send.mockResolvedValue({status:"suppressed",reason:"disabled"});await sendWebsiteMonthlyReport(report,"owner@example.com",actor);expect(deps.send).toHaveBeenCalledWith(expect.objectContaining({audience:"client",tenantId:"mooney",fromAddress:"report@updates.strelva.com",idempotencyKey:"website-report:website:2026-09"}));report.tenantId=null;expect((await sendWebsiteMonthlyReport(report,"owner@example.com",actor)).status).toBe("suppressed");expect(deps.send).toHaveBeenCalledOnce();});
});

const reservation=(requestId:string)=>({requestId,title:"Consultation",start:"2026-09-20T12:00:00Z",end:"2026-09-20T12:30:00Z",status:"accepted",provider:"google",providerId:`calendar-${requestId}`,verification:"verified"});
const schedule=(id:string,count:number)=>({id,productId:"scheduling",payload:{version:1,revision:1,title:"Consultations",createdBy:"owner",createdAt:"2026-09-01T00:00:00.000Z",history:[],availability:[],reservations:Array.from({length:count},(_,index)=>reservation(`${id}-${index}`))}});
const visibility=(url:string,score:number)=>({productId:"ai_visibility",updatedAt:"2026-09-25T12:00:00Z",payload:{business:"The Mooney Firm",url,score,grade:"B",verdict:"Saved measurement",topFix:"No fixture recommendation",measurementStatus:"measured",readinessMeasured:true,signals:[{id:"schema",label:"Structured data",pass:true,detail:"Found structured data",weight:2},{id:"robots",label:"Assistant crawler access",pass:false,detail:"Crawler access could not be confirmed",weight:1}],citation:{probed:false,mentioned:false,recommended:false,note:"Not probed"}}});
describe("published report authority",()=>{
 it("uses live booking grants and source URL while a future draft changes both",async()=>{
  deps.read.mockResolvedValue({workId:"website",workspaceId:"workspace",rebuild:{title:"Future draft name",tenantId:"mooney",candidate:{document:{provenance:{sourceUrl:"https://future.example"},capabilities:{tenant:"mooney",booking:{capabilityId:"draft-booking",version:2}}}}}});
  deps.published.mockResolvedValue({workspaceId:"workspace",workId:"website",tenantId:"mooney",document:{siteName:"The Mooney Firm",provenance:{sourceUrl:"https://attymooney.com"},capabilities:{tenant:"mooney",booking:{capabilityId:"live-booking",version:1}}}});
  deps.tenant.mockResolvedValue({stableId:"tenant-stable"});deps.grants.mockResolvedValue([{status:"published",tenant_stable_id:"tenant-stable",capability_id:"live-booking",capability_version:1,work_id:"live-schedule"},{status:"published",tenant_stable_id:"tenant-stable",capability_id:"draft-booking",capability_version:2,work_id:"future-schedule"}]);
  deps.list.mockResolvedValue([schedule("live-schedule",1),schedule("future-schedule",3),visibility("https://attymooney.com",61),visibility("https://future.example",99)]);
  const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.siteName).toBe("The Mooney Firm");expect(report.bookings).toMatchObject({status:"available",scheduledInPeriod:1,providerAccepted:1,providerVerified:1});expect(report.visibility.status).toBe("unavailable");expect(report.readiness).toMatchObject({status:"available",passedChecks:1,totalChecks:2});
  deps.grants.mockResolvedValue([{status:"revoked",tenant_stable_id:"tenant-stable",capability_id:"live-booking",capability_version:1,work_id:"live-schedule"}]);const revoked=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(revoked.bookings).toMatchObject({status:"unavailable",scheduledInPeriod:null,providerVerified:null});
 });
 it("marks every actually published revision from immutable receipts, not just the live pointer",async()=>{deps.documents.mockResolvedValue([1,2,3].map(revision=>({revision,contentHash:String(revision).repeat(64),createdAt:"2026-09-12T12:00:00Z",createdBy:"owner"})));deps.receipts.mockResolvedValue([{status:"published",candidateRevision:1,artifactHash:"1".repeat(64)},{status:"published",candidateRevision:2,artifactHash:"2".repeat(64)},{status:"published",candidateRevision:3,artifactHash:"a".repeat(64)}]);const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.changes.map(row=>row.published)).toEqual([true,true,false]);});
 it("does not treat a reserved but unpublished tenant as live or read its inquiry records",async()=>{deps.published.mockResolvedValue(null);const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.tenantId).toBeNull();expect(report.inquiries.count).toBeNull();expect(deps.inquiries).not.toHaveBeenCalled();expect(report.visibility.status).toBe("unavailable");});
});


describe("assistant citation evidence",()=>{
 it("does not turn readiness or unprobed default booleans into assistant visibility",async()=>{
  const assessment=visibility("https://attymooney.com",99);assessment.payload.citation={probed:false,mentioned:true,recommended:true,note:"An incomplete check"};deps.list.mockResolvedValue([assessment]);
  const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.visibility).toMatchObject({status:"unavailable"});expect(report.visibility.mentioned).toBeUndefined();expect(report.readiness).toMatchObject({passedChecks:1,totalChecks:2});
  deps.send.mockResolvedValue({status:"suppressed"});await sendWebsiteMonthlyReport(report,"owner@example.com",actor);const rows=deps.send.mock.calls[0]![0].options.rows;expect(rows).toContainEqual({label:"Saved assistant citation check",value:"Not measured"});expect(rows).toContainEqual({label:"Website readiness checks",value:"1 of 2 passed"});expect(JSON.stringify(rows)).not.toContain("99");
 });
 it("keeps actual negative citation evidence independent of later readiness and unrelated sites",async()=>{
  const measured=visibility("https://attymooney.com",61);measured.updatedAt="2026-09-20T12:00:00Z";measured.payload.citation={probed:true,mentioned:false,recommended:false,note:"Gemini did not name The Mooney Firm in one saved answer."};
  const unrelated=visibility("https://future.example",99);unrelated.payload.citation={probed:true,mentioned:true,recommended:true,note:"Different website"};
  deps.list.mockResolvedValue([visibility("https://attymooney.com",99),unrelated,measured]);const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.visibility).toEqual({status:"available",checkedAt:measured.updatedAt,mentioned:false,recommended:false,note:measured.payload.citation.note});expect(report.readiness.checkedAt).toBe("2026-09-25T12:00:00Z");
 });
 it("reports naming and recommendation separately even when website readiness is unavailable",async()=>{
  const measured=visibility("https://attymooney.com",61);measured.payload.readinessMeasured=false;measured.payload.signals=[];measured.payload.citation={probed:true,mentioned:true,recommended:false,note:"Named in one saved answer without a recommendation."};deps.list.mockResolvedValue([measured]);
  const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.visibility).toMatchObject({status:"available",mentioned:true,recommended:false});expect(report.readiness).toMatchObject({status:"unavailable",passedChecks:null,totalChecks:null});deps.send.mockResolvedValue({status:"suppressed"});await sendWebsiteMonthlyReport(report,"owner@example.com",actor);expect(deps.send.mock.calls[0]![0].options.rows).toContainEqual({label:"Saved assistant citation check",value:"Named; not recommended in this check"});
 });
 it("does not count checks outside the selected period or missing source association",async()=>{
  const old=visibility("https://attymooney.com",99);old.updatedAt="2026-08-31T23:59:59Z";old.payload.citation={probed:true,mentioned:true,recommended:true,note:"Prior month"};deps.list.mockResolvedValue([old]);const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});expect(report.visibility.status).toBe("unavailable");expect(report.readiness.status).toBe("unavailable");deps.published.mockResolvedValue(null);deps.list.mockResolvedValue([visibility("https://attymooney.com",99)]);expect((await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"})).readiness.status).toBe("unavailable");
 });
});


describe("monthly native record ownership",()=>{
 it("denies private counts before inquiry, scheduling work or grant reads after native ownership loss",async()=>{deps.native.mockRejectedValue(new (await import("@/platform/workspaces/types")).WorkspaceAccessError("Native owner revoked"));await expect(readWebsiteMonthlyReport(actor,"website",{month:"2026-09"})).rejects.toThrow("Native owner revoked");expect(deps.list).not.toHaveBeenCalled();expect(deps.inquiries).not.toHaveBeenCalled();expect(deps.grants).not.toHaveBeenCalled();expect(deps.send).not.toHaveBeenCalled();expect(deps.documents).toHaveBeenCalled();expect(deps.receipts).toHaveBeenCalled();});
 it("rechecks native ownership after preparing a report and before email transport",async()=>{const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});deps.native.mockRejectedValue(new (await import("@/platform/workspaces/types")).WorkspaceAccessError("Native owner revoked"));await expect(sendWebsiteMonthlyReport(report,actor.verifiedEmail,actor)).rejects.toThrow("Native owner revoked");expect(deps.send).not.toHaveBeenCalled();});
 it("does not email another recipient using a current owner's private report",async()=>{const report=await readWebsiteMonthlyReport(actor,"website",{month:"2026-09"});await expect(sendWebsiteMonthlyReport(report,"foreign@example.com",actor)).rejects.toThrow("verified current owner");expect(deps.send).not.toHaveBeenCalled();});
});
