import { describe,it,expect,vi } from "vitest";
import {load} from "cheerio";
import { createAgencyWebsiteDocumentService,assertAgencyDocumentNodeScope } from "@/products/websites/agency-document-service";
import { siteDocumentHash,siteDocumentSchema } from "@/products/websites/site-document";
import { websiteRebuildSchema } from "@/products/websites/rebuild-contracts";
import { prepareSitePatch } from "@/products/websites/site-operations";
import { WorkspaceAccessError,WorkspaceConflictError,type SavedWork } from "@/platform/workspaces/types";
const actor={userId:"81000000-0000-4000-8000-000000000001",verifiedEmail:"operator@example.test"};
const workspaceId="81000000-0000-4000-8000-000000000002";const workId="81000000-0000-4000-8000-000000000003";const bindingId="81000000-0000-4000-8000-000000000004";const at="2026-10-01T12:00:00.000Z";
function setup(){
 const document=siteDocumentSchema.parse({version:2,siteName:"[Synthetic business]",theme:{palette:"warm",typeScale:"editorial"},pages:[{path:"/",title:"Synthetic",description:"Synthetic fixture",root:"root"}],nodes:{root:{id:"root",type:"Section",variant:"container",props:{},children:["hero","services"],factIds:[]},hero:{id:"hero",type:"Hero",variant:"statement",props:{title:"Existing headline",body:"Existing body"},children:[],factIds:[]},services:{id:"services",type:"ServiceGrid",variant:"list",props:{title:"Services",items:[]},children:[],factIds:[]}},facts:{},assets:{},redirects:[],provenance:{sourceUrl:"https://fixture.example.test",composer:"rules"}});
 const payload=websiteRebuildSchema.parse({version:2,revision:3,title:document.siteName,input:{requestId:"agency-fixture-request",url:"https://fixture.example.test"},status:"approved",stages:[],checkpoint:null,lastError:null,candidate:{revision:2,contentHash:siteDocumentHash(document),document,previewHref:"/api/websites/fixture/preview"},approvedCandidateRevision:2,tenantId:"fixture",launch:{receipt:null,readBack:null},createdBy:actor.userId,createdAt:at,history:[]});
 const work:SavedWork={id:workId,workspaceId,productId:"websites",resourceKind:"website",title:document.siteName,payload,input:null,createdBy:actor.userId,createdAt:at,updatedAt:at};
 const grant={id:"81000000-0000-4000-8000-000000000005",managedWebsiteBindingId:bindingId,businessWorkspaceId:workspaceId,tenantId:"fixture",deliveryId:"81000000-0000-4000-8000-000000000006",assignmentId:"81000000-0000-4000-8000-000000000007",agencyWorkspaceId:"81000000-0000-4000-8000-000000000008",operatorUserId:actor.userId,grantedBy:"81000000-0000-4000-8000-000000000009",status:"active" as "active"|"revoked",expiresAt:"2026-10-02T12:00:00Z",createdAt:at,updatedAt:at,revokedAt:null,revokedBy:null};
 const readGrant=vi.fn(async()=>grant);const read=vi.fn(async()=>({work,section:"hero",sections:["hero"]}));const commit=vi.fn(async(_actor:typeof actor,input:{payload:unknown})=>({...work,payload:input.payload}));const subscription=vi.fn(async()=>true);
 const service=createAgencyWebsiteDocumentService({grants:{read:readGrant},documents:{readAgencyCandidate:read,commitAgencyCandidate:commit},subscription,enabled:()=>true,now:()=>at});
 const request=()=>({bindingId,websiteWorkId:workId,section:"hero",expectedRevision:3,candidateRevision:2,candidateContentHash:websiteRebuildSchema.parse(work.payload).candidate!.contentHash,ops:[{op:"replace",path:"/nodes/hero/props/title",value:"Proposed headline"}]});
 return{service,readGrant,read,commit,subscription,grant,work,document,request};
}
describe("scoped v2 agency document draft",()=>{
 it("commits one immutable reviewed candidate as the actual operator, clearing approval without publishing",async()=>{const h=setup();const result=await h.service.patch(actor,h.request());expect(h.commit).toHaveBeenCalledOnce();const [identity,commit]=h.commit.mock.calls[0]!;expect(identity).toEqual(actor);const payload=websiteRebuildSchema.parse(commit.payload);expect(payload).toMatchObject({revision:4,status:"review_ready",approvedCandidateRevision:null,tenantId:"fixture",launch:{receipt:null,readBack:null},candidate:{revision:3}});expect(payload.history.at(-1)?.actorId).toBe(actor.userId);expect(payload.candidate?.document.nodes.hero?.props).toMatchObject({title:"Proposed headline"});expect(payload.candidate?.document.nodes.hero?.verification?.needsReview).toBe(true);expect(payload.candidate?.document.facts[payload.candidate.document.nodes.hero!.factIds[0]!]!.origin).toBe("owner_stated");expect(result.previewHtml).toContain("Proposed headline");expect(Object.keys(h.service)).toEqual(["read","patch","preview"]);});
 it.each(["revoked","expired","different operator"])("rejects a %s grant before reading documents",async(reason)=>{const h=setup();if(reason==="revoked")h.grant.status="revoked";else if(reason==="expired")h.grant.expiresAt=at;else h.grant.operatorUserId="81000000-0000-4000-8000-000000000099";await expect(h.service.read(actor,bindingId)).rejects.toBeInstanceOf(WorkspaceAccessError);expect(h.read).not.toHaveBeenCalled();expect(h.commit).not.toHaveBeenCalled();});
 it.each(["assignment revoked","delivery revoked","sponsor no longer owner","native binding changed"])("propagates atomic denial after %s without returning a saved candidate",async(reason)=>{const h=setup();h.commit.mockRejectedValue(new WorkspaceAccessError(reason));await expect(h.service.patch(actor,h.request())).rejects.toBeInstanceOf(WorkspaceAccessError);expect(h.commit).toHaveBeenCalledOnce();expect(websiteRebuildSchema.parse(h.work.payload).candidate?.revision).toBe(2);});
 it("rejects stale revision/hash and foreign customer work",async()=>{const h=setup();await expect(h.service.patch(actor,{...h.request(),candidateContentHash:"a".repeat(64)})).rejects.toBeInstanceOf(WorkspaceConflictError);expect(h.commit).not.toHaveBeenCalled();await expect(h.service.patch(actor,{...h.request(),expectedRevision:2})).rejects.toBeInstanceOf(WorkspaceConflictError);await expect(h.service.patch(actor,{...h.request(),candidateRevision:1})).rejects.toBeInstanceOf(WorkspaceConflictError);await expect(h.service.read(actor,bindingId,{workId:"81000000-0000-4000-8000-000000000098"})).rejects.toBeInstanceOf(WorkspaceAccessError);h.work.workspaceId="81000000-0000-4000-8000-000000000099";await expect(h.service.patch(actor,h.request())).rejects.toBeInstanceOf(WorkspaceAccessError);expect(h.commit).not.toHaveBeenCalled();});
 it("rejects foreign sections, owner page authority and blocked structural content",async()=>{const h=setup();await expect(h.service.patch(actor,{...h.request(),ops:[{op:"replace",path:"/nodes/services/props/title",value:"Foreign section"}]})).rejects.toBeInstanceOf(WorkspaceAccessError);await expect(h.service.patch(actor,{...h.request(),ops:[{op:"add",path:"/pages/-",value:{path:"/extra",title:"Extra",description:"",root:"hero"}}]})).rejects.toThrow();expect(h.commit).not.toHaveBeenCalled();});
 it("checks foreign descendants and reordered structural children, not only changed JSON",()=>{const h=setup();const before=structuredClone(h.document);before.nodes.hero!.children=["services"];const after=structuredClone(before);after.nodes.hero!.children=[];expect(()=>assertAgencyDocumentNodeScope(before,after,"hero")).toThrow("outside");});
 it.each(["owner_confirmed","source","owner_stated"] as const)("keeps earlier %s facts while repeated copy creates separate review evidence",async(origin)=>{const h=setup();const earlier=await prepareSitePatch({document:h.document,ops:[{op:"replace",path:"/nodes/hero/props/title",value:"Proposed headline"}],forceReview:true});const confirmedId=earlier.document.nodes.hero!.factIds[0]!;earlier.document.facts[confirmedId]!.origin=origin;if(origin==="source")earlier.document.facts[confirmedId]!.sources=[{sourceId:"fixture-source",quote:"Proposed headline"}];earlier.document.facts[confirmedId]!.verification={supported:true,confidence:1};const old=websiteRebuildSchema.parse(h.work.payload);old.candidate!.document=earlier.document;old.candidate!.contentHash=siteDocumentHash(earlier.document);h.work.payload=old;const result=await h.service.patch(actor,{...h.request(),ops:[{op:"replace",path:"/nodes/hero/props/body",value:"New body"}]});const next=result.website!.rebuild.candidate!.document;expect(next.facts[confirmedId]).toEqual(earlier.document.facts[confirmedId]);expect(next.nodes.hero!.factIds).not.toContain(confirmedId);expect(next.nodes.hero!.factIds.some(id=>id.includes("_agency_"))).toBe(true);});
 it("previews actual multiple pages with links retaining the exact native grant and candidate",async()=>{const h=setup();const current=websiteRebuildSchema.parse(h.work.payload);current.candidate!.document.pages.push({path:"/services",title:"Services",description:"Service page",root:"services"});const hero=current.candidate!.document.nodes.hero!;if(hero.type==="Hero")hero.props.cta={label:"Read services",href:"/services?bindingId=foreign&document=1&revision=999#details"};current.candidate!.contentHash=siteDocumentHash(current.candidate!.document);h.work.payload=current;const view=await h.service.read(actor,bindingId);expect(view.previewHref).toContain("document=preview");const anchor=load(view.previewHtml!)("a").filter((_,element)=>load(view.previewHtml!)(element).text()==="Read services").attr("href")!;const linked=new URL(anchor,"https://strelva.test");expect(linked.pathname).toBe("/api/agency-website-draft-access");expect(Object.fromEntries(linked.searchParams)).toMatchObject({document:"preview",bindingId,websiteWorkId:workId,section:"hero",revision:"2",contentHash:current.candidate!.contentHash,page:"/services"});const preview=await h.service.preview(actor,bindingId,{workId,section:"hero",revision:2,contentHash:current.candidate!.contentHash,page:"/services"});expect(preview.html).toContain("Services");expect(preview.contentHash).toBe(current.candidate!.contentHash);expect(h.commit).not.toHaveBeenCalled();await expect(h.service.preview(actor,bindingId,{workId,section:"hero",revision:2,contentHash:"a".repeat(64),page:"/services"})).rejects.toBeInstanceOf(WorkspaceConflictError);h.grant.status="revoked";await expect(h.service.preview(actor,bindingId,{workId,section:"hero",revision:2,contentHash:current.candidate!.contentHash,page:"/services"})).rejects.toBeInstanceOf(WorkspaceAccessError);});
 it("fails closed on subscription refusal and disabled rollout",async()=>{const h=setup();h.subscription.mockRejectedValue(new WorkspaceAccessError("subscription"));await expect(h.service.read(actor,bindingId)).rejects.toBeInstanceOf(WorkspaceAccessError);expect(h.read).not.toHaveBeenCalled();const disabled=createAgencyWebsiteDocumentService({enabled:()=>false,grants:{read:h.readGrant},documents:{readAgencyCandidate:h.read,commitAgencyCandidate:h.commit}});await expect(disabled.read(actor,bindingId)).rejects.toThrow("not enabled");expect(h.readGrant).toHaveBeenCalledOnce();});
});
