import {describe,it,expect,vi,beforeEach,afterEach} from "vitest";
import {authenticatedCronRequest} from "@/__tests__/support/cron";
const deps=vi.hoisted(()=>({release:vi.fn(),list:vi.fn(),save:vi.fn(),fetch:vi.fn(),send:vi.fn(),heartbeat:vi.fn(),prune:vi.fn()}));
vi.mock("@/products/websites/rebuild-release",()=>({websiteRebuildReleaseEnabled:deps.release}));
vi.mock("@/products/websites/document-store",()=>({websiteDocumentStore:{listPublished:deps.list,recordHealth:deps.save,pruneCrawls:deps.prune}}));
vi.mock("@/lib/pinned-public-text",()=>({fetchPinnedPublicText:deps.fetch}));
vi.mock("@/lib/email/send",()=>({sendEmailWithReceipt:deps.send}));
vi.mock("@/lib/delivery-email",()=>({resolveLeadNotifyRecipients:()=>["operator@example.com"]}));
vi.mock("@/lib/heartbeat",()=>({recordHeartbeat:deps.heartbeat}));
import {GET} from "@/app/api/cron/website-health/route";
beforeEach(()=>{vi.resetAllMocks();deps.release.mockReturnValue(true);deps.prune.mockResolvedValue(0);deps.list.mockResolvedValue([{workspaceId:"workspace",workId:"website",tenantId:"mooney",revision:1,contentHash:"a".repeat(64)}]);deps.save.mockResolvedValue(undefined);deps.send.mockResolvedValue({status:"suppressed",reason:"disabled"});});
afterEach(()=>vi.unstubAllEnvs());
describe("website health cron",()=>{
 it("authenticates before scanning and skips when release is disabled",async()=>{vi.stubEnv("CRON_SECRET","test-cron-secret");expect((await GET(new Request("https://app.strelva.com/api/cron/website-health"))).status).toBe(401);expect(deps.list).not.toHaveBeenCalled();deps.release.mockReturnValue(false);expect(await (await GET(authenticatedCronRequest())).json()).toMatchObject({skipped:true});expect(deps.list).not.toHaveBeenCalled();expect(deps.prune).not.toHaveBeenCalled();expect(deps.heartbeat).toHaveBeenCalledWith("website-health",expect.objectContaining({ok:true}));});
 it("prunes expired crawl pages independently of published document health",async()=>{deps.prune.mockResolvedValue(3);deps.fetch.mockResolvedValue(`<meta name="strelva-site-hash" content="${"a".repeat(64)}">`);const response=await GET(authenticatedCronRequest());expect(response.status).toBe(200);expect(await response.json()).toMatchObject({crawlRetention:{status:"pruned",removed:3},processed:1,failed:0});expect(deps.save).toHaveBeenCalledWith(expect.objectContaining({status:"healthy"}));deps.prune.mockRejectedValue(Error("retention unavailable"));const failed=await GET(authenticatedCronRequest());expect(failed.status).toBe(207);expect(await failed.json()).toMatchObject({crawlRetention:{status:"failed"},processed:1,failed:1});expect(deps.save).toHaveBeenCalledTimes(2);expect(deps.heartbeat).toHaveBeenLastCalledWith("website-health",expect.objectContaining({ok:false,processed:1,failed:1}));});
 it("records missing hash and alerts only through shared operator transport",async()=>{deps.fetch.mockResolvedValue("<html>unexpected</html>");expect((await GET(authenticatedCronRequest())).status).toBe(207);expect(deps.save).toHaveBeenCalledWith(expect.objectContaining({status:"hash_missing",contentHash:"a".repeat(64)}));expect(deps.send).toHaveBeenCalledWith(expect.objectContaining({audience:"operator",fromAddress:"health@updates.strelva.com"}));expect(deps.heartbeat).toHaveBeenCalledWith("website-health",expect.objectContaining({ok:false,processed:1,failed:1}));});
 it("records healthy checks without notifying and does not conceal receipt storage failures",async()=>{deps.fetch.mockResolvedValue(`<meta name="strelva-site-hash" content="${"a".repeat(64)}">`);expect((await GET(authenticatedCronRequest())).status).toBe(200);expect(deps.send).not.toHaveBeenCalled();deps.save.mockRejectedValue(Error("durable storage down"));expect((await GET(authenticatedCronRequest())).status).toBe(503);expect(deps.heartbeat).toHaveBeenLastCalledWith("website-health",expect.objectContaining({ok:false,failed:1}));});
});
