// @vitest-environment jsdom
import { act, createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
import { RebuildExperience } from '@/experience/websites/RebuildExperience';
import { harness, actor } from './rebuild-recovery-independent-harness';
let root:Root,node:HTMLDivElement;
afterEach(async()=>{await act(async()=>root?.unmount());node?.remove();vi.unstubAllGlobals();});
const button=(name:string)=>[...node.querySelectorAll('button')].find(item=>item.textContent?.trim()===name)!;
it('keeps parent writes blocked across generic current reads and role loss until exact undo plus fresh saved-state read',async()=>{
 const h=harness();const published=await h.launch(await h.create());const value=published.rebuild;let failedRead=false,reads=0;const bodies:string[]=[];
 const request=vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(url.includes('/cutover-undo')&&init?.method==='POST'){const raw=String(init.body);bodies.push(raw);const body=JSON.parse(raw);return bodies.length===1?Response.json({receipt:{}}):Response.json({receipt:{receiptId:body.commandId,kind:'rebuild_cutover_undone',tenantId:body.tenantId,tenantStableId:'71000000-0000-4000-8000-000000000097',workId:published.workId,revision:body.candidateRevision,contentHash:body.candidateContentHash,restoredBy:actor.userId,restoredAt:'2026-10-09T00:00:00Z',deliveryModel:'custom_repo',domainRestored:true,fallbackVerified:true}});}
 if(url.includes('/rebuild?')){reads++;return failedRead?Response.json({error:'Saved read unavailable'},{status:503}):Response.json(await h.service.read(actor,published.workId));}
 if(url.includes('/history?'))return Response.json({revisions:[]});if(url.includes('/domain?'))return Response.json({domain:{hostname:'fictional.example.test',status:'verified',checkedAt:'2026-10-09T00:00:00Z',records:[]}});if(url.includes('/connections'))return Response.json({tenants:[{tenantId:value.tenantId,siteName:'Fictional site',inquiry:[{capabilityId:'fictional-inquiries',version:1,name:'Fictional inquiry'}],booking:[]}]});return Response.json({error:'Unneeded fictional read'},{status:503});});
 vi.stubGlobal('fetch',request);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);node=document.createElement('div');document.body.append(node);root=createRoot(node);
 const render=(operator=false)=>root.render(createElement(RebuildExperience,{workspaceId:published.workspaceId,workId:published.workId,canPublish:true,operator}));
 await act(async()=>render());const privateFact=button('Edit fact');expect(privateFact.disabled).toBe(false);const claim=[...node.querySelectorAll('article')].find(item=>item.textContent?.includes('We help families prepare wills and trusts.'))!;await act(async()=>claim.querySelector('button')!.click());const draft=claim.querySelector('textarea')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!.call(draft,'We help families with wills and trusts in Buffalo.');draft.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>button('Choose forms').click());
 const forms=node.querySelector('section[aria-label="Website visitor forms"]')!;const source=forms.querySelector('select')!;await act(async()=>{source.value=value.tenantId!;source.dispatchEvent(new Event('change',{bubbles:true}));});const inquiry=forms.querySelectorAll('select')[1]!;await act(async()=>{inquiry.value='fictional-inquiries';inquiry.dispatchEvent(new Event('change',{bubbles:true}));});expect(button('Update website preview').disabled).toBe(false);
 const undo=node.querySelector('section[aria-labelledby="cutover-undo-heading"]')!;await act(async()=>undo.querySelectorAll('input').forEach(input=>input.click()));await act(async()=>{undo.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));button('Update website preview').click();claim.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
 expect(bodies).toHaveLength(1);expect(request.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);expect(button('Edit fact').disabled).toBe(true);expect(draft.value).toBe('We help families with wills and trusts in Buffalo.');expect(button('Save correction').disabled).toBe(true);expect(button('Update website preview').disabled).toBe(true);expect(button('Check this undo command')).toBeDefined();
 await act(async()=>button('Reload saved preview and history').click());expect(reads).toBe(2);expect(button('Edit fact').disabled).toBe(true);expect(button('Check this undo command')).toBeDefined();expect(node.textContent).toContain('still needs its exact command receipt');
 await act(async()=>render(true));expect(button('Ask owner to approve domain').disabled).toBe(true);expect(button('Check this undo command').disabled).toBe(true);await act(async()=>render());
 await act(async()=>button('Check this undo command').click());expect(bodies).toHaveLength(2);expect(bodies[1]).toBe(bodies[0]);expect(button('Edit fact').disabled).toBe(true);expect(button('Reload current state')).toBeDefined();expect(node.querySelector('#rebuild-domain-heading')).toBeNull();failedRead=true;await act(async()=>button('Reload current state').click());expect(button('Edit fact').disabled).toBe(true);expect(node.textContent).toContain('could not be loaded');expect(node.querySelector('[role="alert"]')?.textContent?.match(/Your inputs/g)).toHaveLength(1);expect(draft.value).toBe('We help families with wills and trusts in Buffalo.');
 failedRead=false;await act(async()=>button('Reload current state').click());expect(button('Edit fact').disabled).toBe(false);expect(draft.value).toBe('We help families with wills and trusts in Buffalo.');expect(button('Save correction').disabled).toBe(false);expect(node.textContent).toContain('The previous website was restored for version');expect(node.textContent).toContain('Earlier publication receipt retained. The previous website is restored.');expect(node.textContent).not.toContain('This revision has been published.');expect(node.textContent).toContain('Saved preview and publication history');expect(node.querySelector('#rebuild-domain-heading')).toBeNull();expect(request.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(2);
});
