import {formatMoney} from "@/platform/connect/money-format";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {Card} from "@/components/ui/Card";
import MerchantControls from "./MerchantControls";
import RefundManager from "./RefundManager";
import PaymentManager,{type PaymentSource,type IssuedRequest} from "./PaymentManager";
import {moneyRpc} from "@/platform/connect";
import {connectEnabled} from "@/platform/connect";
import {readBusinessMoney} from "@/platform/connect/requests";
import {workspaceHttpActor} from "@/platform/workspaces/http";
import {workspaceReleaseEnabled} from "@/platform/workspace-release";
export const dynamic="force-dynamic";
export default async function Payments({searchParams}:{searchParams:Promise<{workspaceId?:string}>}){if(!workspaceReleaseEnabled()||!connectEnabled())notFound();const actor=await workspaceHttpActor();if(!actor)redirect("/sign-in");const {workspaceId}=await searchParams;let money;let detail:{sources:PaymentSource[];requests:IssuedRequest[]};try{const [sources,approved,loadedMoney]=await Promise.all([moneyRpc<{sources:PaymentSource[];requests:IssuedRequest[]}>("read_business_payment_sources",{p_workspace_id:workspaceId,p_user_id:actor.userId,p_verified_email:actor.verifiedEmail}),moneyRpc<PaymentSource[]>("read_agent_quote_payment_terms",{p_workspace_id:workspaceId,p_user_id:actor.userId,p_verified_email:actor.verifiedEmail}),readBusinessMoney(actor,workspaceId??"")]);detail=sources;detail.sources=detail.sources.map(s=>({...s,...approved.find(a=>a.source_id===s.source_id)}));money=loadedMoney;}catch{return <main className="mx-auto max-w-3xl px-6 py-12"><h1 className="font-display text-3xl">Payments</h1><p role="alert" className="mt-6">Payments could not be loaded. Confirm your access and try again.</p></main>;}return <main className="mx-auto max-w-3xl px-6 py-12 text-warm-black"><Link className="inline-flex min-h-12 items-center underline" href={`/workspace?workspaceId=${encodeURIComponent(workspaceId??"")}`}>Back to the business</Link><h1 className="mt-6 font-display text-3xl font-medium">Payments</h1><p className="mt-4 text-gray-muted">Customer payments belong to your business. Refunds and disputes stay with your merchant account.</p><Card className="mt-8" padding="lg">{money?.payments.length?<ul className="space-y-4">{money.payments.map(p=><li key={p.id} className="flex justify-between gap-4"><span>{p.purpose.replaceAll("_"," ")}</span><span className="tabular-nums">{formatMoney(p.amount_cents,p.currency)}</span></li>)}</ul>:<p>No customer payments have been recorded.</p>}</Card><MerchantControls key={`merchant:${workspaceId}`} workspaceId={workspaceId??""} state={money?.account?.state??"pending"}/><RefundManager key={`refund:${workspaceId}`} workspaceId={workspaceId??""} payments={(money?.payments??[]).filter(p=>money?.events.some(e=>e.payment_id===p.id&&e.kind==="paid")).map(p=>({...p,remainingCents:p.amount_cents-(money?.events.filter(e=>e.payment_id===p.id&&e.kind==="refund").reduce((s,e)=>s+e.amount_cents,0)??0)})).filter(p=>p.remainingCents>0)}/><PaymentManager key={workspaceId} workspaceId={workspaceId??""} sources={detail.sources} requests={detail.requests}/></main>;}
