"use client";
import {formatMoney,chargeUnits} from "@/platform/connect/money-format";
import {useRef,useState,useEffect} from "react";
import {Button} from "@/components/ui/Button";
import {Card} from "@/components/ui/Card";
import {TextInput,SelectInput} from "@/components/ui/TextInput";
export interface PaymentSource {source_id:string;kind:"quote"|"deposit";label:string;approvedCents?:number;approvedCurrency?:string;approvedTerms?:string;}
export interface IssuedRequest {id:string;kind:string;amount_cents:number;currency:string;status:string;refundRequired:boolean;}
export default function PaymentManager({workspaceId,sources,requests}:{workspaceId:string;sources:PaymentSource[];requests:IssuedRequest[]}) {
 const [source,setSource]=useState(sources[0]?.source_id??"");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState("usd");const [name,setName]=useState("");const [expires,setExpires]=useState("");const [refundable,setRefundable]=useState("yes");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [url,setUrl]=useState<string|null>(null);const key=useRef<string|null>(null);
 const selected=sources.find(s=>s.source_id===source);
 useEffect(()=>{if(selected?.approvedCents){setAmount((selected.approvedCents/chargeUnits(selected.approvedCurrency??"usd")).toFixed(2));setCurrency(selected.approvedCurrency??"usd");setName("Quoted work");}},[selected]);
 async function issue(e:React.FormEvent){e.preventDefault();const selected=sources.find(s=>s.source_id===source);if(!selected)return;setBusy(true);setError(null);key.current??=crypto.randomUUID();try{const cents=Math.round(Number(amount)*chargeUnits(currency));if(!Number.isSafeInteger(cents)||cents<=0)throw Error("Enter an amount above zero.");const response=await fetch("/api/workspace/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId,kind:selected.kind,sourceRecordId:source,lines:[{name,quantity:1,unitCents:cents}],currency,expiresAt:new Date(expires).toISOString(),...(selected.kind==="deposit"?{cancellationPolicy:{refundable:refundable==="yes"}}:{}),idempotencyKey:key.current})});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error??"The payment request could not be issued.");if(typeof result.paymentUrl!=="string")throw Error("The payment request could not be confirmed. Sign in and try again.");const link=new URL(result.paymentUrl);if(link.origin!==location.origin||link.pathname!=="/pay/business")throw Error("The payment link could not be confirmed.");setUrl(result.paymentUrl);}catch(e){setError(e instanceof Error?e.message:"The payment request could not be issued.");}finally{setBusy(false);}}
 return <><Card className="mt-8" padding="md"><h2 className="font-display text-xl">Issue a payment request</h2>{sources.length?<form onSubmit={issue} className="mt-6 grid gap-4"><SelectInput label="Inquiry or held booking" options={sources.map(s=>({value:s.source_id,label:s.label}))} value={source} onChange={e=>{setSource(e.target.value);key.current=null;}} disabled={busy||!!url}>{sources.map(s=><option key={s.source_id} value={s.source_id}>{s.label}</option>)}</SelectInput><TextInput label="Quoted work or deposit" required maxLength={200} value={name} onChange={e=>setName(e.target.value)} disabled={busy||!!url||!!selected?.approvedCents}/><div className="grid grid-cols-2 gap-4"><TextInput label="Amount" inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)} disabled={busy||!!url||!!selected?.approvedCents}/><SelectInput label="Currency" options={[{value:"usd",label:"USD"},{value:"cad",label:"CAD"},{value:"eur",label:"EUR"}]} value={currency} onChange={e=>setCurrency(e.target.value)} disabled={busy||!!url||!!selected?.approvedCents}><option value="usd">USD</option><option value="cad">CAD</option><option value="eur">EUR</option></SelectInput></div><TextInput label="Payment deadline" type="datetime-local" required value={expires} onChange={e=>setExpires(e.target.value)} disabled={busy||!!url}/>{sources.find(s=>s.source_id===source)?.kind==="deposit"?<SelectInput label="Refund deposit if booking is cancelled" options={[{value:"yes",label:"Yes"},{value:"no",label:"No"}]} value={refundable} onChange={e=>setRefundable(e.target.value)} disabled={busy||!!url}><option value="yes">Yes</option><option value="no">No</option></SelectInput>:null}{selected?.approvedTerms?<p className="whitespace-pre-wrap">{selected.approvedTerms}</p>:null}<p className="text-sm text-gray-muted">Issuing freezes the amount and terms. Share the resulting link with the customer.</p><Button size="lg" type="submit" disabled={busy||!!url}>{busy?"Issuing…":"Issue payment link"}</Button></form>:<p className="mt-4">A business inquiry or held booking is required before issuing payment.</p>}{error?<p className="mt-4" role="alert">{error}</p>:null}{url?<div className="mt-4"><p role="status">Payment link issued.</p><a className="mt-2 inline-flex min-h-12 items-center break-all underline" href={url}>Open customer payment link</a></div>:null}</Card><Card className="mt-8" padding="md"><h2 className="font-display text-xl">Requests</h2>{requests.length?<ul className="mt-4 space-y-4">{requests.map(q=><li key={q.id} className="flex flex-wrap justify-between gap-2"><span>{q.kind} · {q.status}{q.refundRequired?" · Refund review needed":""}</span><span>{formatMoney(q.amount_cents,q.currency)}</span></li>)}</ul>:<p className="mt-4">No payment requests yet.</p>}</Card></>;
}
