import { z } from "zod";
import { nativeGooglePlanSchema } from "../../src/products/google-listing/native/contracts";
const ref=z.string().trim().min(1).max(500),digest=z.string().regex(/^[a-f0-9]{64}$/),uuid=z.string().uuid();
/** This reviewed scope declares one future job; it never grants external rights. */
export const googleProviderProofSchema=z.object({schemaVersion:z.literal(1),kind:z.literal("google-make-real"),environment:z.literal("nonproduction"),authorizationReference:ref,approvedBy:ref,approvedAt:z.string().datetime({offset:true}),expiresAt:z.string().datetime({offset:true}),appOrigin:z.string().url().refine(value=>{const u=new URL(value);return ["localhost","127.0.0.1"].includes(u.hostname)&&u.origin===value&&!u.username&&!u.password;}),ownerAuthStatePath:z.string().startsWith("/"),dispatchJournalDirectory:z.string().startsWith("/"),workspaceId:uuid,ownerUserId:uuid,ownerEmail:z.string().email(),plan:nativeGooglePlanSchema,googlePrincipalEmail:z.string().email(),agencyAuthStatePath:z.string().startsWith("/"),agencyUserId:uuid,agencyEmail:z.string().email(),mandateId:uuid,disconnectCommandId:uuid,
nativeDatabaseEndpointDigest:digest,nativeDatabaseIdentityDigest:digest,supabaseUrlDigest:digest,redisUrlDigest:digest,redisNamespaceDigest:digest,
oauthProjectApprovalReference:ref,accountManagementRightsReference:ref,placeWriteAuthorizationReference:ref,reconciliationAuthorizationReference:ref,governedUndoAuthorizationReference:ref,unknownEffectQualificationReference:ref,mandateAuthorizationReference:ref,nativeStackQualificationReference:ref,oauthDisconnectAuthorizationReference:ref,isolatedCachePurgeAuthorizationReference:ref,nativeInspectionAuthorizationReference:ref,
actions:z.tuple([z.literal("publish-one-exact-google-draft"),z.literal("read-provider-receipt"),z.literal("reconcile-observed-unknown-without-replay"),z.literal("undo-exact-google-receipt"),z.literal("end-exact-local-mandate"),z.literal("disconnect-exact-google-grant"),z.literal("purge-isolated-expired-provider-cache"),z.literal("signed-native-google-reconnect")])}).strict().superRefine((value,ctx)=>{if(value.workspaceId!==value.plan.workspaceId||value.ownerUserId===value.agencyUserId)ctx.addIssue({code:"custom",message:"Exact independent owner/agency scope required."});});
export type GoogleProviderProofScope=z.infer<typeof googleProviderProofSchema>;
