"use client";
import {useMemo} from "react";
import {PackageCatalog} from "./PackageCatalog";
import {effectivePackageBehavior} from "@/platform/system-versions/declaration";
import {WorkspaceRequestContext} from "@/experience/workspace/WorkspaceRequest";
const workspaceId="bb000000-0000-4000-8000-000000000011",agency="bb000000-0000-4000-8000-000000000010",revisionId="bb000000-0000-4000-8000-000000000021",systemId="bb000000-0000-4000-8000-000000000020";
const definition={kind:"bundle",systems:[{key:"tracker",name:"Service tracker",definition:{kind:"internal_app",title:"Service tracker",fields:[{id:"need",label:"Need",type:"text",required:true}],components:[{kind:"form",fields:["need"]},{kind:"list",fields:["need"]}]}},{key:"inquiry",name:"Inquiry intake",definition:{kind:"inquiry_pattern",name:"Intake",title:"How can we help?",intro:"Tell your team what you need.",fields:[{id:"name",label:"Name",kind:"text",required:true},{id:"email",label:"Email",kind:"email",required:true}],routingWithinMinutes:60}},{key:"faq",name:"Website FAQ",definition:{kind:"website_section",title:"Common questions",items:[{question:"How do I start?",answer:"Send an inquiry to our team."}]}}]};
const declaration=effectivePackageBehavior(JSON.parse(JSON.stringify(definition)));
export const bundlePreviewListing={name:"Keep service requests moving",creatorName:"Elmwood Studio",source:{source:{businessId:agency,systemId},creatorWorkspaceId:agency,listingState:"listed"},revision:{source:{businessId:agency,systemId,revisionId,number:1},definition,summary:"Install a service tracker, inquiry pattern and website FAQ as three private Systems.",declaration,qualification:{revisionId,status:"qualified",evidence:["shareable_definition","declaration_match","rehearsal","prior_revision_compare"].map(check=>({revisionId,check,status:"passed",note:"Fictional local native evidence"})),humanReview:{state:"approved",reviewerId:"bb000000-0000-4000-8000-000000000003",reviewedAt:"2026-10-07T10:00:00.000Z",note:"Fictional exact-revision review"}}}};
export function BundlePackagePreview({state}:{state:string}){
 const request=useMemo(()=>bundlePreviewRequest(state),[state]);
 return <WorkspaceRequestContext.Provider value={request}><PackageCatalog key={state} workspaceId={workspaceId} canInstall={state!=="member"&&state!=="delegated"} canGrantInstall={state!=="member"&&state!=="delegated"}/></WorkspaceRequestContext.Provider>;
}

export function bundlePreviewRequest(state:string):typeof fetch {
const grants:Array<Record<string,unknown>>=[];const fn:typeof fetch=async(input,init)=>{const url=new URL(String(input),"http://fixture.test");if(state==="unavailable")return Response.json({error:"This business's Connections are temporarily unavailable."},{status:503});if(url.pathname.endsWith("bundle-targets")){if(init?.method==="POST"){const body=JSON.parse(String(init.body));return Response.json({grantId:body.grantId,targets:body.targets});}return Response.json({workspaceId,revisionId,commandId:url.searchParams.get("commandId"),boundTargets:state==="delegated"?{inquiryTenantId:"elmwood",websiteWorkId:"bb000000-0000-4000-8000-000000000100",websitePagePath:"/services"}:null,inquiry:state==="missing"?[]:[{id:"elmwood",label:"Elmwood service inquiries"}],websites:state==="missing"?[]:[{id:"bb000000-0000-4000-8000-000000000100",label:"Elmwood website",pages:[{path:"/",title:"Home"},{path:"/services",title:"Services"}]}]});}if(url.searchParams.has("grantsForRevision"))return Response.json({workspaceId,grants:state==="delegated"?[{grantId:"bb000000-0000-4000-8000-000000000050",workspaceId,commandId:"bb000000-0000-4000-8000-000000000031",agencyWorkspaceId:agency,revisionId,expiresAt:"2026-10-14T12:00:00.000Z",status:"active"}]:grants});if(init?.method==="POST"){const body=JSON.parse(String(init.body));if(body.action==="grant_install"){grants.splice(0,grants.length,{...body,grantId:"bb000000-0000-4000-8000-000000000050",status:"active"});delete grants[0]!.action;return Response.json(grants[0]);}if(body.action==="revoke_install"){grants.splice(0,grants.length);return Response.json(true);}if(state==="stale")return Response.json({error:"The website changed. No bundle drafts were committed. Reload its current document."},{status:409});return Response.json({workspaceId,bundleId:"bb000000-0000-4000-8000-000000000060",sourceRevisionId:revisionId,outcome:"drafts_created",components:definition.systems.map((s,i)=>({key:s.key,name:s.name,kind:s.definition.kind,systemId:`bb000000-0000-4000-8000-00000000010${i+1}`,versionId:`bb000000-0000-4000-8000-00000000020${i+1}`,openHref:`/workspace?view=system&workspaceId=${workspaceId}&system=bb000000-0000-4000-8000-00000000010${i+1}`,status:"draft"}))});}return Response.json({workspaceId,listings:state==="empty"?[]:[bundlePreviewListing]});};return fn;
}
