"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {z} from "zod";
import {Button} from "@/components/ui/Button";
import {SelectInput,TextInput} from "@/components/ui/TextInput";
import {bundleInstallReceiptSchema,bundleTargetChoicesSchema,bundleTargetsSchema,type BundleTargets} from "@/platform/system-versions/bundle-contracts";
import type {PackageListing} from "@/platform/system-versions/listing-contracts";
type Choices=z.infer<typeof bundleTargetChoicesSchema>;
function errorMessage(body:unknown,fallback:string){return body&&typeof body==="object"&&"error" in body&&typeof body.error==="string"?body.error:fallback;}
function TargetFields({choices,targets,onChange,disabled,needsInquiry,needsWebsite}:{choices:Choices;targets:BundleTargets;onChange:(targets:BundleTargets)=>void;disabled:boolean;needsInquiry:boolean;needsWebsite:boolean}){
 const website=choices.websites.find(w=>w.id===targets.websiteWorkId);
 return <div className="space-y-3">{needsInquiry?<SelectInput label="Your inquiry Connection" value={targets.inquiryTenantId??""} disabled={disabled} options={[{value:"",label:"Choose your business's inquiries"},...choices.inquiry.map(i=>({value:i.id,label:i.label}))]} onChange={event=>onChange({...targets,inquiryTenantId:event.target.value||undefined})}/>:null}{needsWebsite?<><SelectInput label="Your website" value={targets.websiteWorkId??""} disabled={disabled} options={[{value:"",label:"Choose your business's website"},...choices.websites.map(w=>({value:w.id,label:w.label}))]} onChange={event=>onChange({...targets,websiteWorkId:event.target.value||undefined,websitePagePath:undefined})}/>{website?<SelectInput label="Page for the section" value={targets.websitePagePath??""} disabled={disabled} options={[{value:"",label:"Choose a page"},...website.pages.map(p=>({value:p.path,label:p.title||p.path}))]} onChange={event=>onChange({...targets,websitePagePath:event.target.value||undefined})}/>:null}</>:null}</div>;
}
function requirements(listing:PackageListing){const systems=listing.revision.definition.systems as Array<{definition:{kind:string}}>;return {needsInquiry:systems.some(s=>s.definition.kind==="inquiry_pattern"),needsWebsite:systems.some(s=>s.definition.kind==="website_section")};}
function complete(targets:BundleTargets,needsInquiry:boolean,needsWebsite:boolean){return (!needsInquiry||Boolean(targets.inquiryTenantId))&&(!needsWebsite||Boolean(targets.websiteWorkId&&targets.websitePagePath));}
export function BundlePackageInstall({workspaceId,listing,canInstall,request}:{workspaceId:string;listing:PackageListing;canInstall:boolean;request:typeof fetch}){
 const [commandId,setCommandId]=useState(()=>crypto.randomUUID()),[choices,setChoices]=useState<Choices|null>(null),[targets,setTargets]=useState<BundleTargets>({}),[name,setName]=useState(listing.name),[error,setError]=useState(""),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<z.infer<typeof bundleInstallReceiptSchema>|null>(null),[retry,setRetry]=useState(0);
 const pending=useRef<string|null>(null),controller=useRef<AbortController|null>(null),inFlight=useRef(false),active=useRef(true);const {needsInquiry,needsWebsite}=requirements(listing);
 useEffect(()=>{active.current=true;const abort=new AbortController();setChoices(null);setError("");void(async()=>{
  if(!canInstall){const response=await request(`/api/workspace/packages?${new URLSearchParams({workspaceId,grantsForRevision:listing.revision.source.revisionId})}`,{credentials:"same-origin",signal:abort.signal});const body:unknown=await response.json();if(!response.ok)throw new Error(errorMessage(body,"Exact owner permission could not be read."));const grants=z.object({workspaceId:z.literal(workspaceId),grants:z.array(z.object({commandId:z.string().uuid(),revisionId:z.literal(listing.revision.source.revisionId),status:z.string(),expiresAt:z.string()}).passthrough())}).parse(body).grants;const grant=grants.find(g=>g.status==="active"&&Date.parse(g.expiresAt)>Date.now());if(!grant)throw new Error("The business owner must allow this exact installation and choose its Connections first.");if(grant.commandId!==commandId){if(!abort.signal.aborted)setCommandId(grant.commandId);return;}}
  const response=await request(`/api/workspace/packages/bundle-targets?${new URLSearchParams({workspaceId,revisionId:listing.revision.source.revisionId,commandId})}`,{credentials:"same-origin",signal:abort.signal}),body:unknown=await response.json();if(!response.ok)throw new Error(errorMessage(body,"Your bundle Connections could not be read."));const parsed=bundleTargetChoicesSchema.parse(body);if(parsed.workspaceId!==workspaceId||parsed.revisionId!==listing.revision.source.revisionId||parsed.commandId!==commandId)throw new Error("Connections returned for another installation.");if(!abort.signal.aborted){setChoices(parsed);if(!canInstall)setTargets(parsed.boundTargets??{});}
 })().catch(cause=>{if(!abort.signal.aborted)setError(cause instanceof Error?cause.message:"Bundle unavailable.");});return()=>{active.current=false;abort.abort();controller.current?.abort();};},[request,workspaceId,listing.revision.source.revisionId,canInstall,commandId,retry]);
 async function install(){if(inFlight.current||!choices||!complete(targets,needsInquiry,needsWebsite))return;pending.current??=JSON.stringify({action:"install",workspaceId,source:listing.revision.source,name:name.trim(),commandId,targets});inFlight.current=true;setBusy(true);setError("");const abort=new AbortController();controller.current=abort;try{const response=await request("/api/workspace/packages",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:pending.current,signal:abort.signal}),body:unknown=await response.json();if(!response.ok)throw new Error(errorMessage(body,"The installation could not be confirmed. Retry this same request."));const result=bundleInstallReceiptSchema.parse(body);if(result.workspaceId!==workspaceId||result.sourceRevisionId!==listing.revision.source.revisionId)throw new Error("Installation returned for another business or source.");if(active.current&&!abort.signal.aborted){setReceipt(result);pending.current=null;}}catch(cause){if(active.current&&!abort.signal.aborted)setError(cause instanceof Error?cause.message:"Bundle unavailable.");}finally{inFlight.current=false;if(active.current&&!abort.signal.aborted)setBusy(false);}}
 const unavailable=choices&&((needsInquiry&&!choices.inquiry.length)||(needsWebsite&&!choices.websites.length));
 return <div className="space-y-4">{receipt?<><p role="status" className="text-sm">All {receipt.components.length} private drafts are ready. Each System has its own Version and review. Nothing has gone live.</p><ul className="space-y-2">{receipt.components.map(c=><li key={c.key} className="text-sm"><Link className="underline" href={c.openHref}>{c.name}: open owner review</Link></li>)}</ul></>:<><p className="text-sm text-gray-muted">Install the whole bundle using this business’s Connections. Each component stays a private draft until its own approval.</p>{choices?<TargetFields choices={choices} targets={targets} onChange={setTargets} disabled={busy||Boolean(pending.current)||!canInstall} needsInquiry={needsInquiry} needsWebsite={needsWebsite}/>:!error?<p role="status" className="text-sm text-gray-muted">Reading your Connections…</p>:null}{unavailable?<p className="text-sm text-gray-muted">Add the missing inquiry Connection or a native website before installing this bundle.</p>:null}<TextInput label="Name in your business" value={name} maxLength={160} disabled={busy||Boolean(pending.current)} onChange={event=>setName(event.target.value)}/><Button size="sm" loading={busy} disabled={busy||!choices||Boolean(unavailable)||!name.trim()||!complete(targets,needsInquiry,needsWebsite)} onClick={()=>void install()}>{pending.current?"Retry this bundle installation":"Install all private drafts"}</Button></>}{error?<div className="space-y-2"><p role="alert" className="text-sm text-critical">{error}</p>{!choices?<Button size="sm" variant="secondary" onClick={()=>setRetry(r=>r+1)}>Retry Connections</Button>:null}</div>:null}</div>;
}
export function BundleTargetGrant({workspaceId,listing,grantId,commandId,request}:{workspaceId:string;listing:PackageListing;grantId:string;commandId:string;request:typeof fetch}){
 const [choices,setChoices]=useState<Choices|null>(null),[targets,setTargets]=useState<BundleTargets>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false);const pending=useRef<string|null>(null),active=useRef(true),mutation=useRef<AbortController|null>(null);const {needsInquiry,needsWebsite}=requirements(listing);
 useEffect(()=>{active.current=true;const abort=new AbortController();void request(`/api/workspace/packages/bundle-targets?${new URLSearchParams({workspaceId,revisionId:listing.revision.source.revisionId,commandId})}`,{credentials:"same-origin",signal:abort.signal}).then(async response=>{const body:unknown=await response.json();if(!response.ok)throw new Error(errorMessage(body,"Your Connections could not be read."));const parsed=bundleTargetChoicesSchema.parse(body);if(parsed.workspaceId!==workspaceId||parsed.commandId!==commandId||parsed.revisionId!==listing.revision.source.revisionId)throw new Error("Connections returned for another permission.");if(!abort.signal.aborted)setChoices(parsed);}).catch(cause=>{if(!abort.signal.aborted)setError(cause instanceof Error?cause.message:"Connections unavailable.");});return()=>{active.current=false;abort.abort();mutation.current?.abort();};},[request,workspaceId,commandId,listing.revision.source.revisionId]);
 async function grant(){if(busy)return;pending.current??=JSON.stringify({workspaceId,grantId,targets});setBusy(true);setError("");const abort=new AbortController();mutation.current=abort;try{const response=await request("/api/workspace/packages/bundle-targets",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:pending.current,signal:abort.signal});const body:unknown=await response.json();if(!response.ok)throw new Error(errorMessage(body,"Target permission could not be confirmed. Retry this same request."));const confirmed=z.object({grantId:z.literal(grantId),targets:bundleTargetsSchema}).strict().parse(body);const submitted=JSON.parse(pending.current!) as {targets:BundleTargets};if(confirmed.targets.inquiryTenantId!==submitted.targets.inquiryTenantId||confirmed.targets.websiteWorkId!==submitted.targets.websiteWorkId||confirmed.targets.websitePagePath!==submitted.targets.websitePagePath)throw new Error("Permission returned for different Connections.");if(active.current&&!abort.signal.aborted)setDone(true);}catch(cause){if(active.current&&!abort.signal.aborted)setError(cause instanceof Error?cause.message:"Permission unavailable.");}finally{if(active.current&&!abort.signal.aborted)setBusy(false);}}
 return <div className="space-y-3">{done?<p role="status">The agency can prepare this exact bundle using these Connections. Its completed drafts are read only under this install permission; you retain every release decision.</p>:<>{choices?<TargetFields choices={choices} targets={targets} onChange={setTargets} disabled={busy||Boolean(pending.current)} needsInquiry={needsInquiry} needsWebsite={needsWebsite}/>:null}<Button size="sm" variant="secondary" loading={busy} disabled={busy||!choices||!complete(targets,needsInquiry,needsWebsite)} onClick={()=>void grant()}>{pending.current?"Retry exact Connection permission":"Allow these exact Connections"}</Button></>}{error?<p role="alert" className="text-sm text-critical">{error}</p>:null}</div>;
}
