"use client";
import { useEffect,useRef,useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
const grant=z.object({grantId:z.string().uuid(),workspaceId:z.string().uuid(),commandId:z.string().uuid(),agencyWorkspaceId:z.string().uuid(),revisionId:z.string().uuid(),expiresAt:z.string(),status:z.enum(["active","revoked"])}).strict();
export function PackageInstallDelegation({workspaceId,revisionId,agencyWorkspaceId,creatorName,request}:{workspaceId:string;revisionId:string;agencyWorkspaceId:string;creatorName:string;request:typeof fetch}){
 const [opened,setOpened]=useState(false),[grants,setGrants]=useState<z.infer<typeof grant>[]>([]),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState("");const pending=useRef<string|null>(null);
 useEffect(()=>{if(!opened)return;const controller=new AbortController();void request(`/api/workspace/packages?${new URLSearchParams({workspaceId,grantsForRevision:revisionId})}`,{credentials:"same-origin",signal:controller.signal}).then(async response=>{const body:unknown=await response.json();if(!response.ok)throw new Error("Install permissions could not be read.");const parsed=z.object({workspaceId:z.literal(workspaceId),grants:z.array(grant)}).parse(body);if(parsed.grants.some(item=>item.revisionId!==revisionId||item.workspaceId!==workspaceId))throw new Error("Permissions returned for another installation.");if(!controller.signal.aborted)setGrants(parsed.grants);}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:"Install permissions unavailable.");});return()=>controller.abort();},[opened,request,workspaceId,revisionId,attempt]);
 async function command(grantId?:string){if(busy)return;pending.current??=JSON.stringify(grantId?{action:"revoke_install",workspaceId,grantId}:{action:"grant_install",workspaceId,agencyWorkspaceId,revisionId,commandId:crypto.randomUUID(),expiresAt:new Date(Date.now()+7*86400000).toISOString()});setBusy(true);setError("");try{const response=await request("/api/workspace/packages",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:pending.current});const body:unknown=await response.json().catch(()=>null);if(!response.ok)throw new Error(body&&typeof body==="object"&&"error" in body&&typeof body.error==="string"?body.error:"Install permission could not be confirmed. Retry the same request.");pending.current=null;setAttempt(v=>v+1);}catch(cause){setError(cause instanceof Error?cause.message:"Install permission could not be confirmed.");}finally{setBusy(false);}}
 const active=grants.filter(item=>item.status==="active"&&Date.parse(item.expiresAt)>Date.now());
 return <details onToggle={event=>setOpened(event.currentTarget.open)}><summary className="cursor-pointer text-sm">Let {creatorName} prepare this Version</summary><div className="mt-3 space-y-3 text-sm"><p className="text-gray-muted">Your existing delegated agency can install this exact revision and maintain only that resulting System for seven days. It receives no business admin role. You still approve release in Needs you.</p>{error?<p role="alert" className="text-critical">{error}</p>:null}{active.map(item=><div key={item.grantId} className="space-y-2"><p>Install permission expires {new Date(item.expiresAt).toLocaleDateString()}.</p><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void command(item.grantId)}>Revoke install permission</Button></div>)}{!active.length?<Button size="sm" variant="secondary" loading={busy} disabled={busy} onClick={()=>void command()}>{pending.current?"Retry install permission":"Allow this exact installation"}</Button>:null}</div></details>;
}
