"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/Button";
import { TextArea, TextInput, SelectInput } from "@/components/ui/TextInput";
import type { Learning } from "@/products/product-learning/contracts";
import type { WorkspaceWork } from "@/experience/workspace/contracts";

export type LearningSaved = { workId: string; workspaceId: string; learning: Learning; summary: { actualParticipants: number; simulatedEvidence: number; staleEvidence: number; reviewClaimIds: string[]; remainingBudgetCents: number; due: boolean } };
export type LearningTransport = { read(workId: string, signal: AbortSignal): Promise<LearningSaved>; write(body: Record<string, unknown>): Promise<LearningSaved> };
const transport: LearningTransport = {
  async read(workId, signal) { const response = await fetch(`/api/product-learning?workId=${encodeURIComponent(workId)}`, { signal, cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Research could not be loaded."); return body; },
  async write(input) { const response = await fetch("/api/product-learning", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Research could not be saved."); return body; },
};
type Props = { workspaceId: string; workId?: string; readOnly?: boolean; sources?: readonly WorkspaceWork[]; onSaved?: (workId: string) => void; transport?: LearningTransport };
const lines = (value: FormDataEntryValue | null) => String(value ?? "").split("\n").map(line => line.trim()).filter(Boolean);
const entry = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const newId = () => crypto.randomUUID();

export function LearningExperience(props: Props) { return <LearningSession key={`${props.workspaceId}:${props.workId ?? "new"}`} {...props} />; }

function LearningSession({ workspaceId, workId, readOnly, sources = [], onSaved, transport: api = transport }: Props) {
  const [saved, setSaved] = useState<LearningSaved | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [tab, setTab] = useState<"evidence" | "decision" | "verification">("evidence");
  const [claim, setClaim] = useState<Learning["claims"][number] | null>(null);
  const [reload, setReload] = useState(0);
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => {
    if (!workId) return;
    const controller = new AbortController();
    api.read(workId, controller.signal).then(result => { if (!controller.signal.aborted) { setSaved(result); setError(""); } }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Research could not be loaded."); });
    return () => controller.abort();
  }, [workId, api, reload]);
  async function write(body: Record<string, unknown>) {
    if (busy || readOnly) return;
    setBusy(true); setError(""); setMessage("");
    try { const result = await api.write(body); if (!mounted.current) return; setSaved(result); setMessage("Research saved. Evidence and release decisions remain separate."); if (!saved) onSaved?.(result.workId); }
    catch (cause) { if (mounted.current) setError(cause instanceof Error ? cause.message : "Research could not be saved."); }
    finally { if (mounted.current) setBusy(false); }
  }
  const command = (value: Record<string, unknown>) => saved ? write({ action: "command", workId: saved.workId, command: { ...value, expectedRevision: saved.learning.revision } }) : Promise.resolve();
  const work = saved?.learning;
  const availableSources = sources.filter(source => ["documents", "tracker", "research"].includes(source.productId));
  const disabled = Boolean(readOnly || busy);
  return <section aria-label="Internal product research" aria-busy={busy} className="mx-auto max-w-4xl space-y-6 p-4 sm:p-8">
    <header className="space-y-2"><p className="text-sm text-gray-muted">Internal research</p><h1 className="font-display text-2xl">{work?.title ?? "Test a business assumption"}</h1><p className="max-w-2xl text-sm text-gray-muted">{work?.objective ?? "Keep the evidence, the decision, and what actually happened together."}</p></header>
    {error ? <p role="alert" className="text-critical">{error} {workId ? <button type="button" className="underline" onClick={() => setReload(value => value + 1)}>Reload research</button> : null}</p> : null}
    {message ? <p role="status" className="text-sm">{message}</p> : null}
    {readOnly ? <p className="text-sm text-gray-muted">You have read-only access.</p> : null}
    {workId && !work && !error ? <p role="status">Loading research…</p> : null}
    {!workId && !work ? <form className="max-w-xl space-y-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void write({ action: "create", workspaceId, input: { title: entry(data, "title"), objective: entry(data, "objective"), intervalHours: 24, budgetCents: 0, sources: [{ id: "workspace-source", workId: entry(data, "source"), segment: entry(data, "segment"), freshForHours: 168 }] } }); }}>
      <TextInput label="Research question" name="title" maxLength={160} required disabled={disabled} />
      <TextArea label="What result would change our decision?" name="objective" maxLength={4000} required disabled={disabled} rows={3} />
      <SelectInput label="Authorized source" name="source" disabled={disabled} required options={[{ value: "", label: "Select saved work" }, ...availableSources.map(s => ({ value: s.id, label: s.title }))]} />
      <TextInput label="Whose experience does this source describe?" name="segment" required disabled={disabled} maxLength={4000} />
      <p className="text-sm text-gray-muted">Checks the saved source daily when the local runner is active. No paid research or external collection.</p>
      <Button type="submit" disabled={disabled || !availableSources.length}>Start research</Button>{!availableSources.length ? <p className="text-sm text-gray-muted">Save interview notes, a tracker, or an experiment first. <a className="underline" href={`/workspace?workspaceId=${encodeURIComponent(workspaceId)}&view=document`}>Create a source document</a></p> : null}
    </form> : null}
    {work && saved ? <>
      <div className="flex flex-wrap items-center justify-between gap-4 border-y border-gray-border py-4"><div className="text-sm"><p>{saved.summary.reviewClaimIds.length ? `${saved.summary.reviewClaimIds.length} claims need another look` : !work.evidence.length ? "No evidence collected yet" : saved.summary.staleEvidence ? "Some evidence needs a fresh check" : "Evidence is ready to review"}</p><p className="mt-1 text-gray-muted">{saved.summary.actualParticipants} actual participants · {saved.summary.staleEvidence} stale sources · {work.status === "paused" ? "Checks paused" : `Next check ${new Date(work.nextRunAt).toLocaleString()}`}</p></div><Button type="button" variant="secondary" disabled={disabled || !saved.summary.due} onClick={() => void write({ action: "collect", workId: saved.workId, expectedRevision: work.revision })}>{busy ? "Working…" : "Check sources"}</Button><Button type="button" variant="secondary" disabled={disabled} onClick={() => void command({ kind: work.status === "paused" ? "resume" : "pause" })}>{work.status === "paused" ? "Resume checks" : "Pause checks"}</Button></div>
      <nav aria-label="Research sections" className="flex flex-wrap gap-2">{([['evidence', 'Evidence'], ['decision', 'Product decision'], ['verification', 'Tests and outcomes']] as const).map(([value, label]) => <Button key={value} type="button" variant={tab === value ? "primary" : "secondary"} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</Button>)}</nav>
      {tab === "evidence" ? <div className="space-y-6">
        {work.runs.at(-1)?.outages.length ? <p role="status" className="text-sm text-warning">Could not read {work.runs.at(-1)!.outages.join(", ")}. An outage does not prove the original observation is wrong.</p> : null}
        <section className="space-y-3"><h2 className="font-display text-xl">What we know</h2>{!work.claims.length ? <p className="text-sm text-gray-muted">No claims yet. Check the source, then separate what it shows from what you infer.</p> : work.claims.map(item => <article key={item.id} className="border-b border-gray-border py-3"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-medium">{item.text}</h3><span className="text-xs text-gray-muted">{item.certainty}{saved.summary.reviewClaimIds.includes(item.id) ? " · Needs review" : ""}</span></div><p className="mt-2 text-sm">{item.job}</p><p className="mt-1 text-sm text-gray-muted">{item.unknowns.length ? `Unknown: ${item.unknowns.join("; ")}` : "No unanswered questions recorded."}</p><details className="mt-2 text-sm"><summary className="cursor-pointer">Supporting and contrary evidence</summary>{[...item.evidenceIds, ...item.contraryEvidenceIds].map(id => { const evidence = work.evidence.find(e => e.id === id); return evidence ? <p key={id} className="mt-2 whitespace-pre-wrap break-words">{item.contraryEvidenceIds.includes(id) ? "Contrary: " : ""}{evidence.excerpt} <span className="text-gray-muted">({evidence.status})</span></p> : null; })}</details>{!readOnly ? <button type="button" className="mt-3 text-sm underline" onClick={() => setClaim(item)}>Review claim</button> : null}</article>)}</section>
        {!readOnly ? <details open={claim ? true : undefined} className="border-b border-gray-border pb-4"><summary className="cursor-pointer text-sm">{claim ? "Review selected claim" : "Record a claim"}</summary><ClaimForm key={claim?.id ?? "new"} claim={claim} work={work} disabled={disabled} submit={command} /></details> : null}
        <section className="space-y-3"><h2 className="font-display text-xl">Source evidence</h2>{!work.evidence.length ? <p className="text-sm text-gray-muted">No collection has completed yet.</p> : work.evidence.map(evidence => <details key={evidence.id} className="border-b border-gray-border py-3"><summary className="cursor-pointer text-sm">{evidence.segment} · {evidence.evidenceKind.replaceAll("_", " ")} · {evidence.status}</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm">{evidence.excerpt}</p><p className="mt-2 break-words text-xs text-gray-muted">{evidence.reference}<br />Captured {new Date(evidence.capturedAt).toLocaleString()}. Fresh through {new Date(evidence.freshUntil).toLocaleString()}.</p></details>)}</section>
      </div> : null}
      {tab === "decision" ? <div className="space-y-6"><section className="space-y-4"><h2 className="font-display text-xl">What should change?</h2>{!work.options.length ? <p className="text-sm text-gray-muted">No alternatives have been investigated yet. Compare removing a workflow, an integration, a new service, and doing nothing before selecting a build.</p> : work.options.map(option => { const strategy = work.strategies.find(s => s.optionId === option.id); const decision = work.decisions.filter(d => d.optionId === option.id).at(-1); return <article key={option.id} className="space-y-3 border-b border-gray-border pb-4"><h3 className="font-medium">{option.behavior}</h3><p className="text-sm text-gray-muted">{option.advantage}</p>{strategy ? <p className="text-sm">This fails if: {strategy.falsifyingTest}</p> : <p className="text-sm text-gray-muted">Strategy has not been investigated.</p>}{decision ? <p className="text-sm">{decision.decision}: {decision.reason}</p> : null}{!readOnly ? <form className="flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void command({ kind: "decide", optionId: option.id, decision: entry(data, "decision"), reason: entry(data, "reason") }); }}><SelectInput label="Decision" name="decision" disabled={disabled} options={[{ value: "park", label: "Park" }, { value: "reject", label: "Reject" }, ...(strategy && option.approach !== "no_build" ? [{ value: "test", label: "Test" }] : [])]} /><div className="flex-1"><TextInput label="Why?" name="reason" required maxLength={4000} disabled={disabled} /></div><Button type="submit" variant="secondary" disabled={disabled}>Record decision</Button></form> : null}</article>; })}</section><section className="space-y-3"><h2 className="font-display text-xl">Current product agreement</h2>{work.briefs.length ? <><p className="font-medium">{work.briefs.at(-1)!.promise}</p><p className="text-sm text-gray-muted">For {work.briefs.at(-1)!.audience} · Revision {work.briefs.at(-1)!.revision}</p><ul className="list-disc space-y-2 pl-5 text-sm">{work.briefs.at(-1)!.dispositions.map((item, i) => <li key={i}>{item.action}: {item.behavior}. {item.reason}</li>)}</ul><details><summary className="cursor-pointer text-sm">Boundaries and previous agreements</summary>{work.briefs.slice().reverse().map(brief => <article key={brief.revision} className="mt-3 text-sm"><p>Revision {brief.revision}: {brief.promise}</p><p className="text-gray-muted">{brief.boundaries.join("; ")}</p></article>)}</details></> : <p className="text-sm text-gray-muted">No accepted product brief. A parked idea does not create a build task.</p>}</section></div> : null}
      {tab === "verification" ? <div className="space-y-6"><Section title="What changed in the trial?" empty={!work.trials.length ? "No matched trial has been recorded." : undefined}>{work.trials.map(trial => <article key={trial.id} className="border-b border-gray-border py-3 text-sm"><h3 className="font-medium">{trial.capability}</h3><p>{trial.changed}</p><p className="mt-2">Same {trial.baseline.cases} cases: {trial.baseline.completed} completed before, {trial.candidate.completed} after. {trial.candidate.corrections} corrections.</p><p className="text-gray-muted">Baseline {trial.baseline.evidenceKind.replaceAll("_", " ")}; candidate {trial.candidate.evidenceKind.replaceAll("_", " ")} · {trial.candidate.minutes} minutes · {trial.candidate.costCents === null ? "Cost unknown" : `$${(trial.candidate.costCents / 100).toFixed(2)}`}</p></article>)}</Section><Section title="Did the experience work?" empty={!work.experiences.length ? "No goal-based sessions recorded." : undefined}>{work.experiences.map(session => <article key={session.id} className="border-b border-gray-border py-3 text-sm"><h3 className="font-medium">{session.objective}</h3><p>{session.completion} · {session.role} · {session.conditions.join(", ")}</p><p className="text-gray-muted">{session.evidenceKind === "agent" ? "Agent exercise. Human usability remains unproven." : "Observed human session."}</p>{session.friction.map((friction, i) => <p key={i}>{friction}</p>)}</article>)}</Section><Section title="Build decision" empty={!work.builds.length ? "No independently reviewed build." : undefined}>{work.builds.map(build => <article key={build.id} className="border-b border-gray-border py-3 text-sm"><p>{build.releaseDecision === "local_accepted" ? "Accepted locally" : "Blocked"} · Brief revision {build.briefRevision}</p><p className="break-words text-gray-muted">{build.implementationReference}</p>{build.unresolvedDefects.map((defect, i) => <p key={i} className="text-critical">{defect}</p>)}</article>)}</Section><Section title="What happened after exposure?" empty={!work.outcomes.length ? "No outcome evidence. Retention and value are unknown." : undefined}>{work.outcomes.map(outcome => <article key={outcome.id} className="space-y-2 border-b border-gray-border py-3 text-sm"><p className="font-medium">{outcome.observed ?? "Outcome unknown"}</p><p className="text-gray-muted">{outcome.cohort} · {outcome.exposureCount} exposed · {outcome.evidenceKind}</p><p>Next test: {outcome.nextTest}</p><p className="text-gray-muted">Proposal needs approval before execution.</p></article>)}</Section>{!readOnly && work.options.length && work.claims.length ? <details className="border-b border-gray-border pb-4"><summary className="cursor-pointer text-sm">Record outcome evidence</summary><OutcomeForm work={work} disabled={disabled} submit={command} /></details> : null}</div> : null}
    </> : null}
  </section>;
}

function Section({ title, empty, children }: { title: string; empty?: string; children: ReactNode }) { return <section className="space-y-3"><h2 className="font-display text-xl">{title}</h2>{empty ? <p className="text-sm text-gray-muted">{empty}</p> : children}</section>; }
function ClaimForm({ claim, work, disabled, submit }: { claim: Learning["claims"][number] | null; work: Learning; disabled: boolean; submit: (value: Record<string, unknown>) => Promise<void> }) {
  return <form className="mt-4 space-y-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void submit({ kind: "claim", id: claim?.id ?? newId(), text: entry(data, "text"), certainty: entry(data, "certainty"), evidenceIds: data.getAll("support"), contraryEvidenceIds: data.getAll("contrary"), constraint: entry(data, "constraint"), job: entry(data, "job"), possibleValue: entry(data, "value"), unknowns: lines(data.get("unknowns")) }); }}>
    <TextArea label="Claim" name="text" defaultValue={claim?.text} required maxLength={4000} disabled={disabled} rows={2} />
    <SelectInput label="Evidence strength" name="certainty" defaultValue={claim?.certainty ?? "unknown"} disabled={disabled} options={[{ value: "unknown", label: "Unknown" }, { value: "inferred", label: "Inferred" }, { value: "observed", label: "Observed" }]} />
    <div className="grid gap-4 sm:grid-cols-2"><TextInput label="What prevents the outcome?" name="constraint" defaultValue={claim?.constraint} required disabled={disabled} maxLength={4000} /><TextInput label="What is the person trying to accomplish?" name="job" defaultValue={claim?.job} required disabled={disabled} maxLength={4000} /></div>
    <TextInput label="Potential value" name="value" defaultValue={claim?.possibleValue} required disabled={disabled} maxLength={4000} />
    {work.evidence.length ? <fieldset disabled={disabled} className="space-y-3"><legend className="mb-2 text-sm">Supporting and contrary evidence</legend>{work.evidence.map(evidence => <div key={evidence.id} className="space-y-2 border-b border-gray-border pb-3 text-sm"><p className="line-clamp-3 break-words">{evidence.excerpt}</p><div className="flex flex-wrap gap-4"><label className="flex min-h-10 items-center gap-2"><input type="checkbox" name="support" value={evidence.id} defaultChecked={claim?.evidenceIds.includes(evidence.id)} />Supports</label><label className="flex min-h-10 items-center gap-2"><input type="checkbox" name="contrary" value={evidence.id} defaultChecked={claim?.contraryEvidenceIds.includes(evidence.id)} />Contradicts</label></div></div>)}</fieldset> : null}
    <TextArea label="Unanswered questions, one per line" name="unknowns" defaultValue={claim?.unknowns.join("\n")} maxLength={4000} disabled={disabled} rows={3} />
    <Button type="submit" disabled={disabled}>Save claim</Button>
  </form>;
}
function OutcomeForm({ work, disabled, submit }: { work: Learning; disabled: boolean; submit: (value: Record<string, unknown>) => Promise<void> }) {
  const [kind, setKind] = useState("unknown");
  return <form className="mt-4 space-y-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const unknown = kind === "unknown"; void submit({ kind: "outcome", id: newId(), optionId: entry(data, "option"), claimIds: data.getAll("claim"), expected: entry(data, "expected"), observed: unknown ? null : entry(data, "observed"), cohort: entry(data, "cohort"), windowStart: new Date(entry(data, "start")).toISOString(), windowEnd: new Date(entry(data, "end")).toISOString(), evidenceKind: kind, sourceEventReferences: unknown ? [] : lines(data.get("events")), exposureCount: unknown ? 0 : Number(entry(data, "exposure")), costCents: entry(data, "cost") ? Math.round(Number(entry(data, "cost")) * 100) : null, uncertainty: lines(data.get("uncertainty")), nextTest: entry(data, "next"), effect: entry(data, "effect") }); }}>
    <SelectInput label="Alternative tested" name="option" options={work.options.map(option => ({ value: option.id, label: option.behavior }))} disabled={disabled} />
    <SelectInput label="Evidence" value={kind} onChange={event => setKind(event.target.value)} disabled={disabled} options={[{ value: "unknown", label: "Unknown, no telemetry" }, { value: "observed", label: "Observed real exposure" }, { value: "simulated", label: "Simulation only" }]} />
    <TextInput label="Expected result" name="expected" required maxLength={4000} disabled={disabled} /><TextInput label="Cohort and its limits" name="cohort" required maxLength={4000} disabled={disabled} />
    <div className="grid gap-4 sm:grid-cols-2"><TextInput label="Exposure began" name="start" type="datetime-local" required disabled={disabled} /><TextInput label="Exposure ended" name="end" type="datetime-local" required disabled={disabled} /></div>
    {kind !== "unknown" ? <><TextArea label="What happened?" name="observed" required maxLength={4000} disabled={disabled} /><TextInput label="Number exposed" name="exposure" type="number" min={kind === "observed" ? 1 : 0} required disabled={disabled} /><TextArea label="Source event references, one per line" name="events" required={kind === "observed"} disabled={disabled} maxLength={4000} /></> : null}
    <fieldset disabled={disabled}><legend className="mb-2 text-sm">Claims this result affects</legend>{work.claims.map(claim => <label key={claim.id} className="flex min-h-10 items-center gap-2 text-sm"><input name="claim" value={claim.id} type="checkbox" />{claim.text}</label>)}</fieldset>
    <TextInput label="Observed cost in dollars, leave blank if unknown" name="cost" type="number" min={0} step="0.01" disabled={disabled} /><TextArea label="Uncertainty, one per line" name="uncertainty" maxLength={4000} disabled={disabled} /><TextInput label="What should we test next?" name="next" required maxLength={4000} disabled={disabled} />
    <SelectInput label="How does this affect the idea?" name="effect" disabled={disabled} options={[{ value: "revise", label: "Revisit the claims" }, { value: "retain", label: "Keep investigating" }, { value: "retire", label: "Retire this direction" }]} /><Button type="submit" disabled={disabled}>Save outcome and propose next test</Button>
  </form>;
}
