"use client";
import {useEffect,useRef,useState} from "react";
import {Card} from "@/components/ui/Card";
import {Button} from "@/components/ui/Button";
import {SelectInput,TextArea,TextInput} from "@/components/ui/TextInput";
export interface ReconciliationIssue {account_id:string;event_id:string;reason:string;event_type:string;object_id:string|null;resolution:{id:string;kind:string;note:string}|null;}
export default function ReviewQueue({issues}:{issues:ReconciliationIssue[]}){const [rows,setRows]=useState(issues);return <div className="mt-8 space-y-6">{rows.length?rows.map(i=><Review key={`${i.account_id}:${i.event_id}:${i.reason}`} issue={i} onResolved={r=>setRows(old=>old.map(v=>v===i?{...v,resolution:r}:v))}/>):<Card padding="md"><p>No payment exceptions are awaiting review.</p></Card>}</div>;}
function Review({issue,onResolved}:{issue:ReconciliationIssue;onResolved:(receipt:NonNullable<ReconciliationIssue['resolution']>)=>void}){
 const [kind,setKind]=useState("no_effect_after_review");const [note,setNote]=useState("");const [evidenceKind,setEvidenceKind]=useState("invoice_split");const [evidenceId,setEvidenceId]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 async function resolve(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{const response=await fetch("/api/workspace/money-reconciliation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:issue.account_id,eventId:issue.event_id,reason:issue.reason,kind,note,...(kind==="effect_confirmed"?{evidenceKind,evidenceId}:{})})});const result=await response.json().catch(()=>({}));if(!response.ok||typeof result.id!=="string"||!result.id.match(/^[a-f0-9-]{36}$/))throw Error(result.error??"The review receipt could not be confirmed. Sign in and try again.");if(active.current)onResolved(result);}catch(e){if(active.current)setError(e instanceof Error?e.message:"The review could not be recorded.");}finally{if(active.current)setBusy(false);}}
 return <Card padding="md"><h2 className="font-display text-xl">{issue.reason.replaceAll("_"," ")}</h2><p className="mt-3 break-all text-sm text-gray-muted">{issue.account_id} · {issue.event_type} · {issue.event_id}</p><p className="mt-2 break-all text-sm">Provider object: {issue.object_id??"Unavailable"}</p>{issue.resolution?<div className="mt-4"><p role="status">Review recorded: {issue.resolution.kind.replaceAll("_"," ")}</p><p className="mt-2 whitespace-pre-wrap">{issue.resolution.note}</p></div>:<form onSubmit={resolve} className="mt-6 grid gap-4"><SelectInput label="Result of provider and ledger review" options={[{value:"no_effect_after_review",label:"No financial effect after review"},{value:"effect_confirmed",label:"Existing ledger effect confirmed"}]} value={kind} onChange={e=>setKind(e.target.value)} disabled={busy}/><TextArea label="Evidence and conclusion" required minLength={20} maxLength={5000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/>{kind==="effect_confirmed"?<><SelectInput label="Immutable ledger receipt" options={[{value:"invoice_split",label:"Invoice source receipt"},{value:"business_payment",label:"Customer payment event"},{value:"platform_settlement",label:"Platform settlement"}]} value={evidenceKind} onChange={e=>setEvidenceKind(e.target.value)} disabled={busy}/><TextInput label="Receipt ID" required value={evidenceId} onChange={e=>setEvidenceId(e.target.value)} disabled={busy}/></>:null}<p className="text-sm text-gray-muted">Record the review after checking the provider and ledger. This action creates a receipt; it does not charge, refund, transfer or retry a payment.</p><Button size="lg" type="submit" disabled={busy}>{busy?"Recording…":"Record review"}</Button>{error?<p role="alert">{error}</p>:null}</form>}</Card>;
}
