"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { TextInput } from "@/components/ui/TextInput";
export function WebsiteRebuildSharing({ workId, readOnly }: { workId: string; readOnly: boolean }) {
  const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [link, setLink] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  async function makeLink(action: "share" | "handoff") {
    if (busy || readOnly || !email) return; setBusy(true); setError(""); setLink("");
    try { const response = await fetch(`/api/websites/${encodeURIComponent(workId)}/${action}`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipientEmail: email.trim(), ...(action === "share" ? { expiresInHours: 72 } : {}) }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? "A private review link could not be created."); setLink(new URL(action === "share" ? value.previewHref : `/workspace#handoff=${encodeURIComponent(value.token)}`, window.location.origin).toString()); setExpiresAt(action === "share" ? value.expiresAt : value.handoff.expiresAt); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "The private link could not be created."); } finally { setBusy(false); }
  }
  return <section className="mt-12 max-w-2xl border-t border-gray-border pt-6" aria-labelledby="website-sharing-heading"><h2 id="website-sharing-heading" className="text-2xl font-medium text-warm-black">Share with the business owner</h2><p className="my-4 text-sm leading-6 text-gray-muted">The preview is private and expires after 72 hours. The named recipient signs in to open it. A handoff moves ownership only after they accept. Strelva does not send a message to the prospect.</p><TextInput type="email" label="Owner's email" value={email} onChange={event => setEmail(event.target.value)} disabled={readOnly || busy} maxLength={254} /><div className="mt-4 flex flex-wrap gap-3"><Button disabled={readOnly || busy || !email.trim()} loading={busy} onClick={() => void makeLink("share")}>Create private review link</Button><Button variant="secondary" disabled={readOnly || busy || !email.trim()} onClick={() => void makeLink("handoff")}>Prepare ownership handoff</Button></div>{error ? <p className="mt-4 text-sm text-critical" role="alert">{error}</p> : null}{link ? <div className="mt-4"><TextInput label="Copy this link to share" value={link} readOnly onFocus={event => event.currentTarget.select()} /><p className="mt-2 text-xs text-gray-muted">Expires {new Date(expiresAt).toLocaleString()}. No message was sent.</p></div> : null}</section>;
}
