"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {Button} from '@/components/ui/Button';
import {Card} from '@/components/ui/Card';
import {SelectInput,TextInput} from '@/components/ui/TextInput';
import {neutralCreatorMoneyCommandSchema} from '@/platform/connect/neutral-creator-contract';
export function SourceMoneyConfiguration(props:{actorId:string;request?:typeof fetch}){return <ScopedSourceMoneyConfiguration key={props.actorId} {...props}/>;}
function ScopedSourceMoneyConfiguration({actorId,request=fetch}:{actorId:string;request?:typeof fetch}){
 const [mode,setMode]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');const pending=useRef<z.infer<typeof neutralCreatorMoneyCommandSchema>|null>(null),inflight=useRef<AbortController|null>(null),alive=useRef(true),status=useRef<HTMLParagraphElement|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;inflight.current?.abort();};},[]);
 function focus(origin:Element|null){if(document.activeElement===origin||document.activeElement===document.body)queueMicrotask(()=>{if(alive.current&&(document.activeElement===origin||document.activeElement===document.body))status.current?.focus();});}
 async function submit(event?:FormEvent<HTMLFormElement>){event?.preventDefault();if(inflight.current)return;const origin=document.activeElement;
  if(!pending.current){if(!event)return;const data=new FormData(event.currentTarget),text=(key:string)=>String(data.get(key)??'');try{pending.current=neutralCreatorMoneyCommandSchema.parse({action:mode,sourceRevisionId:text('sourceRevisionId'),version:text('version'),effectiveFrom:new Date(text('effectiveFrom')).toISOString(),effectiveUntil:text('effectiveUntil')?new Date(text('effectiveUntil')).toISOString():null,...(mode==='record_creator_agreement'?{rateReference:text('rateReference'),rateBps:Number(text('rateBps'))}:{amountCents:Number(text('amountCents')),currency:text('currency')})});}catch{setFeedback('Enter the exact written source, references, values and effective dates.');focus(origin);return;}}
  const command=pending.current,controller=new AbortController();inflight.current=controller;setBusy(true);
  try{const response=await request('/api/admin/creator-source-money',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),signal:controller.signal});if(!response.ok)throw Error('The written terms remain unconfirmed. Preserve this exact command before retrying.');const receipt=z.object({action:z.literal(command.action),recordedBy:z.literal(actorId),replayed:z.boolean(),creatorWorkspaceId:z.uuid(),sourceSystemId:z.uuid(),definitionId:z.string().regex(/^system-source:[0-9a-f-]{36}$/),command:neutralCreatorMoneyCommandSchema}).strict().parse(await response.json());if(receipt.definitionId!==`system-source:${receipt.sourceSystemId}`||JSON.stringify(receipt.command)!==JSON.stringify(command))throw Error('The recorded command changed the reviewed written terms.');if(controller.signal.aborted||!alive.current)return;pending.current=null;setFeedback('The exact written terms are recorded for the qualified source creator. No payment or payout was dispatched.');focus(origin);}
  catch(error){if(!controller.signal.aborted&&alive.current){setFeedback(error instanceof Error?error.message:'The written terms remain unconfirmed.');focus(origin);}}
  finally{if(!controller.signal.aborted&&alive.current){inflight.current=null;setBusy(false);}}}
 const locked=busy||!!pending.current;
 return <Card className="mt-8" padding="md"><section aria-labelledby="source-money-configuration-heading" className="space-y-4"><h2 id="source-money-configuration-heading" className="font-medium">Written source creator terms</h2><p>Record already decided terms for an actual qualified source. The source determines its creator; business and agency creators use the same qualification bar. No rate or price is supplied here.</p><SelectInput label="Written source decision" value={mode} disabled={locked} onChange={event=>setMode(event.target.value)} options={[{value:'',label:'Choose the written decision'},{value:'record_creator_agreement',label:'Creator agreement'},{value:'record_source_price',label:'Source price'}]}/>{mode?<form onSubmit={event=>void submit(event)} className="grid gap-4"><TextInput label="Actual qualified source revision" name="sourceRevisionId" required disabled={locked}/><TextInput label="Written version reference" name="version" required maxLength={200} disabled={locked}/>{mode==='record_creator_agreement'?<><TextInput label="Written rate reference" name="rateReference" required maxLength={200} disabled={locked}/><TextInput label="Agreed rate in basis points" name="rateBps" type="number" min={0} max={10000} step={1} required disabled={locked}/></>:<><TextInput label="Agreed price in minor currency units" name="amountCents" type="number" min={1} max={100000000} step={1} required disabled={locked}/><TextInput label="Written currency (three lowercase letters)" name="currency" pattern="[a-z]{3}" required disabled={locked}/></>}<TextInput label="Effective from (your local time)" name="effectiveFrom" type="datetime-local" required disabled={locked}/><TextInput label="Effective until (optional, your local time)" name="effectiveUntil" type="datetime-local" disabled={locked}/><Button type="submit" disabled={locked}>Record written source terms</Button></form>:null}<p role="status" aria-live="polite" tabIndex={-1} ref={status}>{feedback}</p>{pending.current?<><p className="break-all">Unconfirmed source: {pending.current.sourceRevisionId}. Written version: {pending.current.version}. New commands remain locked.</p><Button disabled={busy} variant="secondary" onClick={()=>void submit()}>Retry the identical source terms</Button></>:null}</section></Card>;
}
