"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/Button';
import {Card} from '@/components/ui/Card';
import {SelectInput} from '@/components/ui/TextInput';
import {neutralCreatorListingCommandSchema,neutralCreatorSourcesSchema,type NeutralCreatorSources} from '@/platform/connect/neutral-creator-contract';
import {z} from 'zod';
type Command=z.infer<typeof neutralCreatorListingCommandSchema>;
export function SourceListing(props:{graph:NeutralCreatorSources;actorId:string;request?:typeof fetch}) {return <ScopedSourceListing key={`${props.graph.workspaceId}:${props.actorId}`} {...props}/>;}
function ScopedSourceListing({graph:initial,request=fetch}:{graph:NeutralCreatorSources;actorId:string;request?:typeof fetch}) {
 const [graph,setGraph]=useState(initial),[revision,setRevision]=useState(''),[agreementVersion,setAgreementVersion]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
 const pending=useRef<{command:Command;sourceSystemId:string}|null>(null),inflight=useRef<AbortController|null>(null),alive=useRef(true),status=useRef<HTMLParagraphElement|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;inflight.current?.abort();};},[]);
 function focus(origin:Element|null){if(document.activeElement===origin||document.activeElement===document.body)queueMicrotask(()=>{if(alive.current&&(document.activeElement===origin||document.activeElement===document.body))status.current?.focus();});}
 async function reload(){if(inflight.current)return;const controller=new AbortController(),origin=document.activeElement;inflight.current=controller;setBusy(true);
  try{const response=await request(`/api/workspace/creator-source-money?${new URLSearchParams({workspaceId:initial.workspaceId})}`,{credentials:'same-origin',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('Current creator access could not be confirmed.');const next=neutralCreatorSourcesSchema.parse(await response.json());if(next.workspaceId!==initial.workspaceId||next.sources.some(item=>item.creatorWorkspaceId!==initial.workspaceId||item.definitionId!==`system-source:${item.sourceSystemId}`))throw Error('The listing sources belong to another creator.');const attempt=pending.current,source=attempt?next.sources.find(item=>item.sourceRevisionId===attempt.command.sourceRevisionId):null;if(source?.listingId&&(source.sourceSystemId!==attempt?.sourceSystemId||source.listingAgreementVersion!==attempt?.command.agreementVersion||source.listingRateReference!==attempt?.command.rateReference))throw Error('The existing listing does not match the exact request. Preserve the original source and written terms.');if(controller.signal.aborted||!alive.current)return;setGraph(next);if(source?.listingId){pending.current=null;setFeedback('The exact source listing and written agreement are recorded.');}else setFeedback(attempt?'The original listing remains unconfirmed. Reload again before preparing another.':'Current source listings loaded.');focus(origin);}
  catch(error){if(!controller.signal.aborted&&alive.current){setFeedback(error instanceof Error?error.message:'Listing could not be confirmed.');focus(origin);}}
  finally{if(!controller.signal.aborted&&alive.current){inflight.current=null;setBusy(false);}}}
 async function register(event:FormEvent){event.preventDefault();if(inflight.current||pending.current||!graph.canRegister)return;const source=graph.sources.find(item=>item.sourceRevisionId===revision&&item.qualified&&!item.listingId),agreement=graph.agreements.find(item=>item.version===agreementVersion);if(!source||!agreement)return;const origin=document.activeElement,command=neutralCreatorListingCommandSchema.parse({workspaceId:initial.workspaceId,sourceRevisionId:revision,agreementVersion:agreement.version,rateReference:agreement.rateReference});pending.current={command,sourceSystemId:source.sourceSystemId};const controller=new AbortController();inflight.current=controller;setBusy(true);
  try{const response=await request('/api/workspace/creator-source-money',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),signal:controller.signal});if(!response.ok)throw Error('The listing could not be confirmed. Reload its exact source and agreement.');const receipt=z.object({id:z.uuid(),creatorWorkspaceId:z.literal(command.workspaceId),sourceSystemId:z.literal(source.sourceSystemId),sourceRevisionId:z.literal(command.sourceRevisionId),definitionId:z.literal(source.definitionId),agreementVersion:z.literal(command.agreementVersion),rateReference:z.literal(command.rateReference)}).strict().parse(await response.json());if(controller.signal.aborted||!alive.current)return;setGraph(current=>({...current,sources:current.sources.map(item=>item.sourceRevisionId===revision?{...item,listingId:receipt.id,listingAgreementVersion:receipt.agreementVersion,listingRateReference:receipt.rateReference}:item)}));pending.current=null;setFeedback('The qualified source listing is recorded. Reload current authority before preparing another.');focus(origin);}
  catch(error){if(!controller.signal.aborted&&alive.current){setFeedback(error instanceof Error?error.message:'Listing remains unconfirmed.');focus(origin);}}
  finally{if(!controller.signal.aborted&&alive.current){inflight.current=null;setBusy(false);}}}
 const locked=busy||!!pending.current;
 return <section className="mt-8 space-y-5" aria-labelledby="source-listing-heading"><h2 id="source-listing-heading" className="font-medium">Qualified source listings</h2><p>List an actual published source with its written creator agreement. Customers install their own Version. Listing grants no access to customer records or accounts.</p>{graph.canRegister?<Card padding="md"><form className="grid gap-4" onSubmit={event=>void register(event)}><SelectInput label="Qualified source revision" value={revision} disabled={locked} required onChange={event=>setRevision(event.target.value)} options={[{value:'',label:'Choose a qualified published source'},...graph.sources.filter(item=>item.qualified&&!item.listingId).map(item=>({value:item.sourceRevisionId,label:`${item.name} · revision ${item.revision}`}))]}/><SelectInput label="Written creator agreement" value={agreementVersion} disabled={locked} required onChange={event=>setAgreementVersion(event.target.value)} options={[{value:'',label:'Choose a recorded agreement'},...graph.agreements.map(item=>({value:item.version,label:`${item.version} · ${item.rateReference} · ${item.rateBps} basis points`}))]}/><Button type="submit" disabled={locked||!revision||!agreementVersion}>Record this source listing</Button></form></Card>:<p>Future source listings are unavailable. Recorded listings remain visible.</p>}<p role="status" tabIndex={-1} ref={status} aria-live="polite">{feedback}</p><Button variant="secondary" disabled={busy} onClick={()=>void reload()}>Reload source listings</Button>{pending.current?<p className="break-all">Unconfirmed source: {pending.current.command.sourceRevisionId}. New listing requests stay locked.</p>:null}<ul>{graph.sources.filter(item=>item.listingId).map(item=><li className="break-words" key={item.sourceRevisionId}>{item.name} · revision {item.revision} · agreement {item.listingAgreementVersion} · {item.listingRateReference}</li>)}</ul></section>;
}
