create table public.platform_collection_prices(version text primary key,amount_cents bigint not null check(amount_cents>0),currency text not null check(currency ~ '^[a-z]{3}$'),definition_id text,effective_from timestamptz not null,effective_until timestamptz,approved_by uuid not null references public.users(id),approved_at timestamptz not null,check(effective_until is null or effective_until>effective_from));
alter table public.platform_collection_prices enable row level security;revoke all on public.platform_collection_prices from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.platform_collection_prices for each row execute function public.money_immutable_guard();
-- No priced collection terms are supplied by a generic percentage agreement.
-- Each platform invoice line needs an explicit owner acceptance first.
create table public.platform_collection_terms(line_id text primary key,business_workspace_id uuid not null references public.workspaces(id),amount_cents bigint not null check(amount_cents>0),currency text not null check(currency ~ '^[a-z]{3}$'),customer_id text not null,agreement_version text not null,installation_id uuid references public.offering_installations(id),accepted_by uuid not null references public.users(id),accepted_at timestamptz not null default now());
alter table public.platform_collection_terms enable row level security;revoke all on public.platform_collection_terms from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.platform_collection_terms for each row execute function public.money_immutable_guard();
create function public.accept_platform_collection_terms(p_business_id uuid,p_user_id uuid,p_verified_email text,p_line_id text,p_amount bigint,p_currency text,p_customer_id text,p_agreement text,p_installation_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare r public.platform_collection_terms%rowtype;begin
 perform public.connect_assert_manager(p_business_id,p_user_id,p_verified_email);
 if not exists(select 1 from public.workspace_memberships where workspace_id=p_business_id and user_id=p_user_id and role='owner') then raise exception 'collection_owner_required';end if;
 if not exists(select 1 from public.accounts where workspace_id=p_business_id and stripe_customer_id=p_customer_id) then raise exception 'platform_collection_payer_mismatch';end if;
 if not exists(select 1 from public.platform_collection_prices p join public.super_admins o on o.user_id=p.approved_by and o.revoked_at is null join public.users u on u.id=p.approved_by and u.verified_at is not null where p.version=p_agreement and p.amount_cents=p_amount and p.currency=p_currency and p.effective_from<=now() and (p.effective_until is null or p.effective_until>now()) and (p.definition_id is null or exists(select 1 from public.offering_installations where id=p_installation_id and business_workspace_id=p_business_id and definition_id=p.definition_id and status='active'))) then raise exception 'approved_platform_price_required';end if;
 if length(p_line_id) not between 1 and 200 or length(p_agreement)<1 then raise exception 'collection_terms_invalid';end if;
 if p_installation_id is not null and not exists(select 1 from public.offering_installations where id=p_installation_id and business_workspace_id=p_business_id and status='active') then raise exception 'collection_installation_invalid';end if;
 insert into public.platform_collection_terms values(p_line_id,p_business_id,p_amount,p_currency,p_customer_id,p_agreement,p_installation_id,p_user_id,now()) on conflict do nothing;
 select * into r from public.platform_collection_terms where line_id=p_line_id;
 if r.business_workspace_id<>p_business_id or r.amount_cents<>p_amount or r.currency<>p_currency or r.customer_id<>p_customer_id or r.agreement_version<>p_agreement or r.installation_id is distinct from p_installation_id then raise exception 'collection_terms_conflict';end if;return to_jsonb(r);end;$$;
create function public.collection_terms_guard() returns trigger language plpgsql set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.platform_collection_terms t where t.line_id=new.invoice_line_id and t.business_workspace_id=new.business_workspace_id and t.amount_cents=new.amount_cents and t.currency=new.currency and t.customer_id=new.customer_id and t.agreement_version=new.agreement_version and t.installation_id is not distinct from new.installation_id) then raise exception 'accepted_collection_terms_required';end if;return new;end;$$;
create trigger collection_terms_guard before insert on public.platform_collections for each row execute function public.collection_terms_guard();
-- The source net is retrieved from Stripe's actual balance transaction. Every
-- reserved split consumes that source once across concurrent/repeated cron runs.
create function public.reserve_split_payout_dry_run(p_split_id uuid,p_recipient text,p_charge text,p_amount bigint,p_currency text,p_agreement text,p_available bigint) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare s public.revenue_splits%rowtype;r public.split_payouts%rowtype;remaining bigint;spent bigint;begin
 select * into s from public.revenue_splits where id=p_split_id and original_split_id is null;
 if s.id is null or s.source_account_id<>'platform' or s.source_charge_id<>p_charge or s.currency<>p_currency or s.agreement_version is distinct from p_agreement then raise exception 'payout_source_mismatch';end if;
 perform pg_advisory_xact_lock(hashtextextended('platform:'||p_charge,8814));
 if not exists(select 1 from public.connected_accounts c where c.workspace_id=s.beneficiary_workspace_id and c.stripe_account_id=p_recipient and c.state='ready' and 'recipient'=any(c.configurations) and c.capabilities#>>'{recipient,capabilities,stripe_balance,stripe_transfers,status}'='active') then raise exception 'payout_recipient_unavailable';end if;
 select s.amount_cents+coalesce(sum(amount_cents),0) into remaining from public.revenue_splits where original_split_id=s.id;
 if p_amount<>remaining or p_amount<=0 then raise exception 'payout_accrual_changed';end if;
 select * into r from public.split_payouts where split_id=s.id;
 if found then if r.amount_cents<>p_amount or r.recipient_account_id<>p_recipient or r.currency<>p_currency or r.agreement_version<>p_agreement then raise exception 'payout_reservation_changed';end if;return to_jsonb(r);end if;
 select coalesce(sum(amount_cents),0) into spent from public.split_payouts where source_account_id='platform' and source_transaction=p_charge;
 if spent+p_amount>p_available then raise exception 'payout_source_balance_reserved';end if;
 insert into public.split_payouts(split_id,recipient_account_id,source_account_id,source_transaction,amount_cents,currency,agreement_version) values(s.id,p_recipient,'platform',p_charge,p_amount,p_currency,p_agreement) returning * into r;return to_jsonb(r);end;$$;
-- Readers authenticate without taking locks, so retained history remains usable
-- inside a real READ ONLY transaction and after an owner exits future work.
create function public.connect_assert_reader(p_workspace_id uuid,p_user_id uuid,p_verified_email text) returns void language plpgsql stable security definer set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.users u join public.workspace_memberships m on m.user_id=u.id where u.id=p_user_id and lower(u.email)=lower(btrim(p_verified_email)) and u.verified_at is not null and m.workspace_id=p_workspace_id and m.role in('owner','admin')) then raise exception 'connect_denied';end if;end;$$;
DO $$declare definition text;begin select pg_get_functiondef('public.read_business_money(uuid,uuid,text)'::regprocedure) into definition;definition:=replace(definition,'public.connect_assert_manager(','public.connect_assert_reader(');execute definition;end;$$;
-- Only the latest accepted payer, still authorized on both sides, can be linked.
create function public.assert_current_provider_payer(p_business uuid,p_transition uuid,p_agency uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare t public.workspace_payer_transitions%rowtype;begin
 select * into t from public.workspace_payer_transitions where id=p_transition and workspace_id=p_business and status='accepted' for share;
 if t.id is null or t.id is distinct from (select id from public.workspace_payer_transitions where workspace_id=p_business and status='accepted' order by accepted_at desc,id desc limit 1) or (p_agency is null and t.successor_kind<>'business') or (p_agency is not null and (t.successor_kind<>'agency' or t.successor_workspace_id<>p_agency)) then raise exception 'provider_payer_transition_mismatch';end if;
 perform 1 from public.workspace_memberships m join public.users u on u.id=m.user_id and u.verified_at is not null where m.workspace_id=p_business and m.user_id=t.proposed_by and m.role='owner' for share of m,u; if not found then raise exception 'provider_payer_proposer_authority_lost';end if;
 perform 1 from public.workspace_memberships m join public.users u on u.id=m.user_id and u.verified_at is not null where m.workspace_id=coalesce(p_agency,p_business) and m.user_id=t.resolved_by and (case when p_agency is null then m.role='owner' else m.role in('owner','admin') end) for share of m,u; if not found then raise exception 'provider_payer_successor_authority_lost';end if;
end;$$;
DO $$declare definition text;begin
 select pg_get_functiondef('public.request_provider_change(uuid,uuid,text,uuid,text,uuid)'::regprocedure) into definition;
 definition:=replace(definition,'if p_payer_transition_id is not null then','if exists(select 1 from public.provider_change_requests where business_workspace_id=p_workspace_id and idempotency_key=p_key and payer_transition_id is distinct from p_payer_transition_id) then raise exception ''provider_payer_transition_conflict'';end if; if p_payer_transition_id is not null then perform public.assert_current_provider_payer(p_workspace_id,p_payer_transition_id,p_new_agency_id);');execute definition;
 select pg_get_functiondef('public.complete_provider_change(uuid,uuid,text)'::regprocedure) into definition;
 definition:=replace(definition,'if q.payer_transition_id is not null and','if q.payer_transition_id is not null then perform public.assert_current_provider_payer(q.business_workspace_id,q.payer_transition_id,q.new_agency_workspace_id);end if; if q.payer_transition_id is not null and');execute definition;end;$$;
DO $$declare f record;begin for f in select p.oid::regprocedure as name from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('accept_platform_collection_terms','reserve_split_payout_dry_run','connect_assert_reader','assert_current_provider_payer') loop execute format('revoke all on function %s from public,anon,authenticated',f.name);execute format('grant execute on function %s to service_role',f.name);end loop;end $$;
create table public.platform_collection_periods(line_id text primary key references public.platform_collection_terms(line_id),period_start timestamptz not null,period_end timestamptz not null check(period_end>period_start));
create table public.platform_collection_settlements(collection_id uuid primary key references public.platform_collections(id),payment_intent_id text not null unique,charge_id text not null unique,amount_cents bigint not null,currency text not null,event_id text not null,created_at timestamptz not null default now());
DO $$declare t text;begin foreach t in array array['platform_collection_periods','platform_collection_settlements'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);execute format('create trigger money_immutable before update or delete on public.%I for each row execute function public.money_immutable_guard()',t);end loop;end $$;
create function public.freeze_platform_collection_period(p_line_id text,p_user_id uuid,p_verified_email text,p_start timestamptz,p_end timestamptz) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare t public.platform_collection_terms%rowtype;begin
 select * into t from public.platform_collection_terms where line_id=p_line_id;perform public.connect_assert_manager(t.business_workspace_id,p_user_id,p_verified_email);
 if t.accepted_by<>p_user_id then raise exception 'collection_owner_required';end if;
 insert into public.platform_collection_periods values(p_line_id,p_start,p_end) on conflict do nothing;
 if not exists(select 1 from public.platform_collection_periods where line_id=p_line_id and period_start=p_start and period_end=p_end) then raise exception 'collection_period_conflict';end if;end;$$;
create function public.record_platform_collection_settlement(p_id uuid,p_intent text,p_charge text,p_amount bigint,p_currency text,p_customer text,p_event text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare c public.platform_collections%rowtype;r public.platform_collection_settlements%rowtype;period public.platform_collection_periods%rowtype;begin
 select * into c from public.platform_collections where id=p_id for update;
 if c.id is null or c.amount_cents<>p_amount or c.currency<>p_currency or c.customer_id<>p_customer or p_intent !~ '^pi_[A-Za-z0-9]+$' or p_charge !~ '^ch_[A-Za-z0-9]+$' then raise exception 'collection_settlement_mismatch';end if;
 select * into period from public.platform_collection_periods where line_id=c.invoice_line_id;if not found then raise exception 'accepted_collection_period_required';end if;
 insert into public.platform_collection_settlements values(c.id,p_intent,p_charge,p_amount,p_currency,p_event,now()) on conflict do nothing;
 select * into r from public.platform_collection_settlements where collection_id=c.id;
 if r.payment_intent_id<>p_intent or r.charge_id<>p_charge or r.amount_cents<>p_amount or r.currency<>p_currency then raise exception 'collection_settlement_conflict';end if;
 perform public.accrue_invoice_splits(c.business_workspace_id,c.invoice_line_id,period.period_start,period.period_end,'platform',p_charge,p_amount,p_currency,c.installation_id,null);return to_jsonb(r);end;$$;
revoke all on function public.freeze_platform_collection_period(text,uuid,text,timestamptz,timestamptz),public.record_platform_collection_settlement(uuid,text,text,bigint,text,text,text) from public,anon,authenticated;grant execute on function public.freeze_platform_collection_period(text,uuid,text,timestamptz,timestamptz),public.record_platform_collection_settlement(uuid,text,text,bigint,text,text,text) to service_role;
create function public.read_business_payment_sources(p_workspace_id uuid,p_user_id uuid,p_verified_email text) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$declare sources jsonb;requests jsonb;begin
 perform public.connect_assert_reader(p_workspace_id,p_user_id,p_verified_email);
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into sources from (select id as source_id,'quote'::text as kind,'Inquiry · '||to_char(captured_at,'YYYY-MM-DD') as label from public.tenant_leads l where workspace_id=p_workspace_id and not exists(select 1 from public.business_payment_requests q where q.workspace_id=p_workspace_id and q.kind='quote' and q.source_record_id=l.id) union all select id,'deposit','Booking · '||to_char(start_at,'YYYY-MM-DD HH24:MI') from public.business_bookings b where workspace_id=p_workspace_id and status='held' and not exists(select 1 from public.business_payment_requests q where q.workspace_id=p_workspace_id and q.kind='deposit' and q.source_record_id=b.id)) x;
 select coalesce(jsonb_agg((to_jsonb(q)-'token_hash')||jsonb_build_object('status',public.read_public_payment_request(q.token_hash)->>'status','refundRequired',exists(select 1 from public.payment_request_actions a where a.request_id=q.id and a.action='refund_required'))),'[]') into requests from public.business_payment_requests q where workspace_id=p_workspace_id;
 return jsonb_build_object('sources',sources,'requests',requests);end;$$;
revoke all on function public.read_business_payment_sources(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.read_business_payment_sources(uuid,uuid,text) to service_role;
-- Expired unpaid holds release capacity; a late success remains a refund-review
-- receipt and cannot turn that expired booking into a confirmation.
create function public.expire_business_payment_holds(p_limit integer default 100) returns integer language plpgsql security definer set search_path=public,pg_temp as $$declare q record;n integer=0;begin
 for q in select r.id,r.source_record_id,r.workspace_id from public.business_payment_requests r join public.business_bookings b on b.id=r.source_record_id and b.workspace_id=r.workspace_id where r.kind='deposit' and r.expires_at<=now() and b.status='held' order by r.expires_at limit least(greatest(p_limit,1),100) for update of b skip locked loop
 update public.business_bookings set status='cancelled' where id=q.source_record_id and workspace_id=q.workspace_id;
 insert into public.payment_request_actions(request_id,action) values(q.id,'expired') on conflict do nothing;n:=n+1;end loop;return n;end;$$;
revoke all on function public.expire_business_payment_holds(integer) from public,anon,authenticated;grant execute on function public.expire_business_payment_holds(integer) to service_role;
create function public.verify_invoice_split_source(p_business uuid,p_account text,p_customer text,p_subscription text) returns boolean language plpgsql stable security definer set search_path=public,pg_temp as $$declare allowed boolean=false;begin
 if p_account='platform' then return exists(select 1 from public.accounts a where a.workspace_id=p_business and a.stripe_customer_id=p_customer);
 end if;
 if to_regclass('public.agency_billing_intents') is null then return false;end if;
 -- This is the immutable accepted retail intent's provider identity, not invoice
 -- metadata or current agency membership. Old invoices retain their exact source.
 execute 'select exists(select 1 from public.agency_billing_intents i join public.connected_accounts c on c.workspace_id=i.agency_workspace_id and c.stripe_account_id=$2 where i.business_workspace_id=$1 and i.accepted_at is not null and i.provider_account_id=$2 and i.provider_object_id=$3 and i.kind=''rebill'')' into allowed using p_business,p_account,p_subscription;
 return allowed;end;$$;
revoke all on function public.verify_invoice_split_source(uuid,text,text,text) from public,anon,authenticated;grant execute on function public.verify_invoice_split_source(uuid,text,text,text) to service_role;
create table public.business_payment_provider_bindings(payment_id uuid primary key references public.business_payments(id),account_id text not null,provider_id text not null,checkout_id text,unique(account_id,provider_id));
alter table public.business_payment_provider_bindings enable row level security;revoke all on public.business_payment_provider_bindings from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.business_payment_provider_bindings for each row execute function public.money_immutable_guard();
create function public.bind_business_payment_provider(p_payment_id uuid,p_account text,p_provider text,p_currency text,p_checkout text default null) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p public.business_payments%rowtype;c text;begin
 select * into p from public.business_payments where id=p_payment_id for update;
 select channel into c from public.business_payment_channels where payment_id=p_payment_id;
 if p.id is null or p.merchant_account_id<>p_account or p.currency<>p_currency or p_provider !~ '^pi_[A-Za-z0-9]+$' or c is null then raise exception 'payment_provider_binding_mismatch';end if;
 if c='checkout' and not exists(select 1 from public.business_payment_events where payment_id=p.id and merchant_account_id=p_account and kind='checkout_created' and provider_object_id=p_checkout) then raise exception 'payment_checkout_binding_required';end if;
 insert into public.business_payment_provider_bindings values(p.id,p_account,p_provider,p_checkout) on conflict do nothing;
 if not exists(select 1 from public.business_payment_provider_bindings where payment_id=p.id and account_id=p_account and provider_id=p_provider) then raise exception 'payment_provider_binding_conflict';end if;end;$$;
alter function public.record_business_payment_event(text,text,text,uuid,text,bigint) rename to record_business_payment_event_before_currency;
revoke all on function public.record_business_payment_event_before_currency(text,text,text,uuid,text,bigint) from public,anon,authenticated,service_role;
create function public.record_business_payment_event(p_account_id text,p_event_id text,p_object_id text,p_payment_id uuid,p_kind text,p_amount bigint,p_currency text default null,p_source_intent text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.business_payments where id=p_payment_id and merchant_account_id=p_account_id) then raise exception 'payment_account_mismatch';end if;
 if p_kind in('refund','dispute','dispute_won') and not exists(select 1 from public.business_payments p join public.business_payment_provider_bindings b on b.payment_id=p.id where p.id=p_payment_id and p.currency=p_currency and b.account_id=p_account_id and b.provider_id=p_source_intent) then raise exception 'payment_adjustment_source_mismatch';end if;
 if p_kind='paid' and not exists(select 1 from public.business_payments p join public.business_payment_provider_bindings b on b.payment_id=p.id where p.id=p_payment_id and p.currency=p_currency and b.account_id=p_account_id and b.provider_id=p_object_id) then raise exception 'payment_currency_or_provider_mismatch';end if;
 return public.record_business_payment_event_before_currency(p_account_id,p_event_id,p_object_id,p_payment_id,p_kind,p_amount);end;$$;
revoke all on function public.bind_business_payment_provider(uuid,text,text,text,text),public.record_business_payment_event(text,text,text,uuid,text,bigint,text,text) from public,anon,authenticated;grant execute on function public.bind_business_payment_provider(uuid,text,text,text,text),public.record_business_payment_event(text,text,text,uuid,text,bigint,text,text) to service_role;
-- Provider loss is retained even when its invoice has not arrived. Every replay
-- has an exact immutable input; subsequent accrual reapplies the latest snapshot.
create table public.split_loss_receipts(source_account_id text not null,charge_id text not null,event_key text not null,loss_cents bigint not null,charge_basis bigint not null,created_at timestamptz not null default clock_timestamp(),primary key(source_account_id,charge_id,event_key));
alter table public.split_loss_receipts enable row level security;revoke all on public.split_loss_receipts from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.split_loss_receipts for each row execute function public.money_immutable_guard();
alter function public.reconcile_split_loss(text,text,text,bigint,bigint) rename to reconcile_split_loss_before_receipt;
revoke all on function public.reconcile_split_loss_before_receipt(text,text,text,bigint,bigint) from public,anon,authenticated,service_role;
create function public.reconcile_split_loss(p_source_account text,p_charge_id text,p_event_key text,p_cumulative_loss bigint,p_charge_basis bigint) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare r public.split_loss_receipts%rowtype;begin
 perform pg_advisory_xact_lock(hashtextextended(p_source_account||':'||p_charge_id,8811));
 if p_charge_basis<=0 or p_cumulative_loss<0 or p_cumulative_loss>p_charge_basis then raise exception 'split_reversal_invalid';end if;
 insert into public.split_loss_receipts values(p_source_account,p_charge_id,p_event_key,p_cumulative_loss,p_charge_basis,clock_timestamp()) on conflict do nothing;
 select * into r from public.split_loss_receipts where source_account_id=p_source_account and charge_id=p_charge_id and event_key=p_event_key;
 if r.loss_cents<>p_cumulative_loss or r.charge_basis<>p_charge_basis then raise exception 'split_loss_receipt_conflict';end if;
 return public.reconcile_split_loss_before_receipt(p_source_account,p_charge_id,p_event_key,p_cumulative_loss,p_charge_basis);end;$$;
alter function public.accrue_invoice_splits(uuid,text,timestamptz,timestamptz,text,text,bigint,text,uuid,uuid) rename to accrue_invoice_splits_before_loss;
revoke all on function public.accrue_invoice_splits_before_loss(uuid,text,timestamptz,timestamptz,text,text,bigint,text,uuid,uuid) from public,anon,authenticated,service_role;
create function public.accrue_invoice_splits(p_business_id uuid,p_line_id text,p_period_start timestamptz,p_period_end timestamptz,p_source_account text,p_charge_id text,p_basis bigint,p_currency text,p_installation_id uuid default null,p_source_revision_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare result jsonb;r public.split_loss_receipts%rowtype;begin
 perform pg_advisory_xact_lock(hashtextextended(p_source_account||':'||p_charge_id,8811));
 result:=public.accrue_invoice_splits_before_loss(p_business_id,p_line_id,p_period_start,p_period_end,p_source_account,p_charge_id,p_basis,p_currency,p_installation_id,p_source_revision_id);
 select * into r from public.split_loss_receipts where source_account_id=p_source_account and charge_id=p_charge_id order by created_at desc,event_key desc limit 1;
 if found then perform public.reconcile_split_loss_before_receipt(p_source_account,p_charge_id,r.event_key,r.loss_cents,r.charge_basis);end if;return result;end;$$;
revoke all on function public.reconcile_split_loss(text,text,text,bigint,bigint),public.accrue_invoice_splits(uuid,text,timestamptz,timestamptz,text,text,bigint,text,uuid,uuid) from public,anon,authenticated;grant execute on function public.reconcile_split_loss(text,text,text,bigint,bigint),public.accrue_invoice_splits(uuid,text,timestamptz,timestamptz,text,text,bigint,text,uuid,uuid) to service_role;
create table public.business_payment_attempts(payment_id uuid primary key references public.business_payments(id),started_at timestamptz not null default clock_timestamp());
alter table public.business_payment_attempts enable row level security;revoke all on public.business_payment_attempts from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.business_payment_attempts for each row execute function public.money_immutable_guard();
create function public.prepare_business_checkout(p_payment_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare session_id text;started timestamptz;begin
 perform 1 from public.business_payments where id=p_payment_id for update;if not found then raise exception 'payment_not_found';end if;
 select provider_object_id into session_id from public.business_payment_events where payment_id=p_payment_id and kind='checkout_created' order by created_at limit 1;
 if session_id is not null then return jsonb_build_object('sessionId',session_id);end if;
 select started_at into started from public.business_payment_attempts where payment_id=p_payment_id;
 if started is not null and started<clock_timestamp()-interval '23 hours' then raise exception 'payment_attempt_requires_reconciliation';end if;
 insert into public.business_payment_attempts(payment_id) values(p_payment_id) on conflict do nothing;return '{}';end;$$;
create function public.read_business_payment_provider(p_payment_id uuid,p_account text) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select to_jsonb(b) from public.business_payment_provider_bindings b where payment_id=p_payment_id and account_id=p_account;$$;
revoke all on function public.prepare_business_checkout(uuid),public.read_business_payment_provider(uuid,text) from public,anon,authenticated;grant execute on function public.prepare_business_checkout(uuid),public.read_business_payment_provider(uuid,text) to service_role;
-- Serialize provider observations across workers. A timed-out older fetch cannot
-- overwrite a newer generation's source state after its lease is superseded.
create table public.split_reconciliation_leases(source_account text not null,charge_id text not null,generation bigint not null,expires_at timestamptz not null,primary key(source_account,charge_id));
alter table public.split_reconciliation_leases enable row level security;revoke all on public.split_reconciliation_leases from public,anon,authenticated,service_role;
create function public.acquire_split_reconciliation(p_account text,p_charge text) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$declare r public.split_reconciliation_leases%rowtype;begin
 perform pg_advisory_xact_lock(hashtextextended(p_account||':'||p_charge,8811));
 select * into r from public.split_reconciliation_leases where source_account=p_account and charge_id=p_charge for update;
 if found and r.expires_at>clock_timestamp() then raise exception 'split_reconciliation_busy';end if;
 insert into public.split_reconciliation_leases values(p_account,p_charge,1,clock_timestamp()+interval '1 minute') on conflict(source_account,charge_id) do update set generation=split_reconciliation_leases.generation+1,expires_at=excluded.expires_at returning * into r;return r.generation;end;$$;
create function public.finish_split_reconciliation(p_account text,p_charge text,p_generation bigint,p_snapshot text,p_loss bigint,p_basis bigint) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare result jsonb;begin
 perform 1 from public.split_reconciliation_leases where source_account=p_account and charge_id=p_charge and generation=p_generation and expires_at>clock_timestamp() for update;if not found then raise exception 'split_reconciliation_stale';end if;
 result:=public.reconcile_split_loss(p_account,p_charge,p_snapshot,p_loss,p_basis);
 update public.split_reconciliation_leases set expires_at=clock_timestamp() where source_account=p_account and charge_id=p_charge and generation=p_generation;return result;end;$$;
revoke all on function public.acquire_split_reconciliation(text,text),public.finish_split_reconciliation(text,text,bigint,text,bigint,bigint) from public,anon,authenticated;grant execute on function public.acquire_split_reconciliation(text,text),public.finish_split_reconciliation(text,text,bigint,text,bigint,bigint) to service_role;
-- Intentionally empty: Jacob's first live payout authorization is not inferred.
create table public.split_payout_authorizations(payout_id uuid primary key references public.split_payouts(id),approved_by uuid not null references public.users(id),approved_at timestamptz not null,profile_version text not null);
create table public.split_transfer_attempts(payout_id uuid primary key references public.split_payouts(id),started_at timestamptz not null default clock_timestamp());
create table public.split_transfer_receipts(payout_id uuid primary key references public.split_payouts(id),transfer_id text not null unique,amount_cents bigint not null,currency text not null,created_at timestamptz not null default now());
create table public.split_transfer_reversals(id uuid primary key default gen_random_uuid(),payout_id uuid not null references public.split_payouts(id),loss_event text not null,amount_cents bigint not null check(amount_cents>0),started_at timestamptz not null default clock_timestamp(),unique(payout_id,loss_event));
create table public.split_transfer_reversal_receipts(reversal_request_id uuid primary key references public.split_transfer_reversals(id),reversal_id text not null unique,amount_cents bigint not null,created_at timestamptz not null default now());
DO $$declare t text;begin foreach t in array array['split_payout_authorizations','split_transfer_attempts','split_transfer_receipts','split_transfer_reversals','split_transfer_reversal_receipts'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);execute format('create trigger money_immutable before update or delete on public.%I for each row execute function public.money_immutable_guard()',t);end loop;end $$;
create function public.prepare_approved_split_transfer(p_payout_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p public.split_payouts%rowtype;r public.split_transfer_receipts%rowtype;started timestamptz;remaining bigint;begin
 select * into p from public.split_payouts where id=p_payout_id for update;
 if p.id is null or p.source_account_id<>'platform' or not exists(select 1 from public.split_payout_authorizations a join public.super_admins o on o.user_id=a.approved_by and o.revoked_at is null join public.users u on u.id=a.approved_by and u.verified_at is not null join public.connected_accounts c on c.stripe_account_id=p.recipient_account_id where a.payout_id=p.id and a.profile_version=c.profile_version and c.state='ready') then raise exception 'payout_operator_authorization_required';end if;
 select * into r from public.split_transfer_receipts where payout_id=p.id;if found then return to_jsonb(p)||jsonb_build_object('transfer_id',r.transfer_id);end if;
 select s.amount_cents+coalesce((select sum(amount_cents) from public.revenue_splits where original_split_id=s.id),0) into remaining from public.revenue_splits s where id=p.split_id;
 if remaining<>p.amount_cents then raise exception 'payout_accrual_changed';end if;
 select started_at into started from public.split_transfer_attempts where payout_id=p.id;
 if started is not null and started<clock_timestamp()-interval '23 hours' then raise exception 'payout_attempt_requires_reconciliation';end if;
 insert into public.split_transfer_attempts(payout_id) values(p.id) on conflict do nothing;return to_jsonb(p);end;$$;
create function public.record_split_transfer(p_payout_id uuid,p_transfer_id text,p_amount bigint,p_currency text) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.split_payouts p join public.split_transfer_attempts a on a.payout_id=p.id where p.id=p_payout_id and p.amount_cents=p_amount and p.currency=p_currency) or p_transfer_id !~ '^tr_[A-Za-z0-9]+$' then raise exception 'payout_transfer_mismatch';end if;
 insert into public.split_transfer_receipts(payout_id,transfer_id,amount_cents,currency) values(p_payout_id,p_transfer_id,p_amount,p_currency) on conflict do nothing;
 if not exists(select 1 from public.split_transfer_receipts where payout_id=p_payout_id and transfer_id=p_transfer_id and amount_cents=p_amount and currency=p_currency) then raise exception 'payout_transfer_conflict';end if;end;$$;
create function public.prepare_split_transfer_reversal(p_payout_id uuid,p_loss_event text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p public.split_payouts%rowtype;t public.split_transfer_receipts%rowtype;r public.split_transfer_reversals%rowtype;loss bigint;reserved bigint;begin
 select * into p from public.split_payouts where id=p_payout_id for update;select * into t from public.split_transfer_receipts where payout_id=p.id;
 if t.payout_id is null then raise exception 'payout_transfer_required';end if;
 select * into r from public.split_transfer_reversals where payout_id=p.id and loss_event=p_loss_event;
 if r.id is null then
 if not exists(select 1 from public.revenue_splits where original_split_id=p.split_id and event_key=p_loss_event and amount_cents<0) then raise exception 'payout_loss_source_required';end if;
 select -coalesce(sum(amount_cents),0) into loss from public.revenue_splits where original_split_id=p.split_id;
 select coalesce(sum(amount_cents),0) into reserved from public.split_transfer_reversals where payout_id=p.id;
 loss:=greatest(0,loss-((select amount_cents from public.revenue_splits where id=p.split_id)-p.amount_cents));if loss<=reserved then raise exception 'payout_no_new_loss';end if;
 insert into public.split_transfer_reversals(payout_id,loss_event,amount_cents) values(p.id,p_loss_event,least(loss,t.amount_cents)-reserved) returning * into r;end if;
 if not exists(select 1 from public.split_transfer_reversal_receipts where reversal_request_id=r.id) and r.started_at<clock_timestamp()-interval '23 hours' then raise exception 'payout_reversal_requires_reconciliation';end if;
 return to_jsonb(r)||jsonb_build_object('transfer_id',t.transfer_id,'reversal_id',(select reversal_id from public.split_transfer_reversal_receipts where reversal_request_id=r.id));end;$$;
create function public.record_split_transfer_reversal(p_id uuid,p_reversal_id text,p_amount bigint) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 if p_reversal_id !~ '^trr_[A-Za-z0-9]+$' or not exists(select 1 from public.split_transfer_reversals where id=p_id and amount_cents=p_amount) then raise exception 'payout_reversal_mismatch';end if;
 insert into public.split_transfer_reversal_receipts(reversal_request_id,reversal_id,amount_cents) values(p_id,p_reversal_id,p_amount) on conflict do nothing;
 if not exists(select 1 from public.split_transfer_reversal_receipts where reversal_request_id=p_id and reversal_id=p_reversal_id and amount_cents=p_amount) then raise exception 'payout_reversal_conflict';end if;end;$$;
DO $$declare f record;begin for f in select p.oid::regprocedure as name from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('prepare_approved_split_transfer','record_split_transfer','prepare_split_transfer_reversal','record_split_transfer_reversal') loop execute format('revoke all on function %s from public,anon,authenticated',f.name);execute format('grant execute on function %s to service_role',f.name);end loop;end $$;
alter table public.payment_request_actions drop constraint payment_request_actions_action_check;
alter table public.payment_request_actions add constraint payment_request_actions_action_check check(action in('accepted','cancelled','refund_required','expired','followed_up'));
create function public.acknowledge_payment_follow_up(p_workspace_id uuid,p_user_id uuid,p_verified_email text,p_request_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 perform public.connect_assert_manager(p_workspace_id,p_user_id,p_verified_email);
 if not exists(select 1 from public.workspace_memberships where workspace_id=p_workspace_id and user_id=p_user_id and role='owner') or not exists(select 1 from public.business_payment_requests where id=p_request_id and workspace_id=p_workspace_id) then raise exception 'payment_follow_up_denied';end if;
 insert into public.payment_request_actions(request_id,action) values(p_request_id,'followed_up') on conflict do nothing;end;$$;
create function public.read_payment_follow_ups(p_workspace_id uuid,p_user_id uuid,p_verified_email text) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$begin
 perform public.connect_assert_reader(p_workspace_id,p_user_id,p_verified_email);
 return coalesce((select jsonb_agg(jsonb_build_object('id',q.id,'kind',q.kind,'issuedAt',q.issued_at,'amountCents',q.amount_cents,'currency',q.currency,'status',public.read_public_payment_request(q.token_hash)->>'status','refundRequired',exists(select 1 from public.payment_request_actions where request_id=q.id and action='refund_required'))) from public.business_payment_requests q where workspace_id=p_workspace_id and not exists(select 1 from public.payment_request_actions where request_id=q.id and action='followed_up') and ((public.read_public_payment_request(q.token_hash)->>'status')='unpaid' or exists(select 1 from public.payment_request_actions where request_id=q.id and action='refund_required'))),'[]');end;$$;
create function public.business_payment_outcome_month(p_workspace_id uuid,p_user_id uuid,p_verified_email text,p_month date,p_include_inquiries boolean default false) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$declare base jsonb;payments jsonb;starts timestamptz;begin
 if p_include_inquiries then base:=public.business_outcome_month_inquiries(p_workspace_id,p_user_id,p_verified_email,p_month);else base:=public.business_outcome_month(p_workspace_id,p_user_id,p_verified_email,p_month);end if;
 perform public.connect_assert_reader(p_workspace_id,p_user_id,p_verified_email);starts:=date_trunc('month',p_month::timestamp) at time zone 'UTC';
 select jsonb_build_object('quotesPaid',count(distinct q.id) filter(where q.kind='quote'),'depositsPaid',count(distinct q.id) filter(where q.kind='deposit'),'bookedFromPaidDeposit',count(distinct b.id) filter(where b.status in('confirmed','completed'))) into payments from public.business_payment_requests q join public.business_payments p on p.workspace_id=q.workspace_id and p.reference_id=q.id::text join public.business_payment_events e on e.payment_id=p.id and e.kind='paid' left join public.business_bookings b on q.kind='deposit' and b.id=q.source_record_id and b.workspace_id=q.workspace_id where q.workspace_id=p_workspace_id and e.created_at>=starts and e.created_at<starts+interval '1 month';
 return base||jsonb_build_object('payments',payments);end;$$;
revoke all on function public.acknowledge_payment_follow_up(uuid,uuid,text,uuid),public.read_payment_follow_ups(uuid,uuid,text),public.business_payment_outcome_month(uuid,uuid,text,date,boolean) from public,anon,authenticated;grant execute on function public.acknowledge_payment_follow_up(uuid,uuid,text,uuid),public.read_payment_follow_ups(uuid,uuid,text),public.business_payment_outcome_month(uuid,uuid,text,date,boolean) to service_role;
create table public.creator_royalty_terms(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.creator_listings(id),maintainer_state text not null check(maintainer_state in('creator','takeover','tapered')),agreement_version text,rate_reference text,effective_from timestamptz not null,recorded_by uuid not null references public.users(id),recorded_at timestamptz not null default now(),unique(listing_id,effective_from));
alter table public.creator_royalty_terms enable row level security;revoke all on public.creator_royalty_terms from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.creator_royalty_terms for each row execute function public.money_immutable_guard();
create function public.record_creator_royalty_maintenance(p_listing_id uuid,p_user_id uuid,p_verified_email text,p_state text,p_agreement text,p_rate text,p_effective timestamptz) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare l public.creator_listings%rowtype;r public.creator_royalty_terms%rowtype;begin
 select * into l from public.creator_listings where id=p_listing_id for update;if not found then raise exception 'creator_listing_not_found';end if;perform public.connect_assert_manager(l.creator_workspace_id,p_user_id,p_verified_email);
 if p_effective<now() or (p_state='takeover' and (p_agreement is not null or p_rate is not null)) then raise exception 'creator_maintenance_terms_invalid';end if;
 if p_state in('creator','tapered') and not exists(select 1 from public.money_agreements where beneficiary_workspace_id=l.creator_workspace_id and kind='creator' and version=p_agreement and rate_reference=p_rate and effective_from<=p_effective and (effective_until is null or effective_until>p_effective)) then raise exception 'approved_creator_maintenance_agreement_required';end if;
 insert into public.creator_royalty_terms(listing_id,maintainer_state,agreement_version,rate_reference,effective_from,recorded_by) values(l.id,p_state,p_agreement,p_rate,p_effective,p_user_id) on conflict do nothing;
 select * into r from public.creator_royalty_terms where listing_id=l.id and effective_from=p_effective;
 if r.maintainer_state<>p_state or r.agreement_version is distinct from p_agreement or r.rate_reference is distinct from p_rate then raise exception 'creator_maintenance_conflict';end if;return to_jsonb(r);end;$$;
revoke all on function public.record_creator_royalty_maintenance(uuid,uuid,text,text,text,text,timestamptz) from public,anon,authenticated;grant execute on function public.record_creator_royalty_maintenance(uuid,uuid,text,text,text,text,timestamptz) to service_role;
create function public.read_agent_quote_payment_terms(p_workspace_id uuid,p_user_id uuid,p_verified_email text) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$declare result jsonb;begin
 perform public.connect_assert_reader(p_workspace_id,p_user_id,p_verified_email);if to_regclass('public.agent_quote_receipts') is null then return '[]';end if;
 execute 'select coalesce(jsonb_agg(jsonb_build_object(''source_id'',lead_id,''approvedCents'',amount_cents,''approvedCurrency'',lower(currency),''approvedTerms'',terms)),''[]'') from public.agent_quote_receipts where workspace_id=$1' into result using p_workspace_id;return result;end;$$;
revoke all on function public.read_agent_quote_payment_terms(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.read_agent_quote_payment_terms(uuid,uuid,text) to service_role;
create function public.read_source_transfer_ids(p_charge text) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select coalesce(jsonb_agg(r.transfer_id),'[]') from public.split_transfer_receipts r join public.split_payouts p on p.id=r.payout_id where p.source_account_id='platform' and p.source_transaction=p_charge;$$;
create function public.assert_split_transfer_settlement(p_payout_id uuid,p_available bigint,p_currency text) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p public.split_payouts%rowtype;begin
 select * into p from public.split_payouts where id=p_payout_id;
 perform pg_advisory_xact_lock(hashtextextended('platform:'||p.source_transaction,8814));
 if p.currency<>p_currency or (select coalesce(sum(amount_cents),0) from public.split_payouts where source_account_id='platform' and source_transaction=p.source_transaction)>p_available then raise exception 'payout_source_balance_changed';end if;end;$$;
revoke all on function public.read_source_transfer_ids(text),public.assert_split_transfer_settlement(uuid,bigint,text) from public,anon,authenticated;grant execute on function public.read_source_transfer_ids(text),public.assert_split_transfer_settlement(uuid,bigint,text) to service_role;
alter function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) rename to export_workspace_v3_category_before_extended_money;
revoke all on function public.export_workspace_v3_category_before_extended_money(uuid,uuid,text,text,integer,integer) from public,anon,authenticated,service_role;
create function public.export_workspace_v3_category(p_workspace_id uuid,p_user_id uuid,p_verified_email text,p_category text,p_offset integer default 0,p_limit integer default 1000) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare items jsonb;lim integer=least(greatest(coalesce(p_limit,1000),1),1000);off integer=greatest(coalesce(p_offset,0),0);begin
 perform public.workspace_export_v3_role(p_workspace_id,p_user_id,p_verified_email);
 if p_category='payment_requests' then select coalesce(jsonb_agg(to_jsonb(x)-'token_hash'),'[]') into items from(select * from public.business_payment_requests where workspace_id=p_workspace_id order by issued_at,id offset off limit lim)x;
 elsif p_category='payment_actions' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select a.* from public.payment_request_actions a join public.business_payment_requests q on q.id=a.request_id where q.workspace_id=p_workspace_id order by a.created_at,a.id offset off limit lim)x;
 elsif p_category='refund_requests' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select r.*,rr.provider_refund_id from public.business_refund_requests r join public.business_payments p on p.id=r.payment_id left join public.business_refund_receipts rr on rr.refund_request_id=r.id where p.workspace_id=p_workspace_id order by r.created_at,r.id offset off limit lim)x;
 elsif p_category='transfer_receipts' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select r.* from public.split_transfer_receipts r join public.split_payouts p on p.id=r.payout_id join public.revenue_splits s on s.id=p.split_id where s.business_workspace_id=p_workspace_id order by r.created_at,r.payout_id offset off limit lim)x;
 elsif p_category='transfer_reversals' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select r.*,rr.reversal_id from public.split_transfer_reversals r join public.split_payouts p on p.id=r.payout_id join public.revenue_splits s on s.id=p.split_id left join public.split_transfer_reversal_receipts rr on rr.reversal_request_id=r.id where s.business_workspace_id=p_workspace_id order by r.started_at,r.id offset off limit lim)x;
 elsif p_category='platform_collections' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select p.*,s.payment_intent_id,s.charge_id from public.platform_collections p left join public.platform_collection_settlements s on s.collection_id=p.id where p.business_workspace_id=p_workspace_id order by p.created_at,p.id offset off limit lim)x;
 elsif p_category='platform_collection_terms' then select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select t.*,p.period_start,p.period_end from public.platform_collection_terms t left join public.platform_collection_periods p on p.line_id=t.line_id where t.business_workspace_id=p_workspace_id order by t.accepted_at,t.line_id offset off limit lim)x;
 else return public.export_workspace_v3_category_before_extended_money(p_workspace_id,p_user_id,p_verified_email,p_category,p_offset,p_limit);end if;
 return jsonb_build_object('category',p_category,'items',items,'next',case when jsonb_array_length(items)=lim then off+lim end);end;$$;
alter function public.workspace_export_v3_categories() rename to workspace_export_v3_categories_before_extended_money;
create function public.workspace_export_v3_categories() returns text[] language sql immutable set search_path=public,pg_temp as $$select public.workspace_export_v3_categories_before_extended_money()||array['payment_requests','payment_actions','refund_requests','transfer_receipts','transfer_reversals','platform_collections','platform_collection_terms'];$$;
revoke all on function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) from public,anon,authenticated;grant execute on function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) to service_role;
DO $$declare definition text;begin select pg_get_functiondef('public.read_agency_handoffs(uuid,uuid,text)'::regprocedure) into definition;definition:=replace(definition,'public.connect_assert_manager(','public.connect_assert_reader(');execute definition;end;$$;
-- Once Jacob selects the notice policy, old direct removal commands cannot skip it.
alter function public.end_business_provider(uuid,text,uuid,text) rename to end_business_provider_before_notice;
revoke all on function public.end_business_provider_before_notice(uuid,text,uuid,text) from public,anon,authenticated,service_role;
create function public.end_business_provider(p_user_id uuid,p_verified_email text,p_business_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$begin
 if (exists(select 1 from public.provider_change_policy) or exists(select 1 from public.provider_change_requests where business_workspace_id=p_business_id and status in('awaiting_policy','awaiting_notice','notified'))) and exists(select 1 from public.workspace_providers where customer_workspace_id=p_business_id and status='active') then raise exception 'provider_change_completion_required';end if;
 return public.end_business_provider_before_notice(p_user_id,p_verified_email,p_business_id,p_reason);end;$$;
DO $$declare definition text;begin select pg_get_functiondef('public.complete_provider_change_without_payer(uuid,uuid,text)'::regprocedure) into definition;definition:=replace(definition,'public.end_business_provider(','public.end_business_provider_before_notice(');execute definition;end;$$;
revoke all on function public.end_business_provider(uuid,text,uuid,text) from public,anon,authenticated;grant execute on function public.end_business_provider(uuid,text,uuid,text) to service_role;
create function public.read_provider_change_requests(p_workspace_id uuid,p_user_id uuid,p_verified_email text) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$begin
 perform public.connect_assert_reader(p_workspace_id,p_user_id,p_verified_email);
 return coalesce((select jsonb_agg(to_jsonb(q) order by requested_at desc,id) from public.provider_change_requests q left join public.workspace_providers p on p.id=q.old_provider_id where q.business_workspace_id=p_workspace_id or p.provider_workspace_id=p_workspace_id),'[]');end;$$;
revoke all on function public.read_provider_change_requests(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.read_provider_change_requests(uuid,uuid,text) to service_role;
create table public.provider_change_responses(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.provider_change_requests(id),agency_workspace_id uuid not null references public.workspaces(id),responded_by uuid not null references public.users(id),kind text not null check(kind in('acknowledged','handoff_ready','question','objection')),note text not null check(length(note)<=5000),idempotency_key text not null,created_at timestamptz not null default now(),unique(request_id,idempotency_key));
alter table public.provider_change_responses enable row level security;revoke all on public.provider_change_responses from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.provider_change_responses for each row execute function public.money_immutable_guard();
create function public.respond_provider_change(p_request_id uuid,p_user_id uuid,p_verified_email text,p_kind text,p_note text,p_key text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare q public.provider_change_requests%rowtype;p public.workspace_providers%rowtype;r public.provider_change_responses%rowtype;begin
 select * into q from public.provider_change_requests where id=p_request_id for update;select * into p from public.workspace_providers where id=q.old_provider_id;
 perform public.connect_assert_manager(p.provider_workspace_id,p_user_id,p_verified_email);
 if p.status<>'active' or q.status<>'notified' or q.respond_by<now() then raise exception 'provider_response_window_closed';end if;
 if length(p_key) not between 8 and 200 then raise exception 'provider_response_invalid';end if;
 insert into public.provider_change_responses(request_id,agency_workspace_id,responded_by,kind,note,idempotency_key) values(q.id,p.provider_workspace_id,p_user_id,p_kind,p_note,p_key) on conflict do nothing;
 select * into r from public.provider_change_responses where request_id=q.id and idempotency_key=p_key;
 if r.responded_by<>p_user_id or r.kind<>p_kind or r.note<>p_note then raise exception 'provider_response_conflict';end if;return to_jsonb(r);end;$$;
alter function public.acknowledge_provider_change_notice(uuid,uuid,text) rename to acknowledge_provider_change_notice_before_response;
revoke all on function public.acknowledge_provider_change_notice_before_response(uuid,uuid,text) from public,anon,authenticated,service_role;
create function public.acknowledge_provider_change_notice(p_request_id uuid,p_user_id uuid,p_verified_email text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare q jsonb;begin
 q:=public.acknowledge_provider_change_notice_before_response(p_request_id,p_user_id,p_verified_email);
 if not exists(select 1 from public.provider_change_responses where request_id=p_request_id and kind='acknowledged') then perform public.respond_provider_change(p_request_id,p_user_id,p_verified_email,'acknowledged','Agency manager acknowledged the notice.','acknowledge:'||p_request_id::text);end if;return q;end;$$;
-- The read includes immutable responses so both parties see the same record.
DO $$declare definition text;begin select pg_get_functiondef('public.read_provider_change_requests(uuid,uuid,text)'::regprocedure) into definition;definition:=replace(definition,'jsonb_agg(to_jsonb(q) order by requested_at desc,id)','jsonb_agg(to_jsonb(q)||jsonb_build_object(''responses'',coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at,r.id) from public.provider_change_responses r where r.request_id=q.id),''[]'')) order by requested_at desc,q.id)');execute definition;end;$$;
revoke all on function public.respond_provider_change(uuid,uuid,text,text,text,text),public.acknowledge_provider_change_notice(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.respond_provider_change(uuid,uuid,text,text,text,text),public.acknowledge_provider_change_notice(uuid,uuid,text) to service_role;
-- A bundled agency invoice uses persisted provider subscription/item ownership,
-- never a line's claimed business metadata. Unpriced client lines stay closed.
create function public.resolve_invoice_business_line(p_payer_workspace uuid,p_subscription text,p_item text,p_basis bigint,p_currency text) returns uuid language plpgsql stable security definer set search_path=public,pg_temp as $$declare business uuid;begin
 if p_item is not null then select coalesce((to_jsonb(i)->>'business_workspace_id')::uuid,l.workspace_id) into business from public.subscription_items i join public.subscriptions s on s.id=i.subscription_id join public.accounts a on a.id=s.account_id left join public.tenants t on t.id=i.tenant_id left join public.tenant_workspace_links l on l.tenant_stable_id=t.stable_id where a.workspace_id=p_payer_workspace and s.stripe_subscription_id=p_subscription and i.stripe_item_id=p_item and i.amount_cents is not null and i.amount_cents>=p_basis and s.currency=p_currency limit 1;
 if business is not null then return business;end if;end if;
 if exists(select 1 from public.workspaces where id=p_payer_workspace and kind='customer') then return p_payer_workspace;end if;return null;end;$$;
revoke all on function public.resolve_invoice_business_line(uuid,text,text,bigint,text) from public,anon,authenticated;grant execute on function public.resolve_invoice_business_line(uuid,text,text,bigint,text) to service_role;
create table public.money_reconciliation_issues(account_id text not null,event_id text not null,event_type text not null,reason text not null,object_id text,created_at timestamptz not null default now(),primary key(account_id,event_id,reason));
alter table public.money_reconciliation_issues enable row level security;revoke all on public.money_reconciliation_issues from public,anon,authenticated,service_role;
create trigger money_immutable before update or delete on public.money_reconciliation_issues for each row execute function public.money_immutable_guard();
create function public.record_money_reconciliation_issue(p_account text,p_event text,p_type text,p_reason text,p_object text) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 insert into public.money_reconciliation_issues(account_id,event_id,event_type,reason,object_id) values(p_account,p_event,p_type,p_reason,p_object) on conflict do nothing;
 if not exists(select 1 from public.money_reconciliation_issues where account_id=p_account and event_id=p_event and event_type=p_type and reason=p_reason and object_id is not distinct from p_object) then raise exception 'money_reconciliation_identity_conflict';end if;end;$$;
revoke all on function public.record_money_reconciliation_issue(text,text,text,text,text) from public,anon,authenticated;grant execute on function public.record_money_reconciliation_issue(text,text,text,text,text) to service_role;
