-- Recovery is a new, explicitly reviewed generation; the original payout is never resent.
create table public.split_recovery_payouts(id uuid primary key default gen_random_uuid(),payout_id uuid not null references public.split_payouts(id),restoration_id uuid not null references public.revenue_splits(id),amount_cents bigint not null check(amount_cents>0),authorized_by uuid not null references public.users(id),profile_version text not null,idempotency_key text not null,created_at timestamptz not null default now(),unique(payout_id,idempotency_key));
create table public.split_recovery_attempts(recovery_id uuid primary key references public.split_recovery_payouts(id),started_at timestamptz not null default clock_timestamp());
create table public.split_recovery_receipts(recovery_id uuid primary key references public.split_recovery_payouts(id),transfer_id text not null unique,amount_cents bigint not null,currency text not null,created_at timestamptz not null default now());
create table public.split_recovery_reversals(id uuid primary key default gen_random_uuid(),recovery_id uuid not null references public.split_recovery_payouts(id),loss_id uuid not null references public.revenue_splits(id),amount_cents bigint not null check(amount_cents>0),started_at timestamptz not null default clock_timestamp(),unique(recovery_id,loss_id));
create table public.split_recovery_reversal_receipts(reversal_id uuid primary key references public.split_recovery_reversals(id),provider_reversal_id text not null unique,amount_cents bigint not null,created_at timestamptz not null default now());
DO $$declare t text;begin foreach t in array array['split_recovery_payouts','split_recovery_attempts','split_recovery_receipts','split_recovery_reversals','split_recovery_reversal_receipts'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);execute format('create trigger money_immutable before update or delete on public.%I for each row execute function public.money_immutable_guard()',t);end loop;end $$;
create function public.money_assert_operator(p_user uuid,p_email text) returns void language plpgsql stable security definer set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.super_admins a join public.users u on u.id=a.user_id where a.user_id=p_user and a.revoked_at is null and u.verified_at is not null and lower(u.email)=lower(btrim(p_email))) then raise exception 'money_operator_denied';end if;end;$$;
-- Confirmed reversals free capacity; pending reversals never do.
create function public.split_reserved_net(p_split uuid) returns bigint language sql stable security definer set search_path=public,pg_temp as $$select coalesce((select sum(p.amount_cents) from public.split_payouts p where p.split_id=p_split),0)-coalesce((select sum(r.amount_cents) from public.split_transfer_reversal_receipts r join public.split_transfer_reversals x on x.id=r.reversal_request_id join public.split_payouts p on p.id=x.payout_id where p.split_id=p_split),0)+coalesce((select sum(r.amount_cents) from public.split_recovery_payouts r join public.split_payouts p on p.id=r.payout_id where p.split_id=p_split),0)-coalesce((select sum(r.amount_cents) from public.split_recovery_reversal_receipts r join public.split_recovery_reversals x on x.id=r.reversal_id join public.split_recovery_payouts c on c.id=x.recovery_id join public.split_payouts p on p.id=c.payout_id where p.split_id=p_split),0);$$;
create function public.authorize_split_recovery(p_payout uuid,p_restoration uuid,p_user uuid,p_email text,p_amount bigint,p_profile text,p_key text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p public.split_payouts%rowtype;r public.split_recovery_payouts%rowtype;entitlement bigint;begin
 perform public.money_assert_operator(p_user,p_email);select * into p from public.split_payouts where id=p_payout for update;
 perform pg_advisory_xact_lock(hashtextextended('platform:'||p.source_transaction,8814));
 select * into r from public.split_recovery_payouts where payout_id=p.id and idempotency_key=p_key;
 if r.id is not null then if r.restoration_id<>p_restoration or r.amount_cents<>p_amount or r.authorized_by<>p_user or r.profile_version<>p_profile then raise exception 'recovery_idempotency_conflict';end if;return to_jsonb(r);end if;
 if p.id is null or p.source_account_id<>'platform' or length(p_key) not between 8 and 200 or not exists(select 1 from public.split_transfer_receipts where payout_id=p.id) or not exists(select 1 from public.revenue_splits where id=p_restoration and original_split_id=p.split_id and amount_cents>0 and currency=p.currency) then raise exception 'recovery_restoration_required';end if;
 if not exists(select 1 from public.connected_accounts where stripe_account_id=p.recipient_account_id and state='ready' and profile_version=p_profile and 'recipient'=any(configurations) and capabilities#>>'{recipient,capabilities,stripe_balance,stripe_transfers,status}'='active') then raise exception 'recovery_recipient_unavailable';end if;
 select amount_cents+coalesce((select sum(amount_cents) from public.revenue_splits where original_split_id=s.id),0) into entitlement from public.revenue_splits s where id=p.split_id;
 if p_amount<=0 or p_amount>entitlement-public.split_reserved_net(p.split_id) or p_amount>(select amount_cents from public.revenue_splits where id=p_restoration)-coalesce((select sum(amount_cents) from public.split_recovery_payouts where restoration_id=p_restoration),0) then raise exception 'recovery_entitlement_overdraw';end if;
 insert into public.split_recovery_payouts(payout_id,restoration_id,amount_cents,authorized_by,profile_version,idempotency_key) values(p.id,p_restoration,p_amount,p_user,p_profile,p_key) returning * into r;return to_jsonb(r);end;$$;
create function public.prepare_split_recovery(p_recovery uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare r public.split_recovery_payouts%rowtype;p public.split_payouts%rowtype;receipt public.split_recovery_receipts%rowtype;entitlement bigint;begin
 select * into r from public.split_recovery_payouts where id=p_recovery for update;select * into p from public.split_payouts where id=r.payout_id for update;
 perform 1 from public.super_admins a join public.users u on u.id=a.user_id join public.connected_accounts c on c.stripe_account_id=p.recipient_account_id where a.user_id=r.authorized_by and a.revoked_at is null and u.verified_at is not null and c.state='ready' and 'recipient'=any(c.configurations) and c.profile_version=r.profile_version and c.capabilities#>>'{recipient,capabilities,stripe_balance,stripe_transfers,status}'='active' for share of a,u,c;if not found then raise exception 'recovery_authorization_required';end if;
 select * into receipt from public.split_recovery_receipts where recovery_id=r.id;
 if receipt.recovery_id is null then select amount_cents+coalesce((select sum(amount_cents) from public.revenue_splits where original_split_id=s.id),0) into entitlement from public.revenue_splits s where id=p.split_id;
 if public.split_reserved_net(p.split_id)>entitlement then raise exception 'recovery_accrual_changed';end if;
 if exists(select 1 from public.split_recovery_attempts where recovery_id=r.id and started_at<clock_timestamp()-interval '23 hours') then raise exception 'recovery_attempt_requires_reconciliation';end if;
 insert into public.split_recovery_attempts(recovery_id) values(r.id) on conflict do nothing;end if;
 return to_jsonb(r)||jsonb_build_object('recipient_account_id',p.recipient_account_id,'source_account_id',p.source_account_id,'source_transaction',p.source_transaction,'currency',p.currency,'transfer_id',receipt.transfer_id);end;$$;
create function public.assert_recovery_settlement(p_recovery uuid,p_available bigint,p_currency text) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare p public.split_payouts%rowtype;reserved bigint;begin
 select x.* into p from public.split_payouts x join public.split_recovery_payouts r on r.payout_id=x.id where r.id=p_recovery;
 perform pg_advisory_xact_lock(hashtextextended('platform:'||p.source_transaction,8814));
 select coalesce(sum(public.split_reserved_net(split_id)),0) into reserved from public.split_payouts where source_account_id='platform' and source_transaction=p.source_transaction;
 if p.id is null or p.currency<>p_currency or reserved>p_available then raise exception 'recovery_source_balance_changed';end if;end;$$;
create function public.record_split_recovery(p_recovery uuid,p_transfer text,p_amount bigint,p_currency text) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 if p_transfer !~ '^tr_[A-Za-z0-9]+$' or not exists(select 1 from public.split_recovery_payouts r join public.split_payouts p on p.id=r.payout_id join public.split_recovery_attempts a on a.recovery_id=r.id where r.id=p_recovery and r.amount_cents=p_amount and p.currency=p_currency) then raise exception 'recovery_transfer_mismatch';end if;
 insert into public.split_recovery_receipts(recovery_id,transfer_id,amount_cents,currency) values(p_recovery,p_transfer,p_amount,p_currency) on conflict do nothing;
 if not exists(select 1 from public.split_recovery_receipts where recovery_id=p_recovery and transfer_id=p_transfer and amount_cents=p_amount and currency=p_currency) then raise exception 'recovery_transfer_conflict';end if;end;$$;
create function public.prepare_recovery_reversal(p_recovery uuid,p_loss uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare c public.split_recovery_payouts%rowtype;p public.split_payouts%rowtype;r public.split_recovery_reversals%rowtype;receipt public.split_recovery_receipts%rowtype;owed bigint;outstanding bigint;pending bigint;begin
 select * into c from public.split_recovery_payouts where id=p_recovery for update;select * into p from public.split_payouts where id=c.payout_id for update;select * into receipt from public.split_recovery_receipts where recovery_id=c.id;
 select * into r from public.split_recovery_reversals where recovery_id=c.id and loss_id=p_loss;
 if r.id is null then
 if receipt.recovery_id is null or not exists(select 1 from public.revenue_splits where id=p_loss and original_split_id=p.split_id and amount_cents<0) then raise exception 'recovery_loss_source_required';end if;
 select amount_cents+coalesce((select sum(amount_cents) from public.revenue_splits where original_split_id=s.id),0) into owed from public.revenue_splits s where id=p.split_id;
 outstanding:=receipt.amount_cents-coalesce((select sum(amount_cents) from public.split_recovery_reversals where recovery_id=c.id),0);
 select coalesce(sum(x.amount_cents),0) into pending from public.split_recovery_reversals x join public.split_recovery_payouts y on y.id=x.recovery_id where y.payout_id=p.id and not exists(select 1 from public.split_recovery_reversal_receipts z where z.reversal_id=x.id);
 owed:=least(outstanding,public.split_reserved_net(p.split_id)-owed-pending);if owed<=0 then raise exception 'recovery_no_new_loss';end if;
 insert into public.split_recovery_reversals(recovery_id,loss_id,amount_cents) values(c.id,p_loss,owed) returning * into r;end if;
 if not exists(select 1 from public.split_recovery_reversal_receipts where reversal_id=r.id) and r.started_at<clock_timestamp()-interval '23 hours' then raise exception 'recovery_reversal_requires_reconciliation';end if;
 return to_jsonb(r)||jsonb_build_object('transfer_id',receipt.transfer_id,'provider_reversal_id',(select provider_reversal_id from public.split_recovery_reversal_receipts where reversal_id=r.id));end;$$;
create function public.record_recovery_reversal(p_id uuid,p_provider text,p_amount bigint) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 if p_provider !~ '^trr_[A-Za-z0-9]+$' or not exists(select 1 from public.split_recovery_reversals where id=p_id and amount_cents=p_amount) then raise exception 'recovery_reversal_mismatch';end if;
 insert into public.split_recovery_reversal_receipts(reversal_id,provider_reversal_id,amount_cents) values(p_id,p_provider,p_amount) on conflict do nothing;
 if not exists(select 1 from public.split_recovery_reversal_receipts where reversal_id=p_id and provider_reversal_id=p_provider and amount_cents=p_amount) then raise exception 'recovery_reversal_conflict';end if;end;$$;
create or replace function public.read_source_transfer_ids(p_charge text) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select coalesce(jsonb_agg(transfer_id),'[]') from(select r.transfer_id from public.split_transfer_receipts r join public.split_payouts p on p.id=r.payout_id where p.source_account_id='platform' and p.source_transaction=p_charge union all select r.transfer_id from public.split_recovery_receipts r join public.split_recovery_payouts c on c.id=r.recovery_id join public.split_payouts p on p.id=c.payout_id where p.source_account_id='platform' and p.source_transaction=p_charge)x;$$;
DO $$declare f record;begin for f in select p.oid::regprocedure name from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('money_assert_operator','split_reserved_net','authorize_split_recovery','prepare_split_recovery','assert_recovery_settlement','record_split_recovery','prepare_recovery_reversal','record_recovery_reversal') loop execute format('revoke all on function %s from public,anon,authenticated',f.name);execute format('grant execute on function %s to service_role',f.name);end loop;end $$;
-- Both original and recovery rails consume one common, net source reservation.
DO $$declare d text;begin
 select pg_get_functiondef('public.reserve_split_payout_dry_run(uuid,text,text,bigint,text,text,bigint)'::regprocedure) into d;
 d:=replace(d,'select coalesce(sum(amount_cents),0) into spent from public.split_payouts','select coalesce(sum(public.split_reserved_net(split_id)),0) into spent from public.split_payouts');execute d;
 select pg_get_functiondef('public.assert_split_transfer_settlement(uuid,bigint,text)'::regprocedure) into d;
 d:=replace(d,'select coalesce(sum(amount_cents),0) from public.split_payouts','select coalesce(sum(public.split_reserved_net(split_id)),0) from public.split_payouts');execute d;
end;$$;
