create function public.money_assert_operator_writer(p_user uuid,p_email text) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 perform 1 from public.super_admins a join public.users u on u.id=a.user_id where a.user_id=p_user and a.revoked_at is null and u.verified_at is not null and lower(u.email)=lower(btrim(p_email)) for share of a,u;if not found then raise exception 'money_operator_denied';end if;end;$$;
DO $$declare d text;begin select pg_get_functiondef('public.authorize_split_recovery(uuid,uuid,uuid,text,bigint,text,text)'::regprocedure) into d;d:=replace(d,'public.money_assert_operator(','public.money_assert_operator_writer(');execute d;end;$$;
create table public.invoice_money_evidence(id uuid primary key default gen_random_uuid(),account_id text not null,event_id text not null,invoice_id text not null,line_id text not null,created_at timestamptz not null default now(),foreign key(account_id,line_id) references public.invoice_split_sources(source_account_id,invoice_line_id),unique(account_id,event_id,line_id));
create table public.money_reconciliation_resolutions(id uuid primary key default gen_random_uuid(),account_id text not null,event_id text not null,reason text not null,reviewed_by uuid not null references public.users(id),kind text not null check(kind in('no_effect_after_review','effect_confirmed')),note text not null check(length(note) between 20 and 5000),evidence_kind text check(evidence_kind in('business_payment','invoice_split','platform_settlement')),evidence_id uuid,created_at timestamptz not null default now(),foreign key(account_id,event_id,reason) references public.money_reconciliation_issues(account_id,event_id,reason),unique(account_id,event_id,reason),check((kind='effect_confirmed' and evidence_kind is not null and evidence_id is not null) or (kind='no_effect_after_review' and evidence_kind is null and evidence_id is null)));
DO $$declare t text;begin foreach t in array array['invoice_money_evidence','money_reconciliation_resolutions'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);execute format('create trigger money_immutable before update or delete on public.%I for each row execute function public.money_immutable_guard()',t);end loop;end $$;
create function public.record_invoice_money_evidence(p_account text,p_event text,p_invoice text,p_line text) returns void language plpgsql security definer set search_path=public,pg_temp as $$begin
 if not exists(select 1 from public.revenue_splits where source_account_id=p_account and invoice_line_id=p_line and event_key='accrual') or p_invoice !~ '^in_[A-Za-z0-9]+$' then raise exception 'invoice_money_effect_required';end if;
 insert into public.invoice_money_evidence(account_id,event_id,invoice_id,line_id) values(p_account,p_event,p_invoice,p_line) on conflict do nothing;
 if not exists(select 1 from public.invoice_money_evidence where account_id=p_account and event_id=p_event and line_id=p_line and invoice_id=p_invoice) then raise exception 'invoice_money_evidence_conflict';end if;end;$$;
create function public.read_money_reconciliation(p_user uuid,p_email text,p_limit integer default 100) returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$begin
 perform public.money_assert_operator(p_user,p_email);
 return coalesce((select jsonb_agg(to_jsonb(x)) from(select i.*,to_jsonb(r) resolution from public.money_reconciliation_issues i left join public.money_reconciliation_resolutions r using(account_id,event_id,reason) order by (r.id is not null),i.created_at,i.account_id,i.event_id,i.reason limit least(greatest(p_limit,1),100))x),'[]');end;$$;
create function public.resolve_money_reconciliation(p_user uuid,p_email text,p_account text,p_event text,p_reason text,p_kind text,p_note text,p_evidence_kind text default null,p_evidence_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare i public.money_reconciliation_issues%rowtype;r public.money_reconciliation_resolutions%rowtype;proven boolean=false;begin
 perform public.money_assert_operator_writer(p_user,p_email);select * into i from public.money_reconciliation_issues where account_id=p_account and event_id=p_event and reason=p_reason for update;if not found then raise exception 'money_reconciliation_not_found';end if;
 if p_kind='effect_confirmed' then
 if p_evidence_kind='business_payment' then select exists(select 1 from public.business_payment_events e where e.id=p_evidence_id and e.merchant_account_id=i.account_id and e.provider_object_id=i.object_id) into proven;
 elsif p_evidence_kind='invoice_split' then select exists(select 1 from public.invoice_money_evidence e where e.id=p_evidence_id and e.account_id=i.account_id and e.event_id=i.event_id and e.invoice_id=i.object_id) into proven;
 elsif p_evidence_kind='platform_settlement' then select exists(select 1 from public.platform_collection_settlements e where e.collection_id=p_evidence_id and i.account_id='platform' and e.payment_intent_id=i.object_id) into proven;end if;
 if not proven then raise exception 'money_reconciliation_effect_unproven';end if;
 end if;
 insert into public.money_reconciliation_resolutions(account_id,event_id,reason,reviewed_by,kind,note,evidence_kind,evidence_id) values(i.account_id,i.event_id,i.reason,p_user,p_kind,p_note,p_evidence_kind,p_evidence_id) on conflict do nothing;
 select * into r from public.money_reconciliation_resolutions where account_id=i.account_id and event_id=i.event_id and reason=i.reason;
 if r.reviewed_by<>p_user or r.kind<>p_kind or r.note<>p_note or r.evidence_kind is distinct from p_evidence_kind or r.evidence_id is distinct from p_evidence_id then raise exception 'money_reconciliation_resolution_conflict';end if;return to_jsonb(r);end;$$;
DO $$declare f record;begin for f in select p.oid::regprocedure name from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('money_assert_operator_writer','record_invoice_money_evidence','read_money_reconciliation','resolve_money_reconciliation') loop execute format('revoke all on function %s from public,anon,authenticated',f.name);execute format('grant execute on function %s to service_role',f.name);end loop;end $$;
-- Recovery generations and their provider receipts are portable with the original business.
alter function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) rename to export_workspace_v3_category_before_recoveries;
revoke all on function public.export_workspace_v3_category_before_recoveries(uuid,uuid,text,text,integer,integer) from public,anon,authenticated,service_role;
create function public.export_workspace_v3_category(p_workspace_id uuid,p_user_id uuid,p_verified_email text,p_category text,p_offset integer default 0,p_limit integer default 1000) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare items jsonb;begin
 if p_category<>'recovery_payouts' then return public.export_workspace_v3_category_before_recoveries(p_workspace_id,p_user_id,p_verified_email,p_category,p_offset,p_limit);end if;
 perform public.workspace_export_v3_role(p_workspace_id,p_user_id,p_verified_email);
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into items from(select r.*,to_jsonb(t) transfer,coalesce((select jsonb_agg(to_jsonb(v)||jsonb_build_object('providerReceipt',to_jsonb(z))) from public.split_recovery_reversals v left join public.split_recovery_reversal_receipts z on z.reversal_id=v.id where v.recovery_id=r.id),'[]') reversals from public.split_recovery_payouts r join public.split_payouts p on p.id=r.payout_id join public.revenue_splits s on s.id=p.split_id left join public.split_recovery_receipts t on t.recovery_id=r.id where s.business_workspace_id=p_workspace_id order by r.created_at,r.id offset greatest(coalesce(p_offset,0),0) limit least(greatest(coalesce(p_limit,1000),1),1000))x;
 return jsonb_build_object('category',p_category,'items',items,'next',case when jsonb_array_length(items)=least(greatest(coalesce(p_limit,1000),1),1000) then greatest(coalesce(p_offset,0),0)+least(greatest(coalesce(p_limit,1000),1),1000) end);end;$$;
alter function public.workspace_export_v3_categories() rename to workspace_export_v3_categories_before_recoveries;
create function public.workspace_export_v3_categories() returns text[] language sql immutable set search_path=public,pg_temp as $$select public.workspace_export_v3_categories_before_recoveries()||array['recovery_payouts'];$$;
revoke all on function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) from public,anon,authenticated;grant execute on function public.export_workspace_v3_category(uuid,uuid,text,text,integer,integer) to service_role;
