begin;
set local lock_timeout='5s';
do $$ begin if exists(select 1 from public.home_finder_bindings) or exists(select 1 from public.home_finder_intake_receipts) or exists(select 1 from public.home_finder_binding_audit) then raise exception 'home_finder_rollback_retained_history'; end if; end; $$;
drop trigger home_finder_live_gate on public.systems;
drop function public.read_home_finder_receipt_scope(uuid,uuid);
drop function public.refresh_home_finder_probe(uuid,bigint,jsonb,boolean);
drop function public.read_home_finder_probe(uuid);
drop function public.finish_home_finder_intake(uuid,uuid,text,text,text);
drop function public.begin_home_finder_intake(uuid,uuid,bigint,text);
drop function public.read_home_finder_public(uuid);
drop function public.home_finder_lifecycle_guard();
drop function public.revoke_home_finder(uuid,uuid,text,uuid,bigint);
drop function public.observe_home_finder(uuid,uuid,text,uuid,bigint,jsonb,boolean);
drop function public.read_home_finder_bindings(uuid,uuid,text);
drop function public.install_home_finder(uuid,text,jsonb,text);
drop function public.home_finder_binding_json(public.home_finder_bindings);
drop function public.home_finder_current(public.home_finder_bindings);
drop table public.home_finder_binding_audit,public.home_finder_intake_receipts,public.home_finder_bindings;
notify pgrst,'reload schema';
commit;
