-- Refuse after accepted cleanup or exit-ending effects; preserve all original histories.
begin;
set local lock_timeout='3s';
do $$begin
 if exists(select 1 from public.provider_completion_cleanup_receipts) or exists(select 1 from public.provider_exit_completion_permissions) or exists(select 1 from public.business_attribution_endings where workspace_exit_request_id is not null) then raise exception 'provider_completion_receipts_require_preservation';end if;
 if (select md5(prosrc) from pg_proc where oid='public.provider_completion_end_authority()'::regprocedure) is distinct from '17ad69b114de88af119f4e56dcf7cbc5' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.business_attribution_require_provider_change()'::regprocedure) is distinct from '08634dde177ade64ed0cc492274f32bb' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.request_provider_change(uuid,uuid,text,uuid,text,uuid)'::regprocedure) is distinct from '4479781421e0b8af1f35917185a8b923' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.choose_business_provider(uuid,text,uuid,uuid)'::regprocedure) is distinct from '4c8448ce4d394937a36955bba71adb49' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.end_business_provider(uuid,text,uuid,text)'::regprocedure) is distinct from 'ed817e640adaf41994ff52f2c47700ac' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.acknowledge_provider_change_notice(uuid,uuid,text)'::regprocedure) is distinct from '4d2aec70a062d020ba66887a9421af6d' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.complete_provider_change(uuid,uuid,text)'::regprocedure) is distinct from '77c67300c3fd275390657de9a144c2c4' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.cancel_provider_change(uuid,uuid,text)'::regprocedure) is distinct from '027c3e8245a4bb9641d3c831362fffa4' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.grant_agency_application_draft_edit(uuid,text,uuid,uuid)'::regprocedure) is distinct from '6d99d5f8a5d431b6b1b5b8fbfe37584f' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.grant_system_package_install(uuid,uuid,text,uuid,uuid,uuid,timestamptz)'::regprocedure) is distinct from 'facf67e54f1ca9f841d70fd5b2abbb98' then raise exception 'provider_completion_rollback_wrong_order';end if;
 if (select md5(prosrc) from pg_proc where oid='public.complete_workspace_exit(uuid,uuid,text,text,text,jsonb,text,text,text)'::regprocedure) is distinct from '5fc18db00b90c14600a9d55f0bb76c4d' then raise exception 'provider_completion_rollback_wrong_order';end if;
end $$;
drop trigger provider_completion_end_authority on public.workspace_providers;
drop function public.provider_completion_end_authority();
drop trigger business_attribution_provider_change on public.workspace_providers;
drop function public.business_attribution_require_provider_change();
alter function public.business_attribution_require_provider_change_before_exit() rename to business_attribution_require_provider_change;
create trigger business_attribution_provider_change before update on public.workspace_providers for each row when(old.status='active' and new.status='ended') execute function public.business_attribution_require_provider_change();
drop function public.request_provider_change(uuid,uuid,text,uuid,text,uuid);
alter function public.request_provider_change_before_completion_cleanup(uuid,uuid,text,uuid,text,uuid) rename to request_provider_change;
revoke all on function public.request_provider_change(uuid,uuid,text,uuid,text,uuid) from public,anon,authenticated;
grant execute on function public.request_provider_change(uuid,uuid,text,uuid,text,uuid) to service_role;
drop function public.choose_business_provider(uuid,text,uuid,uuid);
alter function public.choose_business_provider_before_completion_cleanup(uuid,text,uuid,uuid) rename to choose_business_provider;
revoke all on function public.choose_business_provider(uuid,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.choose_business_provider(uuid,text,uuid,uuid) to service_role;
drop function public.end_business_provider(uuid,text,uuid,text);
alter function public.end_business_provider_before_completion_cleanup(uuid,text,uuid,text) rename to end_business_provider;
revoke all on function public.end_business_provider(uuid,text,uuid,text) from public,anon,authenticated;
grant execute on function public.end_business_provider(uuid,text,uuid,text) to service_role;
drop function public.acknowledge_provider_change_notice(uuid,uuid,text);
alter function public.acknowledge_provider_change_notice_before_completion_cleanup(uuid,uuid,text) rename to acknowledge_provider_change_notice;
revoke all on function public.acknowledge_provider_change_notice(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.acknowledge_provider_change_notice(uuid,uuid,text) to service_role;
drop function public.complete_provider_change(uuid,uuid,text);
alter function public.complete_provider_change_before_completion_cleanup(uuid,uuid,text) rename to complete_provider_change;
revoke all on function public.complete_provider_change(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.complete_provider_change(uuid,uuid,text) to service_role;
drop function public.cancel_provider_change(uuid,uuid,text);
alter function public.cancel_provider_change_before_completion_cleanup(uuid,uuid,text) rename to cancel_provider_change;
revoke all on function public.cancel_provider_change(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.cancel_provider_change(uuid,uuid,text) to service_role;
drop function public.grant_agency_application_draft_edit(uuid,text,uuid,uuid);
alter function public.grant_agency_application_draft_edit_before_completion_cleanup(uuid,text,uuid,uuid) rename to grant_agency_application_draft_edit;
revoke all on function public.grant_agency_application_draft_edit(uuid,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.grant_agency_application_draft_edit(uuid,text,uuid,uuid) to service_role;
drop function public.grant_system_package_install(uuid,uuid,text,uuid,uuid,uuid,timestamptz);
alter function public.grant_system_package_install_before_completion_cleanup(uuid,uuid,text,uuid,uuid,uuid,timestamptz) rename to grant_system_package_install;
revoke all on function public.grant_system_package_install(uuid,uuid,text,uuid,uuid,uuid,timestamptz) from public,anon,authenticated;
grant execute on function public.grant_system_package_install(uuid,uuid,text,uuid,uuid,uuid,timestamptz) to service_role;
drop function public.complete_workspace_exit(uuid,uuid,text,text,text,jsonb,text,text,text);
alter function public.complete_workspace_exit_before_completion_cleanup(uuid,uuid,text,text,text,jsonb,text,text,text) rename to complete_workspace_exit;
revoke all on function public.complete_workspace_exit(uuid,uuid,text,text,text,jsonb,text,text,text) from public,anon,authenticated;
grant execute on function public.complete_workspace_exit(uuid,uuid,text,text,text,jsonb,text,text,text) to service_role;
alter table public.business_attribution_endings drop constraint business_attribution_one_ending_origin;
alter table public.business_attribution_endings alter column provider_change_request_id set not null;
alter table public.business_attribution_endings drop column workspace_exit_request_id;
drop table public.provider_exit_completion_permissions,public.provider_completion_cleanup_receipts;
notify pgrst,'reload schema';
commit;
