begin;
set local lock_timeout='2s';
set local statement_timeout='30s';
drop function public.confirm_agent_booking(text,boolean),public.change_native_booking_before_w6(text,jsonb);
alter function public.confirm_agent_booking_before_service_policy(text,boolean) rename to confirm_agent_booking;
alter function public.change_native_booking_before_service_policy(text,jsonb) rename to change_native_booking_before_w6;
grant execute on function public.confirm_agent_booking(text,boolean) to service_role;
drop trigger booking_service_policy_guard on public.business_bookings;
drop function public.enforce_booking_service_policy();
drop function public.read_tenant_booking_context(text),public.read_tenant_booking_policy(text),public.configure_booking_setup(uuid,text,uuid,text,jsonb),public.read_booking_instant_policies(uuid),public.decide_booking_instant_policy(uuid,uuid,integer,text,uuid,text,boolean);
alter function public.read_tenant_booking_context_before_service_policy(text) rename to read_tenant_booking_context;
alter function public.read_tenant_booking_policy_before_service_policy(text) rename to read_tenant_booking_policy;
alter function public.configure_booking_setup_before_service_policy(uuid,text,uuid,text,jsonb) rename to configure_booking_setup;
alter function public.read_booking_instant_policies_before_service_policy(uuid) rename to read_booking_instant_policies;
alter function public.decide_booking_instant_policy_before_service_policy(uuid,uuid,integer,text,uuid,text,boolean) rename to decide_booking_instant_policy;
grant execute on function public.read_tenant_booking_context(text),public.read_tenant_booking_policy(text),public.configure_booking_setup(uuid,text,uuid,text,jsonb),public.read_booking_instant_policies(uuid),public.decide_booking_instant_policy(uuid,uuid,integer,text,uuid,text,boolean) to service_role;
drop function public.booking_service_policy_json(uuid);
alter table public.booking_instant_policies drop column business_service_id,drop column service_policy_revision;
drop table public.booking_service_policies;
commit;
