-- Rollback for 20261002120000_business_record.sql
-- Forward SHA-256: 36fffb74a5c26eaacb6cceb0d5abcc9e4bb462a611ffbbf6ac7c926b9f28ce67
-- Batch 1: reverse file order; undo every later batch first.
-- Prepared SQL only. Production execution requires a separately reviewed approval.
-- Take a verified dump first. Removed data is retained in the private archive schema.
-- Does not undo provider effects or repair Supabase migration history.
begin;
set local lock_timeout = '3s';
set local statement_timeout = '120s';
-- Refuse a later schema or a drifted body; never cascade through unknown objects.
do $rollback_guard$
begin
  if (select md5(pg_get_functiondef(to_regprocedure('public.tenant_unlink_plan(uuid)')))) is distinct from 'f7a03cefd9bb85f36b8825c172a30dd8' then raise exception 'rollback_wrong_order_or_function_drift: tenant_unlink_plan'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_sources()')))) is distinct from 'e312cf3a42a713f59e0b11d190c94de7' then raise exception 'rollback_wrong_order_or_function_drift: business_record_sources'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_contact_sources()')))) is distinct from '815a966f7570461fa406265c424da43f' then raise exception 'rollback_wrong_order_or_function_drift: business_contact_sources'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.tenant_workspace_link_guard()')))) is distinct from '5a4973951f6e295dac70e3fec93b6326' then raise exception 'rollback_wrong_order_or_function_drift: tenant_workspace_link_guard'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_contact_phone_key(text)')))) is distinct from 'b4183e9e9f1de7c446739b6a4a474e10' then raise exception 'rollback_wrong_order_or_function_drift: business_contact_phone_key'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.preview_tenant_unlink(text,text)')))) is distinct from 'af41c944e2fb863fa738a9bf3a468036' then raise exception 'rollback_wrong_order_or_function_drift: preview_tenant_unlink'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_email_valid(text)')))) is distinct from '37d0d6726e1d3f8e47c74bf6d6a5b9e0' then raise exception 'rollback_wrong_order_or_function_drift: business_record_email_valid'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_time_valid(jsonb)')))) is distinct from 'fba779abc622715075eaad532574484a' then raise exception 'rollback_wrong_order_or_function_drift: business_record_time_valid'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_history_immutable()')))) is distinct from '3e8745eedf09f5599b709ee312f57c7d' then raise exception 'rollback_wrong_order_or_function_drift: business_record_history_immutable'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.tenant_workspace_unlink_immutable()')))) is distinct from '1e6b76a3e413abe17d739d738f1aeb8b' then raise exception 'rollback_wrong_order_or_function_drift: tenant_workspace_unlink_immutable'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_business_record(uuid,uuid,text)')))) is distinct from '45fc73249b78999b3dfc777111fb98c6' then raise exception 'rollback_wrong_order_or_function_drift: read_business_record'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_tenant_workspace_link(text,text)')))) is distinct from '794eed11717ac5d81f8909ef8f4c3df1' then raise exception 'rollback_wrong_order_or_function_drift: read_tenant_workspace_link'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_fact_valid(text,jsonb)')))) is distinct from 'c59b51aa14cce9bba1134c508809f6cd' then raise exception 'rollback_wrong_order_or_function_drift: business_record_fact_valid'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.resolve_business_owner_recipient(uuid)')))) is distinct from '6f983ec90643d788c0f191ee7a76ca6b' then raise exception 'rollback_wrong_order_or_function_drift: resolve_business_owner_recipient'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.tenant_conversion_assert_operator(text)')))) is distinct from 'b29934e91512d48f212ad34fcac9bb90' then raise exception 'rollback_wrong_order_or_function_drift: tenant_conversion_assert_operator'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_entity_state(uuid,text,text)')))) is distinct from '9a322a509c07061a386f54c9730b1bab' then raise exception 'rollback_wrong_order_or_function_drift: business_record_entity_state'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_business_contacts(uuid,uuid,text,integer)')))) is distinct from '3c089af4c4fab8d4588160ba6d0cf3c4' then raise exception 'rollback_wrong_order_or_function_drift: read_business_contacts'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_revision_touches_contacts(jsonb)')))) is distinct from 'b4d07bb69ab6e9e1482dc295267fc35c' then raise exception 'rollback_wrong_order_or_function_drift: business_record_revision_touches_contacts'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_text_valid(jsonb,integer,integer)')))) is distinct from 'e75aa173f484842effd7938b9c83c27c' then raise exception 'rollback_wrong_order_or_function_drift: business_record_text_valid'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_assert_actor(uuid,uuid,text,boolean)')))) is distinct from '999536de0dfa3f2df7344d64d73fa61c' then raise exception 'rollback_wrong_order_or_function_drift: business_record_assert_actor'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_business_record_history(uuid,uuid,text,integer)')))) is distinct from '4d643807b5122735b2a70cda0ac5ea8a' then raise exception 'rollback_wrong_order_or_function_drift: read_business_record_history'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.convert_tenant_to_business(text,text,jsonb,uuid,text)')))) is distinct from '6faf66ea079a3f5d1a1ccb803a2e5db2' then raise exception 'rollback_wrong_order_or_function_drift: convert_tenant_to_business'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.unlink_tenant_from_business(text,text,uuid,uuid,text)')))) is distinct from '6bc527678115b71cd3a75103ac94fcf5' then raise exception 'rollback_wrong_order_or_function_drift: unlink_tenant_from_business'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_agency_work_ids(uuid,uuid,text,boolean)')))) is distinct from 'a63daf4cb7a05b32870e4494f5a978d2' then raise exception 'rollback_wrong_order_or_function_drift: business_record_agency_work_ids'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_entity_write(uuid,text,text,jsonb,uuid)')))) is distinct from 'b9d90296a416c862a5700da09473fdf7' then raise exception 'rollback_wrong_order_or_function_drift: business_record_entity_write'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_begin_write(uuid,uuid,text,text,uuid,text)')))) is distinct from '1fbbdb6cd941fdd75e59e3161c8af275' then raise exception 'rollback_wrong_order_or_function_drift: business_record_begin_write'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.upsert_business_contacts(uuid,uuid,text,text,jsonb,uuid,text)')))) is distinct from '47a89de81c79f1644e66b5c1fd0013ea' then raise exception 'rollback_wrong_order_or_function_drift: upsert_business_contacts'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.patch_business_record(uuid,uuid,text,text,bigint,jsonb,uuid,text)')))) is distinct from 'f5d66b2b5c822c9b08f1e791c9c81d02' then raise exception 'rollback_wrong_order_or_function_drift: patch_business_record'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.undo_business_record_revision(uuid,uuid,text,text,bigint,uuid,text)')))) is distinct from '07d390c7de13b13a25038ff0b0d72bb3' then raise exception 'rollback_wrong_order_or_function_drift: undo_business_record_revision'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.business_record_apply(uuid,uuid,text,text,jsonb,jsonb,bigint,uuid,text)')))) is distinct from 'b8b3ceda8e2e138522da8c9571afb1ed' then raise exception 'rollback_wrong_order_or_function_drift: business_record_apply'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_record_revisions') and attnum>0 and not attisdropped) <> 12 then raise exception 'rollback_wrong_order_or_table_drift: business_record_revisions'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.tenant_workspace_links') and attnum>0 and not attisdropped) <> 9 then raise exception 'rollback_wrong_order_or_table_drift: tenant_workspace_links'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_people') and attnum>0 and not attisdropped) <> 14 then raise exception 'rollback_wrong_order_or_table_drift: business_people'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_records') and attnum>0 and not attisdropped) <> 7 then raise exception 'rollback_wrong_order_or_table_drift: business_records'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_record_facts') and attnum>0 and not attisdropped) <> 7 then raise exception 'rollback_wrong_order_or_table_drift: business_record_facts'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_services') and attnum>0 and not attisdropped) <> 15 then raise exception 'rollback_wrong_order_or_table_drift: business_services'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.business_contacts') and attnum>0 and not attisdropped) <> 11 then raise exception 'rollback_wrong_order_or_table_drift: business_contacts'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.tenant_workspace_unlinks') and attnum>0 and not attisdropped) <> 11 then raise exception 'rollback_wrong_order_or_table_drift: tenant_workspace_unlinks'; end if;
end;
$rollback_guard$;
lock table public."business_contacts", public."business_people", public."business_record_facts", public."business_record_revisions", public."business_records", public."business_services", public."tenant_workspace_links", public."tenant_workspace_unlinks" in access exclusive mode;
create schema if not exists release_rollback_archive;
revoke all on schema release_rollback_archive from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_contacts" as table public."business_contacts";
revoke all on release_rollback_archive."m20261002120000_business_contacts" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_people" as table public."business_people";
revoke all on release_rollback_archive."m20261002120000_business_people" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_record_facts" as table public."business_record_facts";
revoke all on release_rollback_archive."m20261002120000_business_record_facts" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_record_revisions" as table public."business_record_revisions";
revoke all on release_rollback_archive."m20261002120000_business_record_revisions" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_records" as table public."business_records";
revoke all on release_rollback_archive."m20261002120000_business_records" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_business_services" as table public."business_services";
revoke all on release_rollback_archive."m20261002120000_business_services" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_tenant_workspace_links" as table public."tenant_workspace_links";
revoke all on release_rollback_archive."m20261002120000_tenant_workspace_links" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261002120000_tenant_workspace_unlinks" as table public."tenant_workspace_unlinks";
revoke all on release_rollback_archive."m20261002120000_tenant_workspace_unlinks" from public, anon, authenticated, service_role;
drop trigger "tenant_workspace_links_immutable" on public."tenant_workspace_links";
drop trigger "tenant_workspace_links_attach_leads" on public."tenant_workspace_links";
drop trigger "tenant_workspace_unlinks_immutable" on public."tenant_workspace_unlinks";
drop trigger "business_record_revisions_immutable" on public."business_record_revisions";
alter table public."business_people" drop constraint "business_people_check";
alter table public."business_contacts" drop constraint "business_contacts_check";
alter table public."business_services" drop constraint "business_services_check";
alter table public."business_contacts" drop constraint "business_contacts_check1";
alter table public."business_people" drop constraint "business_people_name_check";
alter table public."business_people" drop constraint "business_people_email_check";
alter table public."business_people" drop constraint "business_people_phone_check";
alter table public."business_people" drop constraint "business_people_source_check";
alter table public."business_contacts" drop constraint "business_contacts_name_check";
alter table public."business_services" drop constraint "business_services_name_check";
alter table public."business_contacts" drop constraint "business_contacts_email_check";
alter table public."business_contacts" drop constraint "business_contacts_phone_check";
alter table public."business_people" drop constraint "business_people_role_title_check";
alter table public."business_records" drop constraint "business_records_revision_check";
alter table public."business_services" drop constraint "business_services_source_check";
alter table public."business_contacts" drop constraint "business_contacts_sources_check";
alter table public."business_record_facts" drop constraint "business_record_facts_check";
alter table public."business_record_facts" drop constraint "business_record_facts_check1";
alter table public."business_services" drop constraint "business_services_position_check";
alter table public."business_services" drop constraint "business_services_price_text_check";
alter table public."business_records" drop constraint "business_records_last_sequence_check";
alter table public."business_services" drop constraint "business_services_description_check";
alter table public."business_services" drop constraint "business_services_external_ref_check";
alter table public."business_record_facts" drop constraint "business_record_facts_source_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_check";
alter table public."business_record_facts" drop constraint "business_record_facts_fact_key_check";
alter table public."business_services" drop constraint "business_services_duration_minutes_check";
alter table public."tenant_workspace_links" drop constraint "tenant_workspace_links_receipt_check";
alter table public."tenant_workspace_unlinks" drop constraint "tenant_workspace_unlinks_receipt_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_result_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_source_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_changes_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_sequence_check";
alter table public."tenant_workspace_links" drop constraint "tenant_workspace_links_command_digest_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_actor_kind_check";
alter table public."tenant_workspace_unlinks" drop constraint "tenant_workspace_unlinks_command_digest_check";
alter table public."tenant_workspace_links" drop constraint "tenant_workspace_links_tenant_slug_at_link_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_command_digest_check";
alter table public."business_record_revisions" drop constraint "business_record_revisions_record_revision_check";
alter table public."tenant_workspace_unlinks" drop constraint "tenant_workspace_unlinks_tenant_slug_at_unlink_check";
drop function public.tenant_unlink_plan(uuid);
drop function public.business_record_sources();
drop function public.business_contact_sources();
drop function public.tenant_workspace_link_guard();
-- The archived generated value survives; remove its dependency before the function.
alter table public.business_contacts drop column phone_key;
drop function public.business_contact_phone_key(text);
drop function public.preview_tenant_unlink(text,text);
drop function public.business_record_email_valid(text);
drop function public.business_record_time_valid(jsonb);
drop function public.business_record_history_immutable();
drop function public.tenant_workspace_unlink_immutable();
drop function public.read_business_record(uuid,uuid,text);
drop function public.read_tenant_workspace_link(text,text);
drop function public.business_record_fact_valid(text,jsonb);
drop function public.resolve_business_owner_recipient(uuid);
drop function public.tenant_conversion_assert_operator(text);
drop function public.business_record_entity_state(uuid,text,text);
drop function public.read_business_contacts(uuid,uuid,text,integer);
drop function public.business_record_revision_touches_contacts(jsonb);
drop function public.business_record_text_valid(jsonb,integer,integer);
drop function public.business_record_assert_actor(uuid,uuid,text,boolean);
drop function public.read_business_record_history(uuid,uuid,text,integer);
drop function public.convert_tenant_to_business(text,text,jsonb,uuid,text);
drop function public.unlink_tenant_from_business(text,text,uuid,uuid,text);
drop function public.business_record_agency_work_ids(uuid,uuid,text,boolean);
drop function public.business_record_entity_write(uuid,text,text,jsonb,uuid);
drop function public.business_record_begin_write(uuid,uuid,text,text,uuid,text);
drop function public.upsert_business_contacts(uuid,uuid,text,text,jsonb,uuid,text);
drop function public.patch_business_record(uuid,uuid,text,text,bigint,jsonb,uuid,text);
drop function public.undo_business_record_revision(uuid,uuid,text,text,bigint,uuid,text);
drop function public.business_record_apply(uuid,uuid,text,text,jsonb,jsonb,bigint,uuid,text);
drop table public."business_contacts", public."business_people", public."business_record_facts", public."business_record_revisions", public."business_records", public."business_services", public."tenant_workspace_links", public."tenant_workspace_unlinks";
commit;
