-- Rollback for 20261007150000_system_versions.sql
-- Forward SHA-256: 16138552215b58bb5ad7fe84384b3924055b4c02581139d08742efb188c608af
-- Batch 3: reverse file order; undo every later batch first.
-- Prepared SQL only. Production execution requires a separately reviewed approval.
-- Take a verified dump first. Removed data is retained in the private archive schema.
-- Does not undo provider effects or repair Supabase migration history.
begin;
set local lock_timeout = '3s';
set local statement_timeout = '120s';
-- Refuse a later schema or a drifted body; never cascade through unknown objects.
do $rollback_guard$
begin
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_uuid(text)')))) is distinct from '6e5ef23feb51da1f9f3b5ff611e788e9' then raise exception 'rollback_wrong_order_or_function_drift: system_version_uuid'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_version_actor(uuid,text)')))) is distinct from '920c843102cf1d68b98423ca6f82f52e' then raise exception 'rollback_wrong_order_or_function_drift: read_version_actor'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_identity_guard()')))) is distinct from '630aff667f456f5148e01e4757957dfc' then raise exception 'rollback_wrong_order_or_function_drift: system_version_identity_guard'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_history_immutable()')))) is distinct from '931320f5cc99dc45de26f3739a0ba100' then raise exception 'rollback_wrong_order_or_function_drift: system_version_history_immutable'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_system_version(uuid,text,uuid)')))) is distinct from 'f23179cd978ecca6ab9cd8259d184e85' then raise exception 'rollback_wrong_order_or_function_drift: read_system_version'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_connection_owner(text)')))) is distinct from 'a5c9a47446bb21d0226b4b374d302ed1' then raise exception 'rollback_wrong_order_or_function_drift: system_version_connection_owner'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.create_system_version(uuid,text,jsonb)')))) is distinct from 'd0456051452ba0fa90694ae3bdbc1c3c' then raise exception 'rollback_wrong_order_or_function_drift: create_system_version'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_business_versions(uuid,uuid,text)')))) is distinct from '40a1ac6271f58aac4855b0842a56af3b' then raise exception 'rollback_wrong_order_or_function_drift: read_business_versions'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_actor_workspaces(uuid,text)')))) is distinct from 'c51d513eadfa9d49ea6183f2b979e7f7' then raise exception 'rollback_wrong_order_or_function_drift: system_version_actor_workspaces'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_member_role(uuid,uuid,text)')))) is distinct from '6426aaeb080f474f4277a9973c6cbb03' then raise exception 'rollback_wrong_order_or_function_drift: system_version_member_role'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_ts(timestamp with time zone)')))) is distinct from '3c608d41515203fe6970701bf93d8af8' then raise exception 'rollback_wrong_order_or_function_drift: system_version_ts'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_source_visible(uuid,uuid,text)')))) is distinct from '6a79f849a957cb637e72912309f83e57' then raise exception 'rollback_wrong_order_or_function_drift: system_version_source_visible'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_workspace_version_sources(uuid,uuid,text)')))) is distinct from '2c6d8404459fe3fa62c181f7fa64c7eb' then raise exception 'rollback_wrong_order_or_function_drift: read_workspace_version_sources'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_system_version_source(uuid,uuid,text,uuid)')))) is distinct from '021440fbe896acde2483be5e61bb113e' then raise exception 'rollback_wrong_order_or_function_drift: read_system_version_source'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.save_system_version(uuid,text,uuid,bigint,jsonb)')))) is distinct from '789b7157b27f584f5bf7603bcf20a9a3' then raise exception 'rollback_wrong_order_or_function_drift: save_system_version'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_connection_holder(uuid,text,text)')))) is distinct from 'f07980c52bdac76c8150ae4f9b6fa600' then raise exception 'rollback_wrong_order_or_function_drift: system_version_connection_holder'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_system_version_for_system(uuid,uuid,text,uuid)')))) is distinct from '4efcc790337029ea6df1647ef8df8fa0' then raise exception 'rollback_wrong_order_or_function_drift: read_system_version_for_system'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_json(system_versions,text,uuid,text)')))) is distinct from '27ff28873f237d62f770f53582f7d470' then raise exception 'rollback_wrong_order_or_function_drift: system_version_json'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_system_version_connection_owner(uuid,text,text)')))) is distinct from '07edca87338c33e5a946fad7848315d3' then raise exception 'rollback_wrong_order_or_function_drift: read_system_version_connection_owner'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_assert_source_manager(uuid,uuid,text)')))) is distinct from '8d3d5d189efa08d9a31152c3ac0edd28' then raise exception 'rollback_wrong_order_or_function_drift: system_version_assert_source_manager'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.put_system_version_source(uuid,uuid,text,uuid,uuid[])')))) is distinct from 'b60b757f03896275e2ea8d76a6fa1232' then raise exception 'rollback_wrong_order_or_function_drift: put_system_version_source'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.publish_system_version_source_revision(uuid,text,jsonb)')))) is distinct from 'e8619a51f229abe6549d9a193be843fc' then raise exception 'rollback_wrong_order_or_function_drift: publish_system_version_source_revision'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_access(system_versions,uuid,text,boolean)')))) is distinct from 'af549c017d590d7f6b27069e3fef7f7a' then raise exception 'rollback_wrong_order_or_function_drift: system_version_access'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.create_system_version_source(uuid,uuid,text,jsonb,uuid,text)')))) is distinct from 'fb99bf668d5916c4df7f9a4839a6ba97' then raise exception 'rollback_wrong_order_or_function_drift: create_system_version_source'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_source_json(system_version_sources,uuid,text)')))) is distinct from 'e19e9ecaad9df74f7908557bc966c267' then raise exception 'rollback_wrong_order_or_function_drift: system_version_source_json'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.read_system_version_source_revisions(uuid,uuid,text,uuid,integer)')))) is distinct from '07f8e2a1bbc90ded30b543439a3db4cb' then raise exception 'rollback_wrong_order_or_function_drift: read_system_version_source_revisions'; end if;
  if (select md5(pg_get_functiondef(to_regprocedure('public.system_version_revision_json(system_version_source_revisions,uuid)')))) is distinct from '2156ccfdc7c3d254c71474e7f94d373a' then raise exception 'rollback_wrong_order_or_function_drift: system_version_revision_json'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_decisions') and attnum>0 and not attisdropped) <> 8 then raise exception 'rollback_wrong_order_or_table_drift: system_version_decisions'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_overrides') and attnum>0 and not attisdropped) <> 6 then raise exception 'rollback_wrong_order_or_table_drift: system_version_overrides'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_releases') and attnum>0 and not attisdropped) <> 8 then raise exception 'rollback_wrong_order_or_table_drift: system_version_releases'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_sources') and attnum>0 and not attisdropped) <> 5 then raise exception 'rollback_wrong_order_or_table_drift: system_version_sources'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_source_shares') and attnum>0 and not attisdropped) <> 7 then raise exception 'rollback_wrong_order_or_table_drift: system_version_source_shares'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_versions') and attnum>0 and not attisdropped) <> 16 then raise exception 'rollback_wrong_order_or_table_drift: system_versions'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_source_revisions') and attnum>0 and not attisdropped) <> 9 then raise exception 'rollback_wrong_order_or_table_drift: system_version_source_revisions'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_bindings') and attnum>0 and not attisdropped) <> 8 then raise exception 'rollback_wrong_order_or_table_drift: system_version_bindings'; end if;
  if (select count(*) from pg_attribute where attrelid=to_regclass('public.system_version_grants') and attnum>0 and not attisdropped) <> 7 then raise exception 'rollback_wrong_order_or_table_drift: system_version_grants'; end if;
end;
$rollback_guard$;
lock table public."system_version_bindings", public."system_version_decisions", public."system_version_grants", public."system_version_overrides", public."system_version_releases", public."system_version_source_revisions", public."system_version_source_shares", public."system_version_sources", public."system_versions" in access exclusive mode;
create schema if not exists release_rollback_archive;
revoke all on schema release_rollback_archive from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_bindings" as table public."system_version_bindings";
revoke all on release_rollback_archive."m20261007150000_system_version_bindings" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_decisions" as table public."system_version_decisions";
revoke all on release_rollback_archive."m20261007150000_system_version_decisions" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_grants" as table public."system_version_grants";
revoke all on release_rollback_archive."m20261007150000_system_version_grants" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_overrides" as table public."system_version_overrides";
revoke all on release_rollback_archive."m20261007150000_system_version_overrides" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_releases" as table public."system_version_releases";
revoke all on release_rollback_archive."m20261007150000_system_version_releases" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_source_revisions" as table public."system_version_source_revisions";
revoke all on release_rollback_archive."m20261007150000_system_version_source_revisions" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_source_shares" as table public."system_version_source_shares";
revoke all on release_rollback_archive."m20261007150000_system_version_source_shares" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_version_sources" as table public."system_version_sources";
revoke all on release_rollback_archive."m20261007150000_system_version_sources" from public, anon, authenticated, service_role;
create table release_rollback_archive."m20261007150000_system_versions" as table public."system_versions";
revoke all on release_rollback_archive."m20261007150000_system_versions" from public, anon, authenticated, service_role;
drop trigger "system_versions_identity_guard" on public."system_versions";
drop trigger "system_version_releases_immutable" on public."system_version_releases";
drop trigger "system_version_decisions_immutable" on public."system_version_decisions";
drop trigger "system_version_source_revisions_immutable" on public."system_version_source_revisions";
alter table public."system_versions" drop constraint "system_versions_check";
alter table public."system_versions" drop constraint "system_versions_local_data_check";
alter table public."system_versions" drop constraint "system_versions_context_kind_check";
alter table public."system_versions" drop constraint "system_versions_row_revision_check";
alter table public."system_versions" drop constraint "system_versions_context_label_check";
alter table public."system_versions" drop constraint "system_versions_current_release_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_check";
alter table public."system_version_grants" drop constraint "system_version_grants_scope_check";
alter table public."system_versions" drop constraint "system_versions_baseline_revision_check";
alter table public."system_versions" drop constraint "system_versions_baseline_definition_check";
alter table public."system_version_bindings" drop constraint "system_version_bindings_kind_check";
alter table public."system_version_grants" drop constraint "system_version_grants_position_check";
alter table public."system_version_overrides" drop constraint "system_version_overrides_path_check";
alter table public."system_version_releases" drop constraint "system_version_releases_number_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_choice_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_reason_check";
alter table public."system_version_source_shares" drop constraint "system_version_source_shares_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_position_check";
alter table public."system_version_overrides" drop constraint "system_version_overrides_position_check";
alter table public."system_version_releases" drop constraint "system_version_releases_definition_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_resolutions_check";
alter table public."system_version_bindings" drop constraint "system_version_bindings_connection_ref_check";
alter table public."system_version_decisions" drop constraint "system_version_decisions_source_revision_check";
alter table public."system_version_releases" drop constraint "system_version_releases_baseline_revision_check";
alter table public."system_version_source_revisions" drop constraint "system_version_source_revisions_label_check";
alter table public."system_version_source_revisions" drop constraint "system_version_source_revisions_number_check";
alter table public."system_version_source_revisions" drop constraint "system_version_source_revisions_summary_check";
alter table public."system_version_source_revisions" drop constraint "system_version_source_revisions_definition_check";
alter table public."system_version_source_revisions" drop constraint "system_version_source_revisions_requires_binding_kinds_check";
drop function public.system_version_uuid(text);
drop function public.read_version_actor(uuid,text);
drop function public.system_version_identity_guard();
drop function public.system_version_history_immutable();
drop function public.read_system_version(uuid,text,uuid);
drop function public.system_version_connection_owner(text);
drop function public.create_system_version(uuid,text,jsonb);
drop function public.read_business_versions(uuid,uuid,text);
drop function public.system_version_actor_workspaces(uuid,text);
drop function public.system_version_member_role(uuid,uuid,text);
drop function public.system_version_ts(timestamp with time zone);
drop function public.system_version_source_visible(uuid,uuid,text);
drop function public.read_workspace_version_sources(uuid,uuid,text);
drop function public.read_system_version_source(uuid,uuid,text,uuid);
drop function public.save_system_version(uuid,text,uuid,bigint,jsonb);
drop function public.system_version_connection_holder(uuid,text,text);
drop function public.read_system_version_for_system(uuid,uuid,text,uuid);
drop function public.system_version_json(system_versions,text,uuid,text);
drop function public.read_system_version_connection_owner(uuid,text,text);
drop function public.system_version_assert_source_manager(uuid,uuid,text);
drop function public.put_system_version_source(uuid,uuid,text,uuid,uuid[]);
drop function public.publish_system_version_source_revision(uuid,text,jsonb);
drop function public.system_version_access(system_versions,uuid,text,boolean);
drop function public.create_system_version_source(uuid,uuid,text,jsonb,uuid,text);
drop function public.system_version_source_json(system_version_sources,uuid,text);
drop function public.read_system_version_source_revisions(uuid,uuid,text,uuid,integer);
drop function public.system_version_revision_json(system_version_source_revisions,uuid);
drop table public."system_version_bindings", public."system_version_decisions", public."system_version_grants", public."system_version_overrides", public."system_version_releases", public."system_version_source_revisions", public."system_version_source_shares", public."system_version_sources", public."system_versions";
commit;
