import { z } from "zod";
const uuid = z.string().uuid();
const httpsOrigin = z.string().url().refine(value => { try { const u = new URL(value); return u.protocol === "https:" && u.origin === value && !u.username && !u.password; } catch { return false; } }, "Use an exact HTTPS origin");
export const homeFinderInstallSchema = z.object({ workspaceId: uuid, agencyId: uuid, commandId: uuid, name: z.string().trim().min(1).max(160), externalInstallationId: z.string().regex(/^[a-zA-Z0-9_-]{1,160}$/), brokerageName: z.string().trim().min(1).max(160), approvedOrigin: httpsOrigin,
  licenseReference: z.string().trim().min(1).max(500), licenseExpiresAt: z.string().datetime(), sourceName: z.string().trim().min(1).max(200) }).strict();
export const homeFinderBindingSchema = homeFinderInstallSchema.omit({ commandId: true, name: true }).extend({ id: uuid, systemId: uuid, revision: z.number().int().positive(), status: z.enum(["active", "revoked"]), lifecycle: z.enum(["draft", "live", "paused"]), qualifiedAt: z.string().nullable(), runtimeAllowed: z.boolean(), readiness: z.array(z.object({ requirement: z.string(), state: z.enum(["confirmed", "missing", "unverified", "stale"]), source: z.string(), observedAt: z.string(), responsibleParty: z.string() })).nullable() }).strict();
export const homeFinderSearchSchema = z.object({ q: z.string().trim().max(160).optional(), city: z.string().trim().max(100).optional(), minPrice: z.number().nonnegative().optional(), maxPrice: z.number().nonnegative().optional(), minBeds: z.number().int().nonnegative().max(20).optional(), minBaths: z.number().nonnegative().max(20).optional(), limit: z.number().int().min(1).max(50).default(20) }).strict().refine(input => input.minPrice === undefined || input.maxPrice === undefined || input.minPrice <= input.maxPrice);
const safeUrl = z.string().url().refine(value => new URL(value).protocol === "https:");
export const homeFinderListingSchema = z.object({ id: z.string().min(1).max(160), inquiryToken: z.string().min(1).max(160), address: z.object({ line: z.string().max(300), city: z.string(), state: z.string(), postalCode: z.string(), latitude: z.number().nullable(), longitude: z.number().nullable() }), price: z.number().nonnegative(), bedrooms: z.number().nullable(), bathrooms: z.number().nullable(), publicRemarks: z.string().nullable(), photos: z.array(z.object({ url: safeUrl, alt: z.string(), order: z.number() })).max(100), listAgentName: z.string().nullable(), listOfficeName: z.string().nullable(), sourceSystemName: z.string().nullable(), modifiedAt: z.string().nullable(), status: z.enum(["active", "coming-soon", "active-under-contract"]) });
export const homeFinderSearchResultSchema = z.object({ source: z.object({ id: z.literal("trestle"), name: z.string(), mode: z.literal("live"), isLive: z.literal(true), description: z.string(), freshnessWindowMinutes: z.number().positive() }), fetchedAt: z.string().datetime(), sourceCheckedAt: z.string().datetime(), count: z.number().int().nonnegative(), listings: z.array(homeFinderListingSchema).max(50) });
export const homeFinderInquirySchema = z.object({ submissionId: uuid, listing: z.object({ id: z.string().min(1).max(160), address: z.string().min(1).max(300), inquiryToken: z.string().min(1).max(160) }).strict(), buyer: z.object({ name: z.string().trim().min(1).max(120), email: z.string().email().max(254), phone: z.string().max(40).optional() }).strict(), message: z.string().max(2000).optional(), criteria: z.string().max(2000).optional(), consent: z.literal(true), website: z.literal("").optional() }).strict();
export const homeFinderInquiryResultSchema = z.object({ status: z.enum(["pending", "delivered", "unavailable"]), message: z.string(), requestId: z.string().uuid() }).strict();
export type HomeFinderBinding = z.infer<typeof homeFinderBindingSchema>;
export type HomeFinderInstall = z.infer<typeof homeFinderInstallSchema>;
export type HomeFinderSearch = z.infer<typeof homeFinderSearchSchema>;
export type HomeFinderInquiry = z.infer<typeof homeFinderInquirySchema>;
